/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package form;

import javax.swing.JOptionPane;

import entity.BangLuongNhanVien;
import utils.Email;
import utils.TaoFilePDF;

/**
 *
 * @author ACER
 */
public class Dialog_BangLuongNhanVien extends java.awt.Dialog {

    private static final long serialVersionUID = 5675890995973587929L;
	/**
     * Creates new form Frm_BangLuongDialog
     */
    public Dialog_BangLuongNhanVien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Bảng Lương Nhân Viên");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	bangLuongNhanVien = null;
        scrMain = new javax.swing.JScrollPane();
        pnMain = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        pnCenter = new javax.swing.JPanel();
        pnChuaHinhAnh = new javax.swing.JPanel();
        pnThongTinBangLuong = new javax.swing.JPanel();
        pnLuongCS_HeSo = new javax.swing.JPanel();
        lblChucVu2 = new javax.swing.JLabel();
        lblHeSo = new javax.swing.JLabel();
        lblDienHeSo = new javax.swing.JLabel();
        lblLuongCS = new javax.swing.JLabel();
        lblDienLuongCoSo = new javax.swing.JLabel();
        pnNgayCong_VangCoPhep = new javax.swing.JPanel();
        lblChucVu3 = new javax.swing.JLabel();
        lblVangCoPhep = new javax.swing.JLabel();
        lblDienVangCoPhep = new javax.swing.JLabel();
        lblNgayCong = new javax.swing.JLabel();
        lblDienNgayCong = new javax.swing.JLabel();
        pnThamNien_NgayLap = new javax.swing.JPanel();
        lblChucVu4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblThue = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnKhongPhep_TangCa = new javax.swing.JPanel();
        lblChucVu5 = new javax.swing.JLabel();
        lblTangCa = new javax.swing.JLabel();
        lblDienTangCa = new javax.swing.JLabel();
        lblDIenKhongPhep = new javax.swing.JLabel();
        lblKhongPhep = new javax.swing.JLabel();
        pnKhauTru_LuongTruocThue = new javax.swing.JPanel();
        lblChucVu6 = new javax.swing.JLabel();
        lblLuongTruocThue = new javax.swing.JLabel();
        lblDienLuongTruocThue = new javax.swing.JLabel();
        lblKhauTru = new javax.swing.JLabel();
        lblDIenKhauTru = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnMa_Ten17 = new javax.swing.JPanel();
        lblChucVu9 = new javax.swing.JLabel();
        lblLuongThuc = new javax.swing.JLabel();
        lblDienLuongThuc = new javax.swing.JLabel();
        pnNhanVien = new javax.swing.JPanel();
        pnMa_Ten2 = new javax.swing.JPanel();
        lblTen = new javax.swing.JLabel();
        lblMaNhanVien = new javax.swing.JLabel();
        lblDienTen = new javax.swing.JLabel();
        lblDienMa = new javax.swing.JLabel();
        pnMa_Ten3 = new javax.swing.JPanel();
        lblChucVu = new javax.swing.JLabel();
        lblPhongBan = new javax.swing.JLabel();
        lblDIenPhongBan = new javax.swing.JLabel();
        lblCV = new javax.swing.JLabel();
        lblDienChucVu = new javax.swing.JLabel();
        pnMa_Ten9 = new javax.swing.JPanel();
        lblChucVu1 = new javax.swing.JLabel();
        lblThamNien = new javax.swing.JLabel();
        lblDienThamNien = new javax.swing.JLabel();
        pnSouth = new javax.swing.JPanel();
        btnGoiThongBaoLuong = new javax.swing.JButton();
        btnGuiThongTin = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(810, 750));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        add(scrMain, java.awt.BorderLayout.EAST);

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true)));
        pnMain.setPreferredSize(new java.awt.Dimension(620, 700));
        pnMain.setLayout(new java.awt.BorderLayout());

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("Bảng Lương Nhân Viên");
        pnMain.add(lblTieuDe, java.awt.BorderLayout.PAGE_START);

        pnCenter.setBackground(new java.awt.Color(255, 255, 255));

        pnChuaHinhAnh.setBackground(new java.awt.Color(255, 255, 255));

        pnThongTinBangLuong.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTinBangLuong.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)), "Thông tin bảng lương", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        pnThongTinBangLuong.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnThongTinBangLuong.setFocusable(false);

        pnLuongCS_HeSo.setBackground(new java.awt.Color(255, 255, 255));

        lblChucVu2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChucVu2.setText("Chức vụ:");
        lblChucVu2.setMinimumSize(new java.awt.Dimension(74, 40));
        lblChucVu2.setPreferredSize(new java.awt.Dimension(38, 40));

        lblHeSo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHeSo.setText("Hệ Số Lương:");

        lblDienHeSo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblLuongCS.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLuongCS.setText("Lương Cơ Sở:");

        lblDienLuongCoSo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnLuongCS_HeSoLayout = new javax.swing.GroupLayout(pnLuongCS_HeSo);
        pnLuongCS_HeSo.setLayout(pnLuongCS_HeSoLayout);
        pnLuongCS_HeSoLayout.setHorizontalGroup(
            pnLuongCS_HeSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLuongCS_HeSoLayout.createSequentialGroup()
                .addComponent(lblLuongCS, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnLuongCS_HeSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLuongCS_HeSoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblChucVu2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnLuongCS_HeSoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDienLuongCoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeSo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienHeSo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnLuongCS_HeSoLayout.setVerticalGroup(
            pnLuongCS_HeSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLuongCS_HeSoLayout.createSequentialGroup()
                .addGroup(pnLuongCS_HeSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblHeSo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnLuongCS_HeSoLayout.createSequentialGroup()
                        .addComponent(lblChucVu2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnLuongCS_HeSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLuongCS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDienLuongCoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblDienHeSo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnNgayCong_VangCoPhep.setBackground(new java.awt.Color(255, 255, 255));

        lblChucVu3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChucVu3.setText("Chức vụ:");
        lblChucVu3.setMinimumSize(new java.awt.Dimension(74, 40));
        lblChucVu3.setPreferredSize(new java.awt.Dimension(38, 40));

        lblVangCoPhep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVangCoPhep.setText("Vắng Có Phép:");

        lblDienVangCoPhep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblNgayCong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNgayCong.setText("Số Ngày Công:");

        lblDienNgayCong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnNgayCong_VangCoPhepLayout = new javax.swing.GroupLayout(pnNgayCong_VangCoPhep);
        pnNgayCong_VangCoPhep.setLayout(pnNgayCong_VangCoPhepLayout);
        pnNgayCong_VangCoPhepLayout.setHorizontalGroup(
            pnNgayCong_VangCoPhepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNgayCong_VangCoPhepLayout.createSequentialGroup()
                .addComponent(lblNgayCong, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnNgayCong_VangCoPhepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNgayCong_VangCoPhepLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblChucVu3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnNgayCong_VangCoPhepLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDienNgayCong, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVangCoPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienVangCoPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnNgayCong_VangCoPhepLayout.setVerticalGroup(
            pnNgayCong_VangCoPhepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVangCoPhep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnNgayCong_VangCoPhepLayout.createSequentialGroup()
                .addComponent(lblChucVu3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnNgayCong_VangCoPhepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayCong, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDienNgayCong, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(lblDienVangCoPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnThamNien_NgayLap.setBackground(new java.awt.Color(255, 255, 255));

        lblChucVu4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChucVu4.setText("Chức vụ:");
        lblChucVu4.setMinimumSize(new java.awt.Dimension(74, 40));
        lblChucVu4.setPreferredSize(new java.awt.Dimension(38, 40));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Ngày Lập:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblThue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblThue.setText("Thuế:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnThamNien_NgayLapLayout = new javax.swing.GroupLayout(pnThamNien_NgayLap);
        pnThamNien_NgayLap.setLayout(pnThamNien_NgayLapLayout);
        pnThamNien_NgayLapLayout.setHorizontalGroup(
            pnThamNien_NgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThamNien_NgayLapLayout.createSequentialGroup()
                .addComponent(lblThue, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnThamNien_NgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThamNien_NgayLapLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblChucVu4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnThamNien_NgayLapLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnThamNien_NgayLapLayout.setVerticalGroup(
            pnThamNien_NgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnThamNien_NgayLapLayout.createSequentialGroup()
                .addComponent(lblChucVu4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnThamNien_NgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThue, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnKhongPhep_TangCa.setBackground(new java.awt.Color(255, 255, 255));

        lblChucVu5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChucVu5.setText("Chức vụ:");
        lblChucVu5.setMinimumSize(new java.awt.Dimension(74, 40));
        lblChucVu5.setPreferredSize(new java.awt.Dimension(38, 40));

        lblTangCa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTangCa.setText("Giờ Tăng Ca:");

        lblDienTangCa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblDIenKhongPhep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnKhongPhep_TangCaLayout = new javax.swing.GroupLayout(pnKhongPhep_TangCa);
        pnKhongPhep_TangCa.setLayout(pnKhongPhep_TangCaLayout);
        pnKhongPhep_TangCaLayout.setHorizontalGroup(
            pnKhongPhep_TangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhongPhep_TangCaLayout.createSequentialGroup()
                .addGroup(pnKhongPhep_TangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKhongPhep_TangCaLayout.createSequentialGroup()
                        .addGap(0, 348, Short.MAX_VALUE)
                        .addComponent(lblChucVu5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnKhongPhep_TangCaLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lblDIenKhongPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTangCa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienTangCa, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnKhongPhep_TangCaLayout.setVerticalGroup(
            pnKhongPhep_TangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTangCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnKhongPhep_TangCaLayout.createSequentialGroup()
                .addComponent(lblChucVu5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDIenKhongPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblDienTangCa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lblKhongPhep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKhongPhep.setText("Không Phép:");

        pnKhauTru_LuongTruocThue.setBackground(new java.awt.Color(255, 255, 255));

        lblChucVu6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChucVu6.setText("Chức vụ:");
        lblChucVu6.setMinimumSize(new java.awt.Dimension(74, 40));
        lblChucVu6.setPreferredSize(new java.awt.Dimension(38, 40));

        lblLuongTruocThue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLuongTruocThue.setText("Lương Trước Thuế:");

        lblDienLuongTruocThue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblKhauTru.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKhauTru.setText("Khẩu trừ:");

        lblDIenKhauTru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnKhauTru_LuongTruocThueLayout = new javax.swing.GroupLayout(pnKhauTru_LuongTruocThue);
        pnKhauTru_LuongTruocThue.setLayout(pnKhauTru_LuongTruocThueLayout);
        pnKhauTru_LuongTruocThueLayout.setHorizontalGroup(
            pnKhauTru_LuongTruocThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhauTru_LuongTruocThueLayout.createSequentialGroup()
                .addComponent(lblKhauTru, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnKhauTru_LuongTruocThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKhauTru_LuongTruocThueLayout.createSequentialGroup()
                        .addGap(0, 269, Short.MAX_VALUE)
                        .addComponent(lblChucVu6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnKhauTru_LuongTruocThueLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDIenKhauTru, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLuongTruocThue, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDienLuongTruocThue, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnKhauTru_LuongTruocThueLayout.setVerticalGroup(
            pnKhauTru_LuongTruocThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhauTru_LuongTruocThueLayout.createSequentialGroup()
                .addGroup(pnKhauTru_LuongTruocThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLuongTruocThue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnKhauTru_LuongTruocThueLayout.createSequentialGroup()
                        .addComponent(lblChucVu6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnKhauTru_LuongTruocThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKhauTru, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDIenKhauTru, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57))
            .addGroup(pnKhauTru_LuongTruocThueLayout.createSequentialGroup()
                .addComponent(lblDienLuongTruocThue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        pnMa_Ten17.setBackground(new java.awt.Color(255, 255, 255));

        lblChucVu9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChucVu9.setText("Chức vụ:");
        lblChucVu9.setMinimumSize(new java.awt.Dimension(74, 40));
        lblChucVu9.setPreferredSize(new java.awt.Dimension(38, 40));

        lblLuongThuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLuongThuc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLuongThuc.setText("Thực Nhận:");

        lblDienLuongThuc.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblDienLuongThuc.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout pnMa_Ten17Layout = new javax.swing.GroupLayout(pnMa_Ten17);
        pnMa_Ten17.setLayout(pnMa_Ten17Layout);
        pnMa_Ten17Layout.setHorizontalGroup(
            pnMa_Ten17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMa_Ten17Layout.createSequentialGroup()
                .addComponent(lblLuongThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienLuongThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChucVu9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnMa_Ten17Layout.setVerticalGroup(
            pnMa_Ten17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMa_Ten17Layout.createSequentialGroup()
                .addComponent(lblChucVu9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLuongThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMa_Ten17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDienLuongThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnThongTinBangLuongLayout = new javax.swing.GroupLayout(pnThongTinBangLuong);
        pnThongTinBangLuong.setLayout(pnThongTinBangLuongLayout);
        pnThongTinBangLuongLayout.setHorizontalGroup(
            pnThongTinBangLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLuongCS_HeSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnNgayCong_VangCoPhep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnThongTinBangLuongLayout.createSequentialGroup()
                .addComponent(lblKhongPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnThamNien_NgayLap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnThongTinBangLuongLayout.createSequentialGroup()
                .addGroup(pnThongTinBangLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnKhauTru_LuongTruocThue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnThongTinBangLuongLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinBangLuongLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnMa_Ten17, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
            .addGroup(pnThongTinBangLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThongTinBangLuongLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnKhongPhep_TangCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnThongTinBangLuongLayout.setVerticalGroup(
            pnThongTinBangLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinBangLuongLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnLuongCS_HeSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnNgayCong_VangCoPhep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lblKhongPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnThamNien_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnKhauTru_LuongTruocThue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMa_Ten17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(pnThongTinBangLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThongTinBangLuongLayout.createSequentialGroup()
                    .addGap(139, 139, 139)
                    .addComponent(pnKhongPhep_TangCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(330, Short.MAX_VALUE)))
        );

        pnNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        pnNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông Tin Nhân Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pnNhanVien.setDoubleBuffered(false);

        pnMa_Ten2.setBackground(new java.awt.Color(255, 255, 255));

        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTen.setText("Tên Nhân Viên:");
        lblTen.setToolTipText("");
        lblTen.setMinimumSize(new java.awt.Dimension(74, 40));
        lblTen.setPreferredSize(new java.awt.Dimension(38, 40));

        lblMaNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaNhanVien.setText("Mã Nhân Viên:");
        lblMaNhanVien.setMinimumSize(new java.awt.Dimension(74, 40));
        lblMaNhanVien.setPreferredSize(new java.awt.Dimension(38, 40));

        lblDienTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblDienMa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnMa_Ten2Layout = new javax.swing.GroupLayout(pnMa_Ten2);
        pnMa_Ten2.setLayout(pnMa_Ten2Layout);
        pnMa_Ten2Layout.setHorizontalGroup(
            pnMa_Ten2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMa_Ten2Layout.createSequentialGroup()
                .addComponent(lblMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienMa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienTen, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnMa_Ten2Layout.setVerticalGroup(
            pnMa_Ten2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lblDienTen, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
            .addComponent(lblDienMa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pnMa_Ten3.setBackground(new java.awt.Color(255, 255, 255));

        lblChucVu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChucVu.setText("Chức vụ:");
        lblChucVu.setMinimumSize(new java.awt.Dimension(74, 40));
        lblChucVu.setPreferredSize(new java.awt.Dimension(38, 40));

        lblPhongBan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhongBan.setText("Phòng Ban:");

        lblDIenPhongBan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblCV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCV.setText("Chức Vụ:");

        lblDienChucVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnMa_Ten3Layout = new javax.swing.GroupLayout(pnMa_Ten3);
        pnMa_Ten3.setLayout(pnMa_Ten3Layout);
        pnMa_Ten3Layout.setHorizontalGroup(
            pnMa_Ten3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMa_Ten3Layout.createSequentialGroup()
                .addComponent(lblCV, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnMa_Ten3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMa_Ten3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnMa_Ten3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDienChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDIenPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnMa_Ten3Layout.setVerticalGroup(
            pnMa_Ten3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPhongBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnMa_Ten3Layout.createSequentialGroup()
                .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnMa_Ten3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDienChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(lblDIenPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnMa_Ten9.setBackground(new java.awt.Color(255, 255, 255));

        lblChucVu1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChucVu1.setText("Chức vụ:");
        lblChucVu1.setMinimumSize(new java.awt.Dimension(74, 40));
        lblChucVu1.setPreferredSize(new java.awt.Dimension(38, 40));

        lblThamNien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblThamNien.setText("Thâm Niên");

        lblDienThamNien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnMa_Ten9Layout = new javax.swing.GroupLayout(pnMa_Ten9);
        pnMa_Ten9.setLayout(pnMa_Ten9Layout);
        pnMa_Ten9Layout.setHorizontalGroup(
            pnMa_Ten9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMa_Ten9Layout.createSequentialGroup()
                .addComponent(lblThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnMa_Ten9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMa_Ten9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblChucVu1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(334, 334, 334))
                    .addGroup(pnMa_Ten9Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDienThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnMa_Ten9Layout.setVerticalGroup(
            pnMa_Ten9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMa_Ten9Layout.createSequentialGroup()
                .addComponent(lblChucVu1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(pnMa_Ten9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDienThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnNhanVienLayout = new javax.swing.GroupLayout(pnNhanVien);
        pnNhanVien.setLayout(pnNhanVienLayout);
        pnNhanVienLayout.setHorizontalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMa_Ten2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnMa_Ten3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnMa_Ten9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnNhanVienLayout.setVerticalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMa_Ten2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMa_Ten3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMa_Ten9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout pnCenterLayout = new javax.swing.GroupLayout(pnCenter);
        pnCenter.setLayout(pnCenterLayout);
        pnCenterLayout.setHorizontalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenterLayout.createSequentialGroup()
                .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnThongTinBangLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnChuaHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );
        pnCenterLayout.setVerticalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenterLayout.createSequentialGroup()
                .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnChuaHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnCenterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnThongTinBangLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnMain.add(pnCenter, java.awt.BorderLayout.CENTER);

        btnGoiThongBaoLuong.setText("Xuất Bảng Lương");
        btnGoiThongBaoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiThongBaoLuongActionPerformed(evt);
            }
        });
        pnSouth.add(btnGoiThongBaoLuong);

        btnGuiThongTin.setText("Gửi bảng lương");
        btnGuiThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiThongTinActionPerformed(evt);
            }
        });
        pnSouth.add(btnGuiThongTin);

        pnMain.add(pnSouth, java.awt.BorderLayout.SOUTH);

        add(pnMain, java.awt.BorderLayout.CENTER);
        // Tạo một đường viền trắng bên trong


        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnGoiThongBaoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoiThongBaoLuongActionPerformed
        // TODO add your handling code here:
//        btnGoiThongBaoLuong.setVisible(false);
//        btnGuiThongTin.setVisible(false);
//        try {
//            BufferedImage bi = new BufferedImage(pnMain.getWidth(), pnMain.getHeight(), BufferedImage.TYPE_INT_ARGB);
//            pnMain.paint(bi.getGraphics());
//            String path = "C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Desktop\\Code\\QuanLySanPham\\QLyLuongSP\\hau123.jpg";
//            ImageIO.write(bi, "jpg", new File(path));
//            Desktop.getDesktop().print(new File(path));
//            
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
        try {
		TaoFilePDF.createInvoicePdf(bangLuongNhanVien);
        } catch (Exception e) {
		e.printStackTrace();
        }
    }//GEN-LAST:event_btnGoiThongBaoLuongActionPerformed

    private void btnGuiThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiThongTinActionPerformed

        if(Email.guiMailChoNguoiDung(bangLuongNhanVien.getNhanVien().getEmail(), "Bang Luong Nhan Vien ", bangLuongNhanVien)) {
    	   JOptionPane.showMessageDialog(null, "Thông báo đến người dùng thành công");
        }else {
    	   JOptionPane.showMessageDialog(null, "Thất bại");
        }
    }//GEN-LAST:event_btnGuiThongTinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialog_BangLuongNhanVien dialog = new Dialog_BangLuongNhanVien(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private BangLuongNhanVien bangLuongNhanVien;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoiThongBaoLuong;
    private javax.swing.JButton btnGuiThongTin;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCV;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblChucVu1;
    private javax.swing.JLabel lblChucVu2;
    private javax.swing.JLabel lblChucVu3;
    private javax.swing.JLabel lblChucVu4;
    private javax.swing.JLabel lblChucVu5;
    private javax.swing.JLabel lblChucVu6;
    private javax.swing.JLabel lblChucVu9;
    private javax.swing.JLabel lblDIenKhauTru;
    private javax.swing.JLabel lblDIenKhongPhep;
    private javax.swing.JLabel lblDIenPhongBan;
    private javax.swing.JLabel lblDienChucVu;
    private javax.swing.JLabel lblDienHeSo;
    private javax.swing.JLabel lblDienLuongCoSo;
    private javax.swing.JLabel lblDienLuongThuc;
    private javax.swing.JLabel lblDienLuongTruocThue;
    private javax.swing.JLabel lblDienMa;
    private javax.swing.JLabel lblDienNgayCong;
    private javax.swing.JLabel lblDienTangCa;
    private javax.swing.JLabel lblDienTen;
    private javax.swing.JLabel lblDienThamNien;
    private javax.swing.JLabel lblDienVangCoPhep;
    private javax.swing.JLabel lblHeSo;
    private javax.swing.JLabel lblKhauTru;
    private javax.swing.JLabel lblKhongPhep;
    private javax.swing.JLabel lblLuongCS;
    private javax.swing.JLabel lblLuongThuc;
    private javax.swing.JLabel lblLuongTruocThue;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgayCong;
    private javax.swing.JLabel lblPhongBan;
    private javax.swing.JLabel lblTangCa;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblThamNien;
    private javax.swing.JLabel lblThue;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblVangCoPhep;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnChuaHinhAnh;
    private javax.swing.JPanel pnKhauTru_LuongTruocThue;
    private javax.swing.JPanel pnKhongPhep_TangCa;
    private javax.swing.JPanel pnLuongCS_HeSo;
    private javax.swing.JPanel pnMa_Ten17;
    private javax.swing.JPanel pnMa_Ten2;
    private javax.swing.JPanel pnMa_Ten3;
    private javax.swing.JPanel pnMa_Ten9;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnNgayCong_VangCoPhep;
    private javax.swing.JPanel pnNhanVien;
    private javax.swing.JPanel pnSouth;
    private javax.swing.JPanel pnThamNien_NgayLap;
    private javax.swing.JPanel pnThongTinBangLuong;
    private javax.swing.JScrollPane scrMain;
    // End of variables declaration//GEN-END:variables
    public void dayDuLieuVaoBang(BangLuongNhanVien bangLuongNhanVien) {
		this.bangLuongNhanVien = bangLuongNhanVien;
		lblDienMa.setText(bangLuongNhanVien.getNhanVien().getMaNhanSu());
		lblDienTen.setText(bangLuongNhanVien.getNhanVien().getTen());
		lblDienChucVu.setText(bangLuongNhanVien.getNhanVien().getChucVu().getTenChucVu());
		lblDIenPhongBan.setText(bangLuongNhanVien.getNhanVien().getBan().getTenPhongBan());
		lblDienThamNien.setText(bangLuongNhanVien.getNhanVien().getThamNiem()+"");
		lblDienLuongCoSo.setText(bangLuongNhanVien.getNhanVien().getChucVu().getHeSoLuong()+"");
		lblDienHeSo.setText(bangLuongNhanVien.getNhanVien().getHeSoLuong()+"");
		lblDienNgayCong.setText(bangLuongNhanVien.getSoNgayDiLam()+"");
		lblDienVangCoPhep.setText(bangLuongNhanVien.getSoNgayVangCoPhep()+"");
		lblDIenKhongPhep.setText(bangLuongNhanVien.getSoNgayVangKhongPhep()+"");
		lblDienTangCa.setText(bangLuongNhanVien.getSoGioTangCa()+"");
		jLabel21.setText(bangLuongNhanVien.layThuePhaiTra()+"");
		jLabel19.setText(bangLuongNhanVien.getNgayLap().toString());
		lblDIenKhauTru.setText(bangLuongNhanVien.khauTruTuBaoHiemYTeVaBaoHiemXaHoi()+"");
		lblDienLuongTruocThue.setText(bangLuongNhanVien.tongThuNhapCaNhanTruocThue()+"");
		lblDienLuongThuc.setText(bangLuongNhanVien.layLuongThucChoNhanVien()+"");
	}


}
