/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package form;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import DAO.TaiKhoan_Dao;

/**
 *
 * @author ACER
 */
public class Dialog_QuenMatKhau extends java.awt.Dialog {

    private static final long serialVersionUID = 1L;
	/**
     * Creates new form QuenMatKhauDialog
     */
    public Dialog_QuenMatKhau(java.awt.Frame parent, boolean modal, String ma) {
        super(parent, modal);
        initComponents(ma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String ma) {

        pnMain = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        pwdMatKhau = new javax.swing.JPasswordField();
        pwdXacNhan = new javax.swing.JPasswordField();
        lblXacNhan = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 360));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(300, 300));

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("Đổi Mật Khẩu");

        lblMatKhau.setText("Mật khẩu mới");

        lblXacNhan.setText("Xác nhận mật khẩu");

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				xacNhanMatKhau(ma);
			}
		});

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTieuDe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblXacNhan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwdXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(btnXacNhan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        add(pnMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void xacNhanMatKhau(String ma) {
		try {
			String matKhau = pwdMatKhau.getText().trim();
			String xacNhanMatKhau = pwdXacNhan.getText().trim();
			System.out.println(matKhau);
			System.out.println(xacNhanMatKhau);
			kiemTraMatKhau(matKhau);
			kiemTraMatKhau(xacNhanMatKhau);
			if(matKhau.equals(xacNhanMatKhau)) {
				if(TaiKhoan_Dao.doiMatKhau(ma, xacNhanMatKhau)) {
					JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công");
					this.dispose();
				}					
				else 
					JOptionPane.showMessageDialog(null, "Đổi mật khẩu thất bại");
			}
		} catch (Exception e) {
			// TODO: handle exception
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
	}

	/**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                QuenMatKhauDialog dialog = new QuenMatKhauDialog(new java.awt.Frame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblXacNhan;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPasswordField pwdMatKhau;
    private javax.swing.JPasswordField pwdXacNhan;
    // End of variables declaration//GEN-END:variables
    
    private boolean kiemTraMatKhau(String matKhau) throws Exception {
        if(matKhau.isEmpty() || matKhau.equals("Mật Khẩu")){
                throw new Exception("Mật khẩu không được để trống");
            }else if(matKhau.length()<4){
            	throw new Exception("Độ dài kí tự phải từ 4 trở lên");
            }else if(!matKhau.matches("[a-zA-Z0-9@$!%*&]{4,}")){
            	throw new Exception("Mật khẩu gồm chữ số và kí tự đặt biết");
        }
        	return true;
    }
}
