/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.AffineTransform;
import javax.swing.Timer;

/**
 *
 * @author ACER
 */
public class Frm_TrangChu extends javax.swing.JPanel {
    private static String originalTitle = "Quản Lý Lương Sản Phẩm";
    private int currentIndex = 0;
    /**
     * Creates new form Frm_TrangChu
     */
    public Frm_TrangChu() {
        initComponents();
//        rotateLabelText();
        Timer timer = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateLabel();
            }
        });
        timer.start();
    }
    private void updateLabel() {
        if (currentIndex < originalTitle.length()) {
            lblTieuDe.setText(originalTitle.substring(0, currentIndex + 1));
            currentIndex++;
        } else {
            // Reset the index and start over
            
            currentIndex = 0;
            lblTieuDe.setText("");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hinhNen1 = new form.HinhNen("img/keToan.jpg");
        lblTieuDe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1250, 680));
        setLayout(new java.awt.BorderLayout());

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("Quản Lý Lương Sản Phẩm Gỗ");

        javax.swing.GroupLayout hinhNen1Layout = new javax.swing.GroupLayout(hinhNen1);
        hinhNen1.setLayout(hinhNen1Layout);
        hinhNen1Layout.setHorizontalGroup(
            hinhNen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        hinhNen1Layout.setVerticalGroup(
            hinhNen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hinhNen1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(609, Short.MAX_VALUE))
        );

        add(hinhNen1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private form.HinhNen hinhNen1;
    private javax.swing.JLabel lblTieuDe;
    // End of variables declaration//GEN-END:variables
}
