/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import DAO.ChuyenMon_Dao;
import DAO.CongNhan_Dao;
import DAO.DiaChi_Dao;
import Enum.GioiTinh;
import entity.ChuyenMon;
import entity.CongNhan;


import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.Serializable;
import java.util.Date;
import java.util.Vector;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.JLabel;

/**
 *
 * @author ACER
 */
public class frm_CongNhan_TimKiem extends javax.swing.JPanel implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * Creates new form frm_NhanVien_CapNhat_
     */
    public frm_CongNhan_TimKiem() {
        initComponents();
        loadDuLieuChoCacModal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	qlDiaChi = new DiaChi_Dao();
    	qlCongNhan = new CongNhan_Dao();
        pnBody = new javax.swing.JPanel();
        scrCongNhan = new javax.swing.JScrollPane();
        tblCongNhan = new javax.swing.JTable();
        pnDienThongTin = new javax.swing.JPanel();
        pnMa_ChuyenMon_GioiTinh = new javax.swing.JPanel();
        lblMa = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        cmbChuyenMon = new javax.swing.JComboBox<>();
        lblChuyenMon = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        cmbGioiTinh = new javax.swing.JComboBox<>();
        pbHo_Ten = new javax.swing.JPanel();
        lblHo = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        lblTen = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        pnCanCuoc_SoDienThoai = new javax.swing.JPanel();
        txtCanCuoc = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        lblCCCD = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        pnDiaChi = new javax.swing.JPanel();
        lblThanhPho_Tinh = new javax.swing.JLabel();
        cmbThanhPho = new javax.swing.JComboBox<>();
        lblQuanHuyen = new javax.swing.JLabel();
        cmbQuanHuyen = new javax.swing.JComboBox<>();
        lblXa = new javax.swing.JLabel();
        cmbXa = new javax.swing.JComboBox<>();
        pnNgay = new javax.swing.JPanel();
        lblNgaySinh = new javax.swing.JLabel();
        dcsNgaySinh = new com.toedter.calendar.JDateChooser();
        lblNgayVaoLam = new javax.swing.JLabel();
        dcsNgayVaoLam = new com.toedter.calendar.JDateChooser();
        pnTieuChi = new javax.swing.JPanel();
        chkMa = new javax.swing.JCheckBox();
        chkHo = new javax.swing.JCheckBox();
        chkSoDienThoai = new javax.swing.JCheckBox();
        chkCCCD = new javax.swing.JCheckBox();
        chkChuyenMon = new javax.swing.JCheckBox();
        chkDiaChi = new javax.swing.JCheckBox();
        chkGioiTinh = new javax.swing.JCheckBox();
        chkNgaySInh = new javax.swing.JCheckBox();
        chckNgayVaoLam = new javax.swing.JCheckBox();
        btnTimKiem = new javax.swing.JButton();
        pnHeader = new javax.swing.JPanel();
        pnTieuDe = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(1250, 800));
        setMinimumSize(new java.awt.Dimension(1196, 680));
        setPreferredSize(new java.awt.Dimension(1250, 680));
        setLayout(new java.awt.BorderLayout());

        pnBody.setBackground(new java.awt.Color(255, 255, 255));

        
        tblCongNhan.setPreferredSize(new java.awt.Dimension(200, 80));
        scrCongNhan.setViewportView(tblCongNhan);

        pnDienThongTin.setBackground(new java.awt.Color(255, 255, 255));
        pnDienThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Điền Thông Tin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pnDienThongTin.setMaximumSize(new java.awt.Dimension(500, 250));
        pnDienThongTin.setMinimumSize(new java.awt.Dimension(200, 200));

        pnMa_ChuyenMon_GioiTinh.setBackground(new java.awt.Color(255, 255, 255));

        lblMa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMa.setText("Mã Công Nhân");
        lblMa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtMa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtMa.setEnabled(false);
        txtMa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaFocusGained(evt);
            }
        });
        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });

        cmbChuyenMon.setMaximumRowCount(64);
        cmbChuyenMon.setToolTipText("");
        cmbChuyenMon.setAutoscrolls(true);
        cmbChuyenMon.setBorder(null);
        cmbChuyenMon.setEnabled(false);
        cmbChuyenMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChuyenMonActionPerformed(evt);
            }
        });

        lblChuyenMon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChuyenMon.setText("Chuyên Môn");
        lblChuyenMon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        lblChuyenMon.setPreferredSize(new java.awt.Dimension(71, 29));

        lblGioiTinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGioiTinh.setText("Giới tính");
        lblGioiTinh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        cmbGioiTinh.setAutoscrolls(true);
        cmbGioiTinh.setEnabled(false);

        javax.swing.GroupLayout pnMa_ChuyenMon_GioiTinhLayout = new javax.swing.GroupLayout(pnMa_ChuyenMon_GioiTinh);
        pnMa_ChuyenMon_GioiTinh.setLayout(pnMa_ChuyenMon_GioiTinhLayout);
        pnMa_ChuyenMon_GioiTinhLayout.setHorizontalGroup(
            pnMa_ChuyenMon_GioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMa_ChuyenMon_GioiTinhLayout.createSequentialGroup()
                .addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChuyenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbChuyenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnMa_ChuyenMon_GioiTinhLayout.setVerticalGroup(
            pnMa_ChuyenMon_GioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMa_ChuyenMon_GioiTinhLayout.createSequentialGroup()
                .addGroup(pnMa_ChuyenMon_GioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnMa_ChuyenMon_GioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbGioiTinh)
                        .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnMa_ChuyenMon_GioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnMa_ChuyenMon_GioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbChuyenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblChuyenMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pbHo_Ten.setBackground(new java.awt.Color(255, 255, 255));

        lblHo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHo.setText("Họ");
        lblHo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtHo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHo.setText("Nhập Họ");
        txtHo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtHo.setEnabled(false);
        txtHo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoFocusLost(evt);
            }
        });
        txtHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoActionPerformed(evt);
            }
        });

        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTen.setText("Tên");
        lblTen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtTen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTen.setText("Nhập Tên");
        txtTen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtTen.setEnabled(false);
        txtTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenFocusLost(evt);
            }
        });
        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pbHo_TenLayout = new javax.swing.GroupLayout(pbHo_Ten);
        pbHo_Ten.setLayout(pbHo_TenLayout);
        pbHo_TenLayout.setHorizontalGroup(
            pbHo_TenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbHo_TenLayout.createSequentialGroup()
                .addComponent(lblHo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pbHo_TenLayout.setVerticalGroup(
            pbHo_TenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pbHo_TenLayout.createSequentialGroup()
                .addGroup(pbHo_TenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTen, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtHo)
                    .addComponent(lblHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnCanCuoc_SoDienThoai.setBackground(new java.awt.Color(255, 255, 255));

        txtCanCuoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCanCuoc.setText("Căn cước");
        txtCanCuoc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtCanCuoc.setEnabled(false);
        txtCanCuoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCanCuocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCanCuocFocusLost(evt);
            }
        });
        txtCanCuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCanCuocActionPerformed(evt);
            }
        });

        lblSDT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSDT.setText("SDT");
        lblSDT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        lblCCCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCCCD.setText("CCCD");
        lblCCCD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtSDT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSDT.setText("Số điện thoại");
        txtSDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        txtSDT.setEnabled(false);
        txtSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSDTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSDTFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnCanCuoc_SoDienThoaiLayout = new javax.swing.GroupLayout(pnCanCuoc_SoDienThoai);
        pnCanCuoc_SoDienThoai.setLayout(pnCanCuoc_SoDienThoaiLayout);
        pnCanCuoc_SoDienThoaiLayout.setHorizontalGroup(
            pnCanCuoc_SoDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCanCuoc_SoDienThoaiLayout.createSequentialGroup()
                .addComponent(lblCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCanCuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSDT))
        );
        pnCanCuoc_SoDienThoaiLayout.setVerticalGroup(
            pnCanCuoc_SoDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCanCuoc_SoDienThoaiLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(pnCanCuoc_SoDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtSDT)))
            .addComponent(lblCCCD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtCanCuoc, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pnDiaChi.setBackground(new java.awt.Color(255, 255, 255));

        lblThanhPho_Tinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThanhPho_Tinh.setText("Tỉnh");
        lblThanhPho_Tinh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        cmbThanhPho.setMaximumRowCount(64);
        cmbThanhPho.setToolTipText("");
        cmbThanhPho.setAutoscrolls(true);
        cmbThanhPho.setBorder(null);
        cmbThanhPho.setEnabled(false);
        cmbThanhPho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbThanhPhoActionPerformed(evt);
            }
        });

        lblQuanHuyen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanHuyen.setText("Huyện");
        lblQuanHuyen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        cmbQuanHuyen.setMaximumRowCount(64);
        cmbQuanHuyen.setToolTipText("");
        cmbQuanHuyen.setAutoscrolls(true);
        cmbQuanHuyen.setBorder(null);
        cmbQuanHuyen.setEnabled(false);
        cmbQuanHuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQuanHuyenActionPerformed(evt);
            }
        });

        lblXa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXa.setText("Xã");
        lblXa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        cmbXa.setAutoscrolls(true);
        cmbXa.setEnabled(false);

        javax.swing.GroupLayout pnDiaChiLayout = new javax.swing.GroupLayout(pnDiaChi);
        pnDiaChi.setLayout(pnDiaChiLayout);
        pnDiaChiLayout.setHorizontalGroup(
            pnDiaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDiaChiLayout.createSequentialGroup()
                .addComponent(lblThanhPho_Tinh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblXa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbXa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDiaChiLayout.setVerticalGroup(
            pnDiaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDiaChiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnDiaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbThanhPho, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThanhPho_Tinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnDiaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbXa, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addComponent(lblXa, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addComponent(cmbQuanHuyen, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addComponent(lblQuanHuyen, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );

        pnNgay.setBackground(new java.awt.Color(255, 255, 255));

        lblNgaySinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgaySinh.setText("Ngày Sinh");
        lblNgaySinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        lblNgaySinh.setFocusable(false);
        lblNgaySinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        dcsNgaySinh.setEnabled(false);

        lblNgayVaoLam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgayVaoLam.setText("Ngày vào làm");
        lblNgayVaoLam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        dcsNgayVaoLam.setEnabled(false);

        javax.swing.GroupLayout pnNgayLayout = new javax.swing.GroupLayout(pnNgay);
        pnNgay.setLayout(pnNgayLayout);
        pnNgayLayout.setHorizontalGroup(
            pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNgayLayout.createSequentialGroup()
                .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcsNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcsNgayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnNgayLayout.setVerticalGroup(
            pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dcsNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
            .addComponent(lblNgayVaoLam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dcsNgayVaoLam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnDienThongTinLayout = new javax.swing.GroupLayout(pnDienThongTin);
        pnDienThongTin.setLayout(pnDienThongTinLayout);
        pnDienThongTinLayout.setHorizontalGroup(
            pnDienThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDienThongTinLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(pnDienThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pbHo_Ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnCanCuoc_SoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnMa_ChuyenMon_GioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );
        pnDienThongTinLayout.setVerticalGroup(
            pnDienThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDienThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMa_ChuyenMon_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbHo_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnCanCuoc_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pnTieuChi.setBackground(new java.awt.Color(255, 255, 255));
        pnTieuChi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Tiêu chí tìm kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        chkMa.setText("Mã Công Nhân");
        chkMa.setToolTipText("");
        chkMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMaActionPerformed(evt);
            }
        });

        chkHo.setText("Họ Ten Công Nhân");
        chkHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHoActionPerformed(evt);
            }
        });

        chkSoDienThoai.setText("Số điện thoại");
        chkSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSoDienThoaiActionPerformed(evt);
            }
        });

        chkCCCD.setText("CCCD");
        chkCCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCCCDActionPerformed(evt);
            }
        });

        chkChuyenMon.setText("Chuyên môn");
        chkChuyenMon.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                chkChuyenMonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        chkChuyenMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkChuyenMonActionPerformed(evt);
            }
        });

        chkDiaChi.setText("Địa chỉ");
        chkDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDiaChiActionPerformed(evt);
            }
        });

        chkGioiTinh.setText("Giới Tính");
        chkGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGioiTinhActionPerformed(evt);
            }
        });

        chkNgaySInh.setText("Ngày sinh");
        chkNgaySInh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNgaySInhActionPerformed(evt);
            }
        });

        chckNgayVaoLam.setText("Ngày vào làm");
        chckNgayVaoLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckNgayVaoLamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTieuChiLayout = new javax.swing.GroupLayout(pnTieuChi);
        pnTieuChi.setLayout(pnTieuChiLayout);
        pnTieuChiLayout.setHorizontalGroup(
            pnTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTieuChiLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkChuyenMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkNgaySInh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chckNgayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        pnTieuChiLayout.setVerticalGroup(
            pnTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTieuChiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkMa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkHo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkGioiTinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSoDienThoai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCCCD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkChuyenMon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDiaChi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkNgaySInh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckNgayVaoLam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTimKiem.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Documents\\NetBeansProjects\\JavaApplication8\\img\\icons\\magnifying-glass.png")); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				btnTimActionPerformed(e);
			}
		});

        javax.swing.GroupLayout pnBodyLayout = new javax.swing.GroupLayout(pnBody);
        pnBody.setLayout(pnBodyLayout);
        pnBodyLayout.setHorizontalGroup(
            pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrCongNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 1248, Short.MAX_VALUE)
            .addGroup(pnBodyLayout.createSequentialGroup()
                .addGroup(pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBodyLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(pnDienThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(pnTieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnBodyLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBodyLayout.setVerticalGroup(
            pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBodyLayout.createSequentialGroup()
                .addGroup(pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnDienThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(scrCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnBody, java.awt.BorderLayout.CENTER);

        pnHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnHeader.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        pnTieuDe.setBackground(new java.awt.Color(255, 153, 0));

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTieuDe.setText("Tìm Kiếm Công Nhân");
        lblTieuDe.setToolTipText("");
        lblTieuDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnTieuDeLayout = new javax.swing.GroupLayout(pnTieuDe);
        pnTieuDe.setLayout(pnTieuDeLayout);
        pnTieuDeLayout.setHorizontalGroup(
            pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTieuDeLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        pnTieuDeLayout.setVerticalGroup(
            pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTieuDe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );
        
        btnHDSD = new JButton("?");
        btnHDSD.setFont(new Font("Tahoma", Font.BOLD, 10));
        
        lblHDSD = new JLabel("Hướng dẫn sử dụng");

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeaderLayout.setHorizontalGroup(
        	pnHeaderLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnHeaderLayout.createSequentialGroup()
        			.addGroup(pnHeaderLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(pnHeaderLayout.createSequentialGroup()
        					.addGap(354)
        					.addComponent(pnTieuDe, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 79, Short.MAX_VALUE))
        				.addGroup(pnHeaderLayout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblHDSD, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)))
        			.addComponent(btnHDSD)
        			.addGap(19))
        );
        pnHeaderLayout.setVerticalGroup(
        	pnHeaderLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnHeaderLayout.createSequentialGroup()
        			.addGap(22)
        			.addComponent(pnTieuDe, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(29, Short.MAX_VALUE))
        		.addGroup(Alignment.TRAILING, pnHeaderLayout.createSequentialGroup()
        			.addContainerGap(97, Short.MAX_VALUE)
        			.addGroup(pnHeaderLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnHDSD)
        				.addComponent(lblHDSD))
        			.addContainerGap())
        );
        pnHeader.setLayout(pnHeaderLayout);

        add(pnHeader, java.awt.BorderLayout.NORTH);
        
        tblCongNhan.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tblCongNhan.rowAtPoint(e.getPoint());
                if (e.getButton() == MouseEvent.BUTTON1 && row >= 0) {
                    String ma = (String) tblCongNhan.getValueAt(row, 1);
                    CongNhan nv = qlCongNhan.timCongNhanTheoMa(ma);
                    ThongTinNhanVienDialog nhanVienDialog = new ThongTinNhanVienDialog(new Frame() , true);
                    nhanVienDialog.chuyenThanhFormCongNhan();
                    nhanVienDialog.caiDuLieuVaoForm(nv.getAnh(), nv.getMaNhanSu(), nv.getHo()+" "+ nv.getTen(),
                    								nv.getChuyenMon().getTenChuyenMon(), nv.getGioiTinh().getGioiTinh(),
                    								nv.getNgaySinh().toString(), nv.getNgayVaoLam().toString(),
                    								nv.getCCCD(), nv.getSoDienThoai(), (nv.isTrangThai()?"Tham gia":"Không"),
                    								nv.getPhuCap()+"", nv.getDiaChi().toString(), "");
                    nhanVienDialog.setLocationRelativeTo(null);
                    nhanVienDialog.setVisible(true);
                }
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    protected void btnTimActionPerformed(ActionEvent evt) {
    	try {
    		String maCongNhan = "";
        	String ten = "";
        	String ho = "";
        	String cccd = "";
        	String sdt = "";
        	GioiTinh gioiTinh = null;
        	String tinhThanh = "";
        	String quanHuyen = "";
        	String thiXa = "";
        	Date ngaySinh = null;
        	Date ngayVaoLam = null;
        	ChuyenMon chuyenMon = null;
        	
        	maCongNhan = (String) layDuLieuTimKiem(txtMa);
        	chuyenMon = (ChuyenMon) layDuLieuTimKiem(cmbChuyenMon);
        	gioiTinh = (GioiTinh) layDuLieuTimKiem(cmbGioiTinh);
        	ho = (String) layDuLieuTimKiem(txtHo);
        	ten = (String) layDuLieuTimKiem(txtTen);
        	cccd = (String) layDuLieuTimKiem(txtCanCuoc);
        	sdt = (String) layDuLieuTimKiem(txtSDT);
        	tinhThanh = (String) layDuLieuTimKiem(cmbThanhPho);
        	quanHuyen = (String) layDuLieuTimKiem(cmbQuanHuyen);
        	thiXa =(String) layDuLieuTimKiem(cmbXa);
        	ngaySinh = (Date) layDuLieuTimKiem(dcsNgaySinh);
        	ngayVaoLam = (Date) layDuLieuTimKiem(dcsNgayVaoLam);
        	CongNhan mangCongNhan[] = qlCongNhan.tieuChiTimKiemCongNhan(maCongNhan, chuyenMon, gioiTinh,ho, ten, cccd, sdt, tinhThanh, quanHuyen, thiXa, ngaySinh, ngayVaoLam);
        	loadDuLieuNhanVienRaBang(modal, mangCongNhan);
        	lamMoiDuLieu();
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
	}

	private void chkMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMaActionPerformed
        // TODO add your handling code here:
        thayDoiTrangThai(txtMa, chkMa);
        
    }//GEN-LAST:event_chkMaActionPerformed

    private void chkHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHoActionPerformed
        // TODO add your handling code here:
        thayDoiTrangThai(txtHo, chkHo);
        thayDoiTrangThai(txtTen, chkHo);
    }//GEN-LAST:event_chkHoActionPerformed

    private void chkSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSoDienThoaiActionPerformed
        // TODO add your handling code here:
        thayDoiTrangThai(txtSDT, chkSoDienThoai);
    }//GEN-LAST:event_chkSoDienThoaiActionPerformed

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    private void txtHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void txtCanCuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCanCuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCanCuocActionPerformed

    private void cmbThanhPhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbThanhPhoActionPerformed
        // TODO add your handling code here:
    	capNhatDuLIeuQuanHuyen();
    }//GEN-LAST:event_cmbThanhPhoActionPerformed

    private void cmbChuyenMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChuyenMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbChuyenMonActionPerformed

    private void cmbQuanHuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQuanHuyenActionPerformed
        // TODO add your handling code here:
    	capNhatDuLieuThiXa();
    }//GEN-LAST:event_cmbQuanHuyenActionPerformed

    private void chkGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGioiTinhActionPerformed
        // TODO add your handling code here:
        thayDoiTrangThai(cmbGioiTinh, chkGioiTinh);
    }//GEN-LAST:event_chkGioiTinhActionPerformed

    private void chkCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCCCDActionPerformed
        // TODO add your handling code here:
        thayDoiTrangThai(txtCanCuoc, chkCCCD);
    }//GEN-LAST:event_chkCCCDActionPerformed

    private void chkChuyenMonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_chkChuyenMonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_chkChuyenMonAncestorAdded

    private void chkChuyenMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkChuyenMonActionPerformed
        // TODO add your handling code here:
        thayDoiTrangThai(cmbChuyenMon, chkChuyenMon);
    }//GEN-LAST:event_chkChuyenMonActionPerformed

    private void chkDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDiaChiActionPerformed
        // TODO add your handling code here:
        thayDoiTrangThai(cmbThanhPho, chkDiaChi);
        thayDoiTrangThai(cmbQuanHuyen, chkDiaChi);
        thayDoiTrangThai(cmbXa, chkDiaChi);
        loadDuLieuDiaChi();
    }//GEN-LAST:event_chkDiaChiActionPerformed

    private void chkNgaySInhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNgaySInhActionPerformed
        // TODO add your handling code here:
        thayDoiTrangThai(dcsNgaySinh, chkNgaySInh);
    }//GEN-LAST:event_chkNgaySInhActionPerformed

    private void chckNgayVaoLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckNgayVaoLamActionPerformed
        // TODO add your handling code here:
        thayDoiTrangThai(dcsNgayVaoLam, chckNgayVaoLam);
    }//GEN-LAST:event_chckNgayVaoLamActionPerformed

    private void txtMaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaFocusGained

    private void txtHoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoFocusGained
        // TODO add your handling code here:
        String duLieu = txtHo.getText().trim();
        if (duLieu.equalsIgnoreCase("Nhập Họ")) {
            txtHo.setText("");
            txtHo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtHoFocusGained

    private void txtHoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoFocusLost
        // TODO add your handling code here:
        if (txtHo.getText().isEmpty()) {
            txtHo.setText("Nhập Họ");
        }
    }//GEN-LAST:event_txtHoFocusLost

    private void txtTenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenFocusGained
        // TODO add your handling code here:
        String duLieu = txtTen.getText().trim();
        if (duLieu.equalsIgnoreCase("Nhập Tên")) {
            txtTen.setText("");
            txtTen.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtTenFocusGained

    private void txtTenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenFocusLost
        // TODO add your handling code here:
        if (txtTen.getText().isEmpty()) {
            txtTen.setText("Nhập Tên");
        }
    }//GEN-LAST:event_txtTenFocusLost

    private void txtCanCuocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCanCuocFocusGained
        // TODO add your handling code here
        String duLieu = txtCanCuoc.getText().trim();
        if (duLieu.equalsIgnoreCase("Căn cước")) {
            txtCanCuoc.setText("");
            txtCanCuoc.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtCanCuocFocusGained

    private void txtCanCuocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCanCuocFocusLost
        // TODO add your handling code here:
        if (txtCanCuoc.getText().isEmpty()) {
            txtCanCuoc.setText("Căn cước");
        }
    }//GEN-LAST:event_txtCanCuocFocusLost

    private void txtSDTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusGained
        // TODO add your handling code here:
        String duLieu = txtSDT.getText().trim();
        if (duLieu.equalsIgnoreCase("Số điện thoại")) {
            txtSDT.setText("");
            txtSDT.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtSDTFocusGained

    private void txtSDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusLost
        // TODO add your handling code here:
        if (txtSDT.getText().isEmpty()) {
            txtSDT.setText("Số điện thoại");
        }
    }//GEN-LAST:event_txtSDTFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DiaChi_Dao qlDiaChi;
    private CongNhan_Dao qlCongNhan;
    private DefaultTableModel modal;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JCheckBox chckNgayVaoLam;
    private javax.swing.JCheckBox chkCCCD;
    private javax.swing.JCheckBox chkChuyenMon;
    private javax.swing.JCheckBox chkDiaChi;
    private javax.swing.JCheckBox chkGioiTinh;
    private javax.swing.JCheckBox chkHo;
    private javax.swing.JCheckBox chkMa;
    private javax.swing.JCheckBox chkNgaySInh;
    private javax.swing.JCheckBox chkSoDienThoai;
    private javax.swing.JComboBox<ChuyenMon> cmbChuyenMon;
    private javax.swing.JComboBox<GioiTinh> cmbGioiTinh;
    private javax.swing.JComboBox<String> cmbQuanHuyen;
    private javax.swing.JComboBox<String> cmbThanhPho;
    private javax.swing.JComboBox<String> cmbXa;
    private com.toedter.calendar.JDateChooser dcsNgaySinh;
    private com.toedter.calendar.JDateChooser dcsNgayVaoLam;
    private javax.swing.JLabel lblCCCD;
    private javax.swing.JLabel lblChuyenMon;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHo;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblQuanHuyen;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblThanhPho_Tinh;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblXa;
    private javax.swing.JPanel pbHo_Ten;
    private javax.swing.JPanel pnBody;
    private javax.swing.JPanel pnCanCuoc_SoDienThoai;
    private javax.swing.JPanel pnDiaChi;
    private javax.swing.JPanel pnDienThongTin;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnMa_ChuyenMon_GioiTinh;
    private javax.swing.JPanel pnNgay;
    private javax.swing.JPanel pnTieuChi;
    private javax.swing.JPanel pnTieuDe;
    private javax.swing.JScrollPane scrCongNhan;
    private javax.swing.JTable tblCongNhan;
    private javax.swing.JTextField txtCanCuoc;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private JButton btnHDSD;
    private JLabel lblHDSD;
    // End of variables declaration//GEN-END:variables
    
    private Object layDuLieuTimKiem(Component com) {
    	if(com.isEnabled()) {
    		if(com instanceof JTextField) {
    			return (String)((JTextField) com).getText().trim();
    		}else if(com instanceof JComboBox) {
    			return ((JComboBox<?>) com).getSelectedItem();
    		}else if(com instanceof JDateChooser) {
    			return ((JDateChooser) com).getDate();
    		}else if(com instanceof JCheckBox) {
    			return ((JCheckBox) com).isSelected();
    		}
    	}else {
    		if(com instanceof JCheckBox)
    			return false;
    		return null;
    	}
		return null;
    }
    
    public void thayDoiTrangThai(Component com, JCheckBox chk){
        if(chk.isSelected()){
            com.setEnabled(true);
        }else{
            com.setEnabled(false);
        }
    }
    
    public void loadDuLieuChoCacModal(){
        loadDuLieuChoChuyenMon();
        loadDuLieuChoGioiTinh();
        bangDuLieuCongNhan();
    }
    
    private void loadDuLieuDiaChi() {
        loadDuLieuTinh();
        capNhatDuLIeuQuanHuyen();
        capNhatDuLieuThiXa();
    }

    private void loadDuLieuTinh() {
    	DiaChi_Dao qlDiaChi = new DiaChi_Dao();
		String quanHuyen[] = qlDiaChi.layDanhSachTinhThanhPho();
		cmbThanhPho.removeAllItems();
		cmbThanhPho.addItem("Bất Kì");
		for(int i=0;i<quanHuyen.length;i++)
			cmbThanhPho.addItem(quanHuyen[i]);
	}

	private void loadDuLieuChoGioiTinh() {
    	cmbGioiTinh.addItem(GioiTinh.NAM);
    	cmbGioiTinh.addItem(GioiTinh.NU);
    	cmbGioiTinh.addItem(GioiTinh.KHAC);
	}

	private void loadDuLieuChoChuyenMon() {
        ChuyenMon_Dao qlChuyenMon = new ChuyenMon_Dao();
        for (ChuyenMon chuyenMon : qlChuyenMon.getDs()) {
            cmbChuyenMon.addItem(chuyenMon);
        }
    }
	
	protected void capNhatDuLIeuQuanHuyen() {
		String TinhThanhPhpDaChon = (String) cmbThanhPho.getSelectedItem();
		cmbQuanHuyen.removeAllItems();
		if(TinhThanhPhpDaChon == null || TinhThanhPhpDaChon.equalsIgnoreCase("Bất Kì")) {	
			return;
		}		
		String quanHuyen[] = qlDiaChi.layQuanHuyenDuaTheoTinhThanhPho(TinhThanhPhpDaChon.trim());		
		cmbQuanHuyen.addItem("Bất Kì");
		for(int i=0;i<quanHuyen.length;i++)
			cmbQuanHuyen.addItem(quanHuyen[i]);
	}
    
    protected void capNhatDuLieuThiXa() {
		try {
			String TinhThanhPhpDaChon = (String) cmbThanhPho.getSelectedItem();
			String quanHuyenDaChon = (String) cmbQuanHuyen.getSelectedItem();
			cmbXa.removeAllItems();
			if(TinhThanhPhpDaChon == null || TinhThanhPhpDaChon.equalsIgnoreCase("Bất Kì") || quanHuyenDaChon == null || quanHuyenDaChon.equalsIgnoreCase("Bất Kì"))
				return;
			String thiXa[] = qlDiaChi.layPhuongXaDuaTrenQuanHuyenVaTinhThanhPho(TinhThanhPhpDaChon.trim(), quanHuyenDaChon.trim());
			cmbXa.addItem("Bất Kì");
			for(int i=0;i<thiXa.length;i++)
				cmbXa.addItem(thiXa[i]);
		} catch (Exception e) {
			// TODO: handle 
			e.printStackTrace();
		}
	}
    
    private void loadDuLieuNhanVienRaBang(DefaultTableModel modal, CongNhan[] mangCongNhan) {
    	int i=1;
    	tblCongNhan.removeAll();
    	modal.setRowCount(0);
        for (CongNhan cn : mangCongNhan) {
        	Vector<String> data = new  Vector<>();
        	data.add(i+"");
        	i++;
        	data.addAll(cn.duLieuFormCapNhat());
        	modal.addRow(data);
        }
	}
    
    private void lamMoiDuLieu() {
    	txtMa.setText("");
    	cmbChuyenMon.setSelectedIndex(0);
    	txtHo.setText("Nhập Họ");
    	txtTen.setText("Nhập Tên");
    	txtCanCuoc.setText("Căn cước");
    	txtSDT.setText("Số điện thoại");
    	dcsNgaySinh.setDate(null);
    	dcsNgayVaoLam.setDate(null);
    	cmbGioiTinh.setSelectedIndex(0);
    	cmbThanhPho.setSelectedIndex(0);
//    	cmbQuanHuyen.setSelectedIndex(0);
//    	cmbXa.setSelectedIndex(0);
    }
    
    private void bangDuLieuCongNhan(){
    	String column[]= {"STT", "Mã Công Nhân", "Họ", "Tên", "SDT", "Căn Cước", "DiaChi", "Giới Tính", "Chuyên Môn", "Trạng Thái"};
        modal = new DefaultTableModel(column, 0) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class,java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false,  false,false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        loadDuLieuNhanVienRaBang(modal, qlCongNhan.layDanhSachCongNhan().toArray(new CongNhan[0]));
        tblCongNhan.setModel(modal); 
    }
    
    
}
