/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import com.toedter.calendar.JDateChooser;

import Enum.CaLamCongNhan;
import GUI.GUI_APP;
import DAO.BangChamCongCongNhan_Dao;
import DAO.CongDoan_Dao;
import DAO.SanPham_Dao;
import entity.BangChamCongCongNhan;
import entity.NhanVien;




/**
 * 
 * @author Vu
 */
public class frm_CongNhan_ChamCong extends javax.swing.JPanel {
	private BangChamCongCongNhan_Dao bangCCCN_Dao;
	private CongDoan_Dao congDoan_Dao;
	private SanPham_Dao sanPham_Dao;
	private ArrayList<BangChamCongCongNhan> listCCCN;
    public GUI_APP app;
    /**
     * Creates new form PanelChamCongCongNhan
     * @param nv 
     */
    public frm_CongNhan_ChamCong(NhanVien nv) {
    	KetNoiCSDL();
        initComponents(nv);
        
    }
    // khởi tạo kết nối đến CSDL
 	public void KetNoiCSDL() {
 		try {
			ConnectDB.ConnectDB.getInstance().connect();
		} catch (SQLException e) {
			e.printStackTrace();
		}
 		bangCCCN_Dao = new BangChamCongCongNhan_Dao();
 		congDoan_Dao = new CongDoan_Dao();
 		sanPham_Dao = new SanPham_Dao();
 	}
 	

 	//chấm công hôm nay
 	private void loadBangChamHomNay() {
 		SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String strDate = formatter.format(dateChNgayCham.getDate());
        System.out.println(strDate);
 		ArrayList<BangChamCongCongNhan> listCCCNHomNay = bangCCCN_Dao.layDanhSachChamCongCNHomNay(strDate);
 		for (BangChamCongCongNhan bcc : listCCCNHomNay) {
 			modelBCCCN.addRow(new Object[] {listCCCNHomNay.indexOf(bcc)+1, 
 					bcc.getMaBangChamCong(),
 					bcc.getChamCongDoan().getCongNhanDamNhan().getMaNhanSu(),
 					bcc.getChamCongDoan().getCongNhanDamNhan().getTen(),
 					bcc.getNgayChamCong(),
 					bcc.getCaLam(),
 					bcc.isTrangThai()? "Có mặt":"Vắng mặt",
 					bcc.getChamCongDoan().getCongDoan().getSanPham().getTenSP(),
 					bcc.getChamCongDoan().getCongDoan().getLoaiCongDoan(),
 					bcc.getSoLuongSanPhamHoanThanh(), 
 					bcc.getNguoiChamCong().getTen()
 			});
 		}	
 	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(NhanVien nv) {

        jLabel1 = new javax.swing.JLabel();
        dateChNgayCham = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangCCCN = new javax.swing.JTable();
        txtTimKiemBangCCCN = new javax.swing.JTextField();
        btnLayDSPhanCong = new javax.swing.JButton();
        chkHomNay = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtMaPhanCong = new javax.swing.JLabel();
        txtMaCongNhan = new javax.swing.JLabel();
        txtTenCongNhan = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JLabel();
        txtTenCongDoan = new javax.swing.JLabel();
        txtNguoiCham = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JLabel();
        cmbCaLam = new javax.swing.JComboBox<>();
        cmbTrangThai = new javax.swing.JComboBox<>();
        addPlaceholder(txtTimKiemBangCCCN, "Nhập để tìm kiếm...");
        
        setPreferredSize(new java.awt.Dimension(1295, 634));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Chấm công công nhân");

        
        dateChNgayCham.setPreferredSize(new java.awt.Dimension(300, 28));
        dateChNgayCham.setDateFormatString("yyyy-MM-dd");
        dateChNgayCham.setEnabled(false);
        dateChNgayCham.setDate(new Date());
        
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ngày chấm công:");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bảng chấm công công nhân"));
        String[] colsDV = { "STT", "Mã chấm công", "Mã công nhân", "Tên công nhân", "Ngày chấm", "Ca làm", "Trạng thái", "Tên sản phẩm", "Tên công đoạn", "Số lượng làm", "Người chấm" };
		modelBCCCN = new DefaultTableModel(colsDV, 0);
		tblBangCCCN = new JTable(modelBCCCN);
        jScrollPane1.setViewportView(tblBangCCCN);

        //Tìm kiếm bảng chấm công công nhân
        txtTimKiemBangCCCN.addKeyListener(new KeyAdapter() {
			@Override
			public void keyReleased(KeyEvent e) {
				String text = txtTimKiemBangCCCN.getText().toLowerCase();
				TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(modelBCCCN);
				tblBangCCCN.setRowSorter(sorter);
				sorter.setRowFilter(RowFilter.regexFilter(text));
				if (text.trim().length() == 0) {
					sorter.setRowFilter(null);
				} else {
					sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
					modelBCCCN.setRowCount(0);
					loadBangChamHomNay();
				}
			}
		});
     
        tblBangCCCN.addMouseListener(new MouseListener() {	
			@Override
			public void mouseReleased(MouseEvent e) {}
			@Override
			public void mousePressed(MouseEvent e) {}
			@Override
			public void mouseExited(MouseEvent e) {}	
			@Override
			public void mouseEntered(MouseEvent e) {}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				int pos = tblBangCCCN.getSelectedRow();
				txtMaPhanCong.setText(modelBCCCN.getValueAt(pos, 1).toString());
				txtMaCongNhan.setText(modelBCCCN.getValueAt(pos, 2).toString());
				txtTenCongNhan.setText(modelBCCCN.getValueAt(pos, 3).toString());
				txtTenSanPham.setText(modelBCCCN.getValueAt(pos, 7).toString());
				txtTenCongDoan.setText(modelBCCCN.getValueAt(pos, 8).toString());
				txtNguoiCham.setText(modelBCCCN.getValueAt(pos, 10).toString());
				cmbCaLam.setSelectedItem(modelBCCCN.getValueAt(pos, 5).toString());
				cmbTrangThai.setSelectedItem(modelBCCCN.getValueAt(pos, 6).toString());
				txtSoLuong.setText(modelBCCCN.getValueAt(pos, 9).toString());
			}
		});

        btnLayDSPhanCong.setBackground(new java.awt.Color(89, 193, 99));
        btnLayDSPhanCong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLayDSPhanCong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/item/icons8-add-24.png"))); // NOI18N
        btnLayDSPhanCong.setText("Lấy danh sách phân công");
        btnLayDSPhanCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayDSPhanCongActionPerformed(evt, nv);
                modelBCCCN.setRowCount(0);
                loadBangChamHomNay();
            }
        });
        
        chkHomNay.setText("Hôm nay");
        
     // checkbox hôm nay
// 		chkHomNay.addActionListener(new ActionListener() {
// 			@Override
// 			public void actionPerformed(ActionEvent e) {
// 				if (chkHomNay.isSelected() == true) {
// 					modelBCCCN.setRowCount(0);
// 					loadBangChamHomNay();
// 				} else {
// 					modelBCCCN.setRowCount(0);
// 					loadBangChamCongCongNhan();
// 				}
//
// 			}
// 		});
        
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã chấm công:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã công nhân:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tên công nhân:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tên sản phẩm:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Người chấm:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tên công đoạn:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Ca làm:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Số lượng làm:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Trạng thái:");

        txtMaPhanCong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N


        txtMaCongNhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N


        txtTenCongNhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N


        txtTenSanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
 

        txtTenCongDoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
 

        txtNguoiCham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N


        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N


        cmbCaLam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbCaLam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ca Một", "Ca Hai", "Ca Ba" }));

        cmbTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Có mặt", "Vắng mặt" }));
        loadBangChamHomNay();
        
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Chấm công công nhân");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTimKiemBangCCCN, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(dateChNgayCham, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnLayDSPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtNguoiCham, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTenCongDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChNgayCham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                        .addComponent(jLabel9)
                        .addComponent(txtMaPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLayDSPhanCong)
                    .addComponent(jLabel4)
                    .addComponent(txtMaCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTenCongDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cmbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtNguoiCham)
                    .addComponent(jLabel10)
                    .addComponent(txtSoLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(txtTimKiemBangCCCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkHomNayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHomNayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkHomNayActionPerformed

    private void btnLayDSPhanCongActionPerformed(java.awt.event.ActionEvent evt, NhanVien nv) {//GEN-FIRST:event_btnLayDSPhanCongActionPerformed
        // TODO add your handling code here:
        Dialog_DanhSachPhanCong dsPhanCong = new Dialog_DanhSachPhanCong(app, true, nv);
        dsPhanCong.setLocationRelativeTo(null);
        dsPhanCong.setTitle("Danh sách phân công");
        dsPhanCong.setVisible(true);

    }//GEN-LAST:event_btnLayDSPhanCongActionPerformed

    public static void addPlaceholder(JTextField textField, String placeholder) {
        // Sự kiện khi component focus được bật
        textField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            // Sự kiện khi component focus mất đi
            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(Color.GRAY);
                }
            }
        });

        // Thiết lập màu sắc và placeholder ban đầu
        textField.setForeground(Color.GRAY);
        textField.setText(placeholder);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLayDSPhanCong;
    private javax.swing.JCheckBox chkHomNay;
    private javax.swing.JComboBox<String> cmbCaLam;
    private javax.swing.JComboBox<String> cmbTrangThai;
    private com.toedter.calendar.JDateChooser dateChNgayCham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBangCCCN;
    private javax.swing.JLabel txtMaCongNhan;
    private javax.swing.JLabel txtMaPhanCong;
    private javax.swing.JLabel txtNguoiCham;
    private javax.swing.JLabel txtSoLuong;
    private javax.swing.JLabel txtTenCongDoan;
    private javax.swing.JLabel txtTenCongNhan;
    private javax.swing.JLabel txtTenSanPham;
    private javax.swing.JTextField txtTimKiemBangCCCN;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelBCCCN;
}
