/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;
import Enum.LoaiCongDoan;
import entity.CongDoan;
import entity.SanPham;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import DAO.CongDoan_Dao;
import DAO.DAO_SanPham;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.JLabel;
/**
 *
 * @author ACER
 */
public class frm_SanPham_ChiaCongDoan extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = -6421167478887147299L;
	private DefaultTableModel modalSanPham;
	private DefaultTableModel modalCongDoan;
	/**
     * Creates new form frm_NhanVien_CapNhat_
     */
    public frm_SanPham_ChiaCongDoan() {
        initComponents();
        layDanhSachSanPham();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	qlSanPham = new DAO_SanPham();
        pnBody = new javax.swing.JPanel();
        scrCongDoan = new javax.swing.JScrollPane();
        tblCongDoan = new javax.swing.JTable();
        pnTieuChi = new javax.swing.JPanel();
        chkMa = new javax.swing.JCheckBox();
        chkTen = new javax.swing.JCheckBox();
        chkKhoiLuong = new javax.swing.JCheckBox();
        chkSoLuong = new javax.swing.JCheckBox();
        chkChuyenMon = new javax.swing.JCheckBox();
        chkDiaChi = new javax.swing.JCheckBox();
        chkLoaiGo = new javax.swing.JCheckBox();
        chkKichThuoc = new javax.swing.JCheckBox();
        chkSoCongDoan = new javax.swing.JCheckBox();
        pnDanhSachNhanVien = new javax.swing.JPanel();
        scrDSSP = new javax.swing.JScrollPane();
        tblDSSP = new javax.swing.JTable();
        txtNhapTenSP = new javax.swing.JTextField();
        lblTenSanPham = new javax.swing.JLabel();
        pnCongDoan = new javax.swing.JPanel();
        lblMaCongDoan = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        lblGia = new javax.swing.JLabel();
        lblThuocSanPham = new javax.swing.JLabel();
        txtSanPham = new javax.swing.JTextField();
        lblLoaiCongDoan = new javax.swing.JLabel();
        cmbLoaiCongDoan = new javax.swing.JComboBox<>(new LoaiCongDoan[]{LoaiCongDoan.CATGO, LoaiCongDoan.LAPRAP, LoaiCongDoan.CHETAC, LoaiCongDoan.BEMAT});
        lblSoCongNhan = new javax.swing.JLabel();
        txtSoCongNhan = new javax.swing.JTextField();
        txtSoSanPham = new javax.swing.JTextField();
        lblSoSanPham = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtGia = new javax.swing.JTextField();
        tglThem = new javax.swing.JToggleButton();
        tglSua = new javax.swing.JToggleButton();
        btnXoa = new javax.swing.JButton();
        pnHeader = new javax.swing.JPanel();
        pnTieuDe = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(1250, 680));
        setMinimumSize(new java.awt.Dimension(1196, 680));
        setPreferredSize(new java.awt.Dimension(1250, 680));
        setLayout(new java.awt.BorderLayout());

        pnBody.setBackground(new java.awt.Color(255, 255, 255));
        pnBody.setPreferredSize(new java.awt.Dimension(1250, 548));

        scrCongDoan.setPreferredSize(new java.awt.Dimension(1250, 402));
        modalCongDoan = new DefaultTableModel(new Object [][] {

        },
        new String [] {
            "STT", "Mã Công Đoạn", "Tên Công Đoan", "Thuộc Sản Phẩm", "Lương 1 Công Đoạn", "Số Công Nhân Đảm Nhận",  "Số Thành Phần", "Ngày Chia Công Đoạn"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false, false, false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    };
    
        tblCongDoan.setModel(modalCongDoan);
        tblCongDoan.setPreferredSize(new java.awt.Dimension(1250, 250));
        scrCongDoan.setViewportView(tblCongDoan);
        if (tblCongDoan.getColumnModel().getColumnCount() > 0) {
            tblCongDoan.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblCongDoan.getColumnModel().getColumn(4).setPreferredWidth(50);
        }
        tblCongDoan.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				datDuLieuCongDoanDuocChonVaoForm();
			}
		});

        pnTieuChi.setBackground(new java.awt.Color(255, 255, 255));
        pnTieuChi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Tiêu chí tìm kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        chkMa.setText("Mã Sản Phẩm");
        chkMa.setToolTipText("");

        chkTen.setText("Tên Sản Phẩm");

        chkKhoiLuong.setText("Khối Lượng");

        chkSoLuong.setText("Số lượng");

        chkChuyenMon.setText("Thời hạn sản xuất");

        chkDiaChi.setText("Giá");

        chkLoaiGo.setText("Loai Gỗ");

        chkKichThuoc.setText("Kích thước");

        chkSoCongDoan.setText("Số Công Đoạn");

        chkMa.setSelected(true);

        javax.swing.GroupLayout pnTieuChiLayout = new javax.swing.GroupLayout(pnTieuChi);
        pnTieuChi.setLayout(pnTieuChiLayout);
        pnTieuChiLayout.setHorizontalGroup(
            pnTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTieuChiLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkKhoiLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkChuyenMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkKichThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkLoaiGo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(chkSoCongDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        pnTieuChiLayout.setVerticalGroup(
            pnTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTieuChiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMa)
                    .addComponent(chkSoCongDoan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkTen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkLoaiGo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkKhoiLuong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSoLuong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkChuyenMon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDiaChi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkKichThuoc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chkMa.setSelected(true);

        pnDanhSachNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        pnDanhSachNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Danh Sách Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        tblDSSP.setAutoCreateRowSorter(true);
        modalSanPham = new DefaultTableModel(
                new Object [][] {
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String [] {
                    "STT", "Mã Sản Phẩm", "Tên Sản Phẩm"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                    false, false, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            };
        tblDSSP.setModel(modalSanPham);
        scrDSSP.setViewportView(tblDSSP);
        if (tblDSSP.getColumnModel().getColumnCount() > 0) {
            tblDSSP.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblDSSP.getColumnModel().getColumn(1).setResizable(false);
            tblDSSP.getColumnModel().getColumn(2).setResizable(false);
        }
        tblDSSP.addMouseListener(new MouseListener() {		
			@Override
			public void mouseClicked(MouseEvent e) {
				duLieuLoaiCongDoan();
				xoaTrangForm();
				txtMa.setText("");
				int dongDuocChon = tblDSSP.getSelectedRow();
				if(dongDuocChon>=0) {
					txtSanPham.setText((String)tblDSSP.getValueAt(dongDuocChon, 2));
					layCongDoanTheoSanPhamDuocChon((String)tblDSSP.getValueAt(dongDuocChon, 1));
					kiemTraSoLuong();
				}
			}

			@Override
			public void mousePressed(MouseEvent e) {	
			}

			@Override
			public void mouseReleased(MouseEvent e) {
			}

			@Override
			public void mouseEntered(MouseEvent e) {
			}

			@Override
			public void mouseExited(MouseEvent e) {
			}
		});
        
        tblDSSP.setRowHeight(25);

        lblTenSanPham.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Desktop\\PTUD\\PTUD_APP\\QLyLuongSP\\img\\icons\\magnifying-glass.png")); // NOI18N
        lblTenSanPham.setText("Tìm ");

        javax.swing.GroupLayout pnDanhSachNhanVienLayout = new javax.swing.GroupLayout(pnDanhSachNhanVien);
        pnDanhSachNhanVien.setLayout(pnDanhSachNhanVienLayout);
        pnDanhSachNhanVienLayout.setHorizontalGroup(
            pnDanhSachNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrDSSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
            .addGroup(pnDanhSachNhanVienLayout.createSequentialGroup()
                .addComponent(txtNhapTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnDanhSachNhanVienLayout.setVerticalGroup(
            pnDanhSachNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDanhSachNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDanhSachNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNhapTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrDSSP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        pnCongDoan.setBackground(new java.awt.Color(255, 255, 255));
        pnCongDoan.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true), "Công Đoạn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 102, 0))); // NOI18N
        pnCongDoan.setEnabled(false);

        lblMaCongDoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaCongDoan.setText("Mã Công Đoạn");
        lblMaCongDoan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        txtMa.setEditable(false);
        txtMa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txtMa.setEnabled(false);

        lblGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGia.setText("Giá Thành");
        lblGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        lblThuocSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThuocSanPham.setText("Thuộc Sản Phẩm");
        lblThuocSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        txtSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txtSanPham.setEnabled(false);
        txtSanPham.setEditable(false);

        lblLoaiCongDoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoaiCongDoan.setText("Loại Công Đoạn");
        lblLoaiCongDoan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        cmbLoaiCongDoan.setMaximumRowCount(4);
        cmbLoaiCongDoan.setToolTipText("Loại Công Đoạn ");
        cmbLoaiCongDoan.setEnabled(false);
        cmbLoaiCongDoan.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				cmbLoaiCongDoanActionPerformed(e);
			}
		});

        lblSoCongNhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoCongNhan.setText("Số Công Nhân");
        lblSoCongNhan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        txtSoCongNhan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txtSoCongNhan.setEnabled(false);

        txtSoSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txtSoSanPham.setEnabled(false);


        lblSoSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoSanPham.setText("Số Sản Phẩm ");
        lblSoSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        btnXacNhan.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Desktop\\PTUD\\PTUD_APP\\QLyLuongSP\\img\\icons\\check-mark.png")); // NOI18N
        btnXacNhan.setText("Xác Nhận");
        btnXacNhan.setEnabled(false);
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Desktop\\PTUD\\PTUD_APP\\QLyLuongSP\\img\\icons\\refresh-arrow.png")); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.setEnabled(false);
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Desktop\\PTUD\\PTUD_APP\\QLyLuongSP\\img\\icons\\house.png")); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setEnabled(false);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        txtGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txtGia.setEnabled(false);
        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCongDoanLayout = new javax.swing.GroupLayout(pnCongDoan);
        pnCongDoan.setLayout(pnCongDoanLayout);
        pnCongDoanLayout.setHorizontalGroup(
            pnCongDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCongDoanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnCongDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnCongDoanLayout.createSequentialGroup()
                        .addComponent(lblThuocSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSanPham))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnCongDoanLayout.createSequentialGroup()
                        .addComponent(lblMaCongDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnCongDoanLayout.createSequentialGroup()
                        .addComponent(lblSoCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnCongDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLamMoi)
                            .addComponent(txtSoCongNhan))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnCongDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSoSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnCongDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblLoaiCongDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCongDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtGia)
                    .addComponent(cmbLoaiCongDoan, 0, 133, Short.MAX_VALUE)
                    .addComponent(txtSoSanPham))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCongDoanLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(btnXacNhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        pnCongDoanLayout.setVerticalGroup(
            pnCongDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCongDoanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnCongDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaCongDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCongDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCongDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblThuocSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLoaiCongDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLoaiCongDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCongDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCongDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSoCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSoCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCongDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSoSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSoSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(pnCongDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        tglThem.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Desktop\\PTUD\\PTUD_APP\\QLyLuongSP\\img\\icons\\plus.png")); // NOI18N
        tglThem.setText("Thêm");
        tglThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglThemActionPerformed(evt);
            }
        });

        tglSua.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Desktop\\PTUD\\PTUD_APP\\QLyLuongSP\\img\\icons\\edit.png")); // NOI18N
        tglSua.setText("Sửa");
        tglSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Desktop\\PTUD\\PTUD_APP\\QLyLuongSP\\img\\icons\\bin.png")); // NOI18N
        btnXoa.setText("Xóa Chọn Trên Bảng");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBodyLayout = new javax.swing.GroupLayout(pnBody);
        pnBodyLayout.setHorizontalGroup(
        	pnBodyLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnBodyLayout.createSequentialGroup()
        			.addGroup(pnBodyLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(scrCongDoan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(pnBodyLayout.createSequentialGroup()
        					.addGroup(pnBodyLayout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(pnBodyLayout.createSequentialGroup()
        							.addGap(731)
        							.addComponent(tglThem)
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(tglSua)
        							.addGap(65)
        							.addComponent(btnXoa))
        						.addGroup(pnBodyLayout.createSequentialGroup()
        							.addGap(81)
        							.addComponent(pnDanhSachNhanVien, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(78)
        							.addComponent(pnCongDoan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        					.addGap(430)
        					.addComponent(pnTieuChi, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBodyLayout.setVerticalGroup(
        	pnBodyLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnBodyLayout.createSequentialGroup()
        			.addComponent(pnTieuChi, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(341, Short.MAX_VALUE))
        		.addGroup(pnBodyLayout.createSequentialGroup()
        			.addContainerGap(18, Short.MAX_VALUE)
        			.addGroup(pnBodyLayout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(pnDanhSachNhanVien, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(pnCongDoan, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGap(18)
        			.addGroup(pnBodyLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(tglSua, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        				.addComponent(tglThem, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnXoa, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
        			.addGap(12)
        			.addComponent(scrCongDoan, GroupLayout.PREFERRED_SIZE, 198, GroupLayout.PREFERRED_SIZE))
        );
        pnBody.setLayout(pnBodyLayout);

        add(pnBody, java.awt.BorderLayout.CENTER);

        pnHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnHeader.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnHeader.setPreferredSize(new java.awt.Dimension(1250, 130));

        pnTieuDe.setBackground(new java.awt.Color(255, 153, 0));

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTieuDe.setText("Tạo Công Đoạn Sản Phẩm");
        lblTieuDe.setToolTipText("");
        lblTieuDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnTieuDeLayout = new javax.swing.GroupLayout(pnTieuDe);
        pnTieuDe.setLayout(pnTieuDeLayout);
        pnTieuDeLayout.setHorizontalGroup(
            pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTieuDeLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(lblTieuDe)
                .addGap(151, 151, 151))
        );
        pnTieuDeLayout.setVerticalGroup(
            pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTieuDe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );
        
        btnHDSD = new JButton("?");
        btnHDSD.setFont(new Font("Tahoma", Font.BOLD, 10));
        
        lblHDSD = new JLabel("Hướng dẫn sử dụng");

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeaderLayout.setHorizontalGroup(
        	pnHeaderLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnHeaderLayout.createSequentialGroup()
        			.addGroup(pnHeaderLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(pnHeaderLayout.createSequentialGroup()
        					.addGap(354)
        					.addComponent(pnTieuDe, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
        				.addGroup(pnHeaderLayout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblHDSD, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)))
        			.addComponent(btnHDSD)
        			.addContainerGap())
        );
        pnHeaderLayout.setVerticalGroup(
        	pnHeaderLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnHeaderLayout.createSequentialGroup()
        			.addGap(22)
        			.addComponent(pnTieuDe, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(27, Short.MAX_VALUE))
        		.addGroup(pnHeaderLayout.createSequentialGroup()
        			.addContainerGap(97, Short.MAX_VALUE)
        			.addGroup(pnHeaderLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnHDSD)
        				.addComponent(lblHDSD))
        			.addContainerGap())
        );
        pnHeader.setLayout(pnHeaderLayout);

        add(pnHeader, java.awt.BorderLayout.NORTH);
        tblCongDoan.setRowHeight(30);
    }// </editor-fold>//GEN-END:initComponents



    protected void cmbLoaiCongDoanActionPerformed(ActionEvent e) {
		layMaCongDoanTiepTheo();
	}

	protected void layCongDoanTheoSanPhamDuocChon(String maSanPham) {
		ArrayList<CongDoan> dsCongDoan = CongDoan_Dao.layDanhSachCongDoanKhiCoMaSanPham(maSanPham);
		modalCongDoan.setRowCount(0);
		int i =0;
		for (CongDoan congDoan : dsCongDoan) {
			modalCongDoan.addRow(new String[] {++i + "", congDoan.getMaCongDoan(), congDoan.getLoaiCongDoan().toString(), congDoan.getSanPham().getMaSanPham(), congDoan.getLuongTren1Sp()+"", congDoan.getSoCongNhan()+"",congDoan.getSoLuongThanhPhan()+"", congDoan.getNgayChiaCongDoan().toString()});
		}
		kiemTraSoLuong();
		layLoaiCongDoanConLai();
	}

	private void tglThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglThemActionPerformed
        // TODO add your handling code here:
        if (tglThem.isSelected()) {
        	if(tblDSSP.getSelectedRow()!=-1) {
        		moFormNhapDuLieu();
                layLoaiCongDoanConLai();
                layMaCongDoanTiepTheo();
                txtSanPham.setText((String) tblDSSP.getValueAt(tblDSSP.getSelectedRow(), 2));
        	}
            tglThem.setSelected(false);
        } else {
            dongFormNhapDuLieu();
        }

    }//GEN-LAST:event_tglThemActionPerformed

    private void layMaCongDoanTiepTheo() {
    	LoaiCongDoan congDoanHienTai = (LoaiCongDoan) cmbLoaiCongDoan.getSelectedItem();
    	if(congDoanHienTai == null) return;
    	if(congDoanHienTai.toString().equalsIgnoreCase("Bề Mặt")) {
    		String maCongDoan = "CD0003"+ (String)tblDSSP.getValueAt(tblDSSP.getSelectedRow(), 1);
    		txtMa.setText(maCongDoan);
    	}else if(congDoanHienTai.toString().equalsIgnoreCase("Cắt Gỗ")) {
    		String maCongDoan = "CD0001"+ (String)tblDSSP.getValueAt(tblDSSP.getSelectedRow(), 1);
    		txtMa.setText(maCongDoan);
    	}else if(congDoanHienTai.toString().equalsIgnoreCase("Chế Tác")) {
    		String maCongDoan = "CD0002"+ (String)tblDSSP.getValueAt(tblDSSP.getSelectedRow(), 1);
    		txtMa.setText(maCongDoan);
    	}else {
    		String maCongDoan = "CD0004"+ (String)tblDSSP.getValueAt(tblDSSP.getSelectedRow(), 1);
    		txtMa.setText(maCongDoan);
    	}
	}

	private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int lc = JOptionPane.showConfirmDialog(null, "Bạn Có Chắn Muốn Thoát Tác Vụ Này Không", "Chú Ý?", JOptionPane.YES_NO_OPTION);
        if(lc == JOptionPane.YES_OPTION){
        	xoaTrangForm();
        	txtMa.setText("");
        	if(tglSua.isSelected()) {
        		datDuLieuCongDoanDuocChonVaoForm();
        	}
        	dongFormNhapDuLieu();
        	kiemTraSoLuong();
        	txtSanPham.setText((String)tblDSSP.getValueAt(tblDSSP.getSelectedRow(), 2));
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void tglSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglSuaActionPerformed
        int dongDuocChon = tblCongDoan.getSelectedRow();
        if(dongDuocChon>=0){
            if (tglSua.isSelected()) {
            	moFormNhapDuLieu();
	        } else {
	            dongFormNhapDuLieu();
	        }
        }else{
            JOptionPane.showMessageDialog(null, "Chọn Công Đoạn Cần Sửa");
            tglSua.setSelected(false);
        }
    }//GEN-LAST:event_tglSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        tblCongDoan.clearSelection();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        if(tglThem.isSelected()){
            xoaTrangForm();
        }else{
            xoaTrangForm();
            datDuLieuCongDoanDuocChonVaoForm();
        }
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        CongDoan congDoan = taoCongDoan();
        if(kiemTraDuLieu()){
            if(tglThem.isSelected()){
                if(CongDoan_Dao.themCongDoan(congDoan)){
                    JOptionPane.showMessageDialog(null, "Tạo Công Đoạn Thành Công");
                    
                    dienMaSanPham();
                    layCongDoanTheoSanPhamDuocChon(congDoan.getSanPham().getMaSanPham());

                    dongFormNhapDuLieu();
                    kiemTraSoLuong();
                    xoaTrangForm();
                    txtMa.setText("");
                    txtSanPham.setText((String) tblDSSP.getValueAt(tblDSSP.getSelectedRow(), 2));
                }else{             
                    JOptionPane.showMessageDialog(null, "Tạo Công Đoạn Thất Bại");
                }
            }else{
                if(CongDoan_Dao.suaCongDoan(congDoan)){
                    JOptionPane.showMessageDialog(null, "Sửa Công Đoạn Thành Công");
                    layCongDoanTheoSanPhamDuocChon(congDoan.getSanPham().getMaSanPham());                 
                    dongFormNhapDuLieu();
                    kiemTraSoLuong();
                    txtMa.setText("");
                    txtNhapTenSP.setText((String) tblDSSP.getValueAt(tblDSSP.getSelectedRow(), 2));
                    tblCongDoan.clearSelection();
                }else{             
                    JOptionPane.showMessageDialog(null, "Sửa Công Đoạn Thất Bại");
                }
            }
        }    
    }//GEN-LAST:event_btnXacNhanActionPerformed


    private void dienMaSanPham() {
		txtSanPham.setText((String) tblDSSP.getValueAt(tblDSSP.getSelectedRow(), 1));
	}


	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoa;
    private javax.swing.JCheckBox chkChuyenMon;
    private javax.swing.JCheckBox chkDiaChi;
    private javax.swing.JCheckBox chkKhoiLuong;
    private javax.swing.JCheckBox chkKichThuoc;
    private javax.swing.JCheckBox chkLoaiGo;
    private javax.swing.JCheckBox chkMa;
    private javax.swing.JCheckBox chkSoCongDoan;
    private javax.swing.JCheckBox chkSoLuong;
    private javax.swing.JCheckBox chkTen;
    private javax.swing.JComboBox<LoaiCongDoan> cmbLoaiCongDoan;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblLoaiCongDoan;
    private javax.swing.JLabel lblMaCongDoan;
    private javax.swing.JLabel lblSoCongNhan;
    private javax.swing.JLabel lblSoSanPham;
    private javax.swing.JLabel lblTenSanPham;
    private javax.swing.JLabel lblThuocSanPham;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnBody;
    private javax.swing.JPanel pnCongDoan;
    private javax.swing.JPanel pnDanhSachNhanVien;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnTieuChi;
    private javax.swing.JPanel pnTieuDe;
    private javax.swing.JScrollPane scrCongDoan;
    private javax.swing.JScrollPane scrDSSP;
    private javax.swing.JTable tblCongDoan;
    private javax.swing.JTable tblDSSP;
    private javax.swing.JToggleButton tglSua;
    private javax.swing.JToggleButton tglThem;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNhapTenSP;
    private javax.swing.JTextField txtSanPham;
    private javax.swing.JTextField txtSoCongNhan;
    private javax.swing.JTextField txtSoSanPham;
    private DAO_SanPham qlSanPham;
    private JButton btnHDSD;
    private JLabel lblHDSD;
    // End of variables declaration//GEN-END:variables

    private void moFormNhapDuLieu() {
    	tblDSSP.setEnabled(false);
        tglThem.setEnabled(false);
        tglSua.setEnabled(false);
        txtMa.setEnabled(true);
        txtGia.setEnabled(true);
        txtSanPham.setEnabled(true);
        cmbLoaiCongDoan.setEnabled(true);
        txtSoCongNhan.setEnabled(true);
        txtSoSanPham.setEnabled(true);
        btnXacNhan.setEnabled(true);
        btnLamMoi.setEnabled(true);
        btnThoat.setEnabled(true);
    }
    
    private void dongFormNhapDuLieu() {
    	tblDSSP.setEnabled(true);
        tglThem.setEnabled(true);
        tglThem.setSelected(false);
        tglSua.setSelected(false);
        tglSua.setEnabled(true);
        txtMa.setEnabled(false);
        txtGia.setEnabled(false);
        txtSanPham.setEnabled(false);
        cmbLoaiCongDoan.setEnabled(false);
        txtSoCongNhan.setEnabled(false);
        txtSoSanPham.setEnabled(false);
        btnXacNhan.setEnabled(false);
        btnLamMoi.setEnabled(false);
        btnThoat.setEnabled(false);
    }

    private void xoaTrangForm() {
        txtGia.setText("");
        txtSanPham.setText("");
//        cmbLoaiCongDoan.setSelectedIndex(0);
        txtSoCongNhan.setText("");
        txtSoSanPham.setText("");
    }

    private void datDuLieuCongDoanDuocChonVaoForm() {
        int dongDuocChonTrenBangCongDoan = tblCongDoan.getSelectedRow();
//        System.out.println(dongDuochon);
        String maCongDoan = (String)tblCongDoan.getValueAt(dongDuocChonTrenBangCongDoan, 1);
        CongDoan congDoan = CongDoan_Dao.timCongDoanKhiCoMa(maCongDoan);
        txtMa.setText(congDoan.getMaCongDoan());
        txtGia.setText(congDoan.getLuongTren1Sp()+"");
        cmbLoaiCongDoan.removeAllItems();
        cmbLoaiCongDoan.addItem(congDoan.getLoaiCongDoan());
        txtSoCongNhan.setText(congDoan.getSoCongNhan()+"");	
        txtSoSanPham.setText(congDoan.getSoLuongThanhPhan()+"");
        txtSanPham.setText(congDoan.getSanPham().getTenSP());
    }

	private CongDoan taoCongDoan() {
        String maCongDoan = txtMa.getText().trim();
        double giaThanh = Double.parseDouble(txtGia.getText());
        String maSanPham = (String)tblDSSP.getValueAt(tblDSSP.getSelectedRow(), 1);
        LoaiCongDoan loaiCongDoan = (LoaiCongDoan)cmbLoaiCongDoan.getSelectedItem();
        int soCongNhan = Integer.parseInt(txtSoCongNhan.getText());
        int soLuongThanhPhan = Integer.parseInt(txtSoSanPham.getText());
        int trangThai = 0;      
        CongDoan congDoan = new CongDoan(maCongDoan, giaThanh, soCongNhan, soLuongThanhPhan, new SanPham(maSanPham), loaiCongDoan, LocalDate.now(), trangThai);
        return congDoan;
    }

    private boolean kiemTraDuLieu() {
    	String giaThanh = txtGia.getText().trim();
    	if(giaThanh == null || giaThanh.isEmpty()) {
    		baoLoi("Giá Thành Không Được Để Trống", txtGia);
    		return false;
    	}else if(!giaThanh.matches("[0-9.]+") || Double.parseDouble(giaThanh)<=0) {
    		baoLoi("Giá thành là số và lớn hơn 0", txtGia);
    		return false;
    	}
    	
    	String soCongNhan = txtSoCongNhan.getText().trim();
    	if(soCongNhan == null || soCongNhan.isEmpty()) {
    		baoLoi("Số Công Nhân Không Được Để Trống", txtSoCongNhan);
    		return false;
    	}else if(!soCongNhan.matches("[0-9]+") || Integer.parseInt(soCongNhan)<=0) {
    		baoLoi("Số Công Nhân là số và lớn hơn 0", txtSoCongNhan);
    		return false;
    	}
    	
    	String soSanPham = txtSoSanPham.getText().trim();
    	if(soSanPham == null || soSanPham.isEmpty()) {
    		baoLoi("Số Sản Phẩm Không Được Để Trống", txtSoSanPham);
    		return false;
    	}else if(!soSanPham.matches("[0-9]+") || Integer.parseInt(soSanPham)<=0) {
    		baoLoi("Số Sản Phẩm là số và lớn hơn 0", txtSoSanPham);
    		return false;
    	}
        return true;
    }
    
    private void baoLoi(String loi, JComponent cpn){
        JOptionPane.showMessageDialog(null, loi);
        cpn.requestFocus();
    }
    
    private void layDanhSachSanPham() {
    	ArrayList<SanPham> ds = qlSanPham.layDanhSachSanPham();
    	modalSanPham.setRowCount(0);
    	int i=0;
    	for (SanPham sanPham : ds) {
			modalSanPham.addRow(new String[] {++i + "", sanPham.getMaSanPham(), sanPham.getTenSP()});
		}
    }
    
    private void kiemTraSoLuong() {
    	int soCongDoan = tblCongDoan.getRowCount();
    	if(soCongDoan ==4) {
    		tglThem.setEnabled(false);
    	}else {
    		tglThem.setEnabled(true);
    	}
    }
    
    
    private void layLoaiCongDoanConLai() {
    	int soDong = tblCongDoan.getRowCount();
    	for(int i=0; i< soDong;i++) {
    		String loaiCongDoan = (String) tblCongDoan.getValueAt(i, 2);
    		if(loaiCongDoan.trim().equalsIgnoreCase("Bề Mặt"))
    			cmbLoaiCongDoan.removeItem(LoaiCongDoan.BEMAT);
    		else if(loaiCongDoan.trim().equalsIgnoreCase("Lắp Ráp")) {
    			cmbLoaiCongDoan.removeItem(LoaiCongDoan.LAPRAP);
    		}else if(loaiCongDoan.trim().equalsIgnoreCase("Chế Tác")) {
    			cmbLoaiCongDoan.removeItem(LoaiCongDoan.CHETAC);
    		}else if(loaiCongDoan.trim().equalsIgnoreCase("Cắt Gỗ")){
    			cmbLoaiCongDoan.removeItem(LoaiCongDoan.CATGO);
    		}
    	}
    }
    
    private void duLieuLoaiCongDoan() {
    	cmbLoaiCongDoan.removeAllItems();
    	cmbLoaiCongDoan.addItem(LoaiCongDoan.CATGO);
    	cmbLoaiCongDoan.addItem(LoaiCongDoan.CHETAC);
    	cmbLoaiCongDoan.addItem(LoaiCongDoan.LAPRAP);
    	cmbLoaiCongDoan.addItem(LoaiCongDoan.BEMAT);
    }
    
}
