/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Frame;

import Enum.*;
import entity.ChucVu;
import entity.NhanVien;
import entity.PhongBan;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;

import javax.swing.AbstractButton;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;
import javax.swing.event.ListDataListener;
import javax.swing.table.DefaultTableModel;

import com.toedter.calendar.JDateChooser;

import DAO.ChucVu_Dao;
import DAO.DiaChi_Dao;
import DAO.NhanVien_Dao;
import DAO.PhongBan_Dao;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.JLabel;

/**
 *
 * @author ACER
 */
public class frm_NhanVien_TimKiem extends javax.swing.JPanel {

    /**
     * Creates new form frm_NhanVien_CapNhat_
     */
    public frm_NhanVien_TimKiem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	GioiTinh gt[] = {GioiTinh.NAM, GioiTinh.NU, GioiTinh.KHAC};
        pnBody = new javax.swing.JPanel();
        scrCongNhan = new javax.swing.JScrollPane();
        tblCongNhan = new javax.swing.JTable();
        pnDienThongTin = new javax.swing.JPanel();
        pnDiaChi = new javax.swing.JPanel();
        lblThanhPho_Tinh = new javax.swing.JLabel();
        cmbThanhPho = new javax.swing.JComboBox<String>(qlDiaChi.layDanhSachTinhThanhPho()) ;       
        lblHuyenXa = new javax.swing.JLabel();
        cmbQuanHuyen = new javax.swing.JComboBox<>();
        lblXa = new javax.swing.JLabel();
        cmbXa = new javax.swing.JComboBox<>();
        pnMa = new javax.swing.JPanel();
        lblMa = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        cmbChucVu = new javax.swing.JComboBox<>();
        lblChucVu = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        cmbGioiTinh = new javax.swing.JComboBox<GioiTinh>(gt) ;
        pnHoTen = new javax.swing.JPanel();
        lblHo = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        lblTen = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        pnCCCDSDT = new javax.swing.JPanel();
        txtCanCuoc = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        lblCCCD = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        pnChonNgay = new javax.swing.JPanel();
        lblNgaySinh = new javax.swing.JLabel();
        dcsNgaySinh = new com.toedter.calendar.JDateChooser();
        lblNgayVaoLam = new javax.swing.JLabel();
        dcsNgayVaoLam = new com.toedter.calendar.JDateChooser();
        pnEmailBaoHiem = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblBaoHiem = new javax.swing.JLabel();
        chkBHYT = new javax.swing.JCheckBox();
        chkBHXH = new javax.swing.JCheckBox();
        pnBan_ThamNien_HeSo = new javax.swing.JPanel();
        lblPhongBan = new javax.swing.JLabel();
        cmbPhongBan = new javax.swing.JComboBox<>();
        lblThamNien = new javax.swing.JLabel();
        cmbThamNien = new javax.swing.JComboBox<>();
        lblHeSoLuong = new javax.swing.JLabel();
        cmbHeSo = new javax.swing.JComboBox<>();
        pnGiioiTinh = new javax.swing.JPanel();
        chkMa = new javax.swing.JCheckBox();
        chkHo = new javax.swing.JCheckBox();
        chkSoDienThoai = new javax.swing.JCheckBox();
        chkCCCD = new javax.swing.JCheckBox();
        chkPhongBan = new javax.swing.JCheckBox();
        chkDiaChi = new javax.swing.JCheckBox();
        chkGioiTinh = new javax.swing.JCheckBox();
        chkNgaySInh = new javax.swing.JCheckBox();
        chckNgayVaoLam = new javax.swing.JCheckBox();
        chkChucVu = new javax.swing.JCheckBox();
        chkHeSoLuong = new javax.swing.JCheckBox();
        chkThamNien = new javax.swing.JCheckBox();
        chkEmail = new javax.swing.JCheckBox();
        chkBH = new javax.swing.JCheckBox();
        btnTimKiem = new javax.swing.JButton();
        pnHeader = new javax.swing.JPanel();
        pnTieuDe = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(1250, 800));
        setMinimumSize(new java.awt.Dimension(1196, 680));
        setPreferredSize(new java.awt.Dimension(1250, 680));
        setLayout(new java.awt.BorderLayout());
        
        //DiaChi
        capNhatDuLIeuQuanHuyen();
        capNhatDuLieuThiXa();
        //

        pnBody.setBackground(new java.awt.Color(255, 255, 255));

        tblCongNhan.setPreferredSize(new java.awt.Dimension(200, 160));
        scrCongNhan.setViewportView(tblCongNhan);
        scrCongNhan.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS );
//        scrCongNhan.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnDienThongTin.setBackground(new java.awt.Color(255, 255, 255));
        pnDienThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Điền Thông Tin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pnDienThongTin.setMaximumSize(new java.awt.Dimension(650, 250));
        pnDienThongTin.setMinimumSize(new java.awt.Dimension(200, 200));

        pnDiaChi.setBackground(new java.awt.Color(255, 255, 255));

        lblThanhPho_Tinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThanhPho_Tinh.setText("Tỉnh");
        lblThanhPho_Tinh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        
        cmbThanhPho.setEnabled(false);
        cmbThanhPho.setMaximumRowCount(64);
        cmbThanhPho.setToolTipText("");
        cmbThanhPho.setBorder(null);

        lblHuyenXa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuyenXa.setText("Quận");
        lblHuyenXa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        cmbQuanHuyen.setEnabled(false);
        cmbQuanHuyen.setMaximumRowCount(20);
        cmbQuanHuyen.setBorder(null);

        lblXa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXa.setText("Xã");
        lblXa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        
        cmbXa.setEnabled(false);

        javax.swing.GroupLayout pnDiaChiLayout = new javax.swing.GroupLayout(pnDiaChi);
        pnDiaChi.setLayout(pnDiaChiLayout);
        pnDiaChiLayout.setHorizontalGroup(
            pnDiaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDiaChiLayout.createSequentialGroup()
                .addComponent(lblThanhPho_Tinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, 110, 110)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHuyenXa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 120,120)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblXa, 20, 30, 31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbXa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, 120))
        );
        pnDiaChiLayout.setVerticalGroup(
            pnDiaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDiaChiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnDiaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblXa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbQuanHuyen, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHuyenXa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbThanhPho, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThanhPho_Tinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbXa, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        pnMa.setBackground(new java.awt.Color(255, 255, 255));

        lblMa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMa.setText("Mã Nhân Viên");
        lblMa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        
        txtMa.setEnabled(false);
        txtMa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));       
        
        cmbChucVu.setMaximumRowCount(64);
        cmbChucVu.setAutoscrolls(true);
        cmbChucVu.setBorder(null);
        cmbChucVu.setEnabled(false);
        cmbChucVu.setPreferredSize(new java.awt.Dimension(121, 29));

        lblChucVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChucVu.setText("Chức Vụ");
        lblChucVu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        lblGioiTinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGioiTinh.setText("Giới tính");
        lblGioiTinh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));


        javax.swing.GroupLayout pnMaLayout = new javax.swing.GroupLayout(pnMa);
        pnMa.setLayout(pnMaLayout);
        pnMaLayout.setHorizontalGroup(
            pnMaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMaLayout.createSequentialGroup()
                .addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cmbGioiTinh.setEnabled(false);
        pnMaLayout.setVerticalGroup(
            pnMaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbGioiTinh)
            .addGroup(pnMaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnMaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cmbChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnHoTen.setBackground(new java.awt.Color(255, 255, 255));

        lblHo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHo.setText("Họ");
        lblHo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        
        txtHo.setEnabled(false);
        txtHo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHo.setText("Nhập Họ");
        txtHo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtHo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoFocusLost(evt);
            }
        });

        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTen.setText("Tên");
        lblTen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        
        txtTen.setEnabled(false);
        txtTen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTen.setText("Nhập Tên");
        txtTen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnHoTenLayout = new javax.swing.GroupLayout(pnHoTen);
        pnHoTen.setLayout(pnHoTenLayout);
        pnHoTenLayout.setHorizontalGroup(
            pnHoTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHoTenLayout.createSequentialGroup()
                .addComponent(lblHo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnHoTenLayout.setVerticalGroup(
            pnHoTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHoTenLayout.createSequentialGroup()
                .addGroup(pnHoTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTen, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtHo)
                    .addComponent(lblHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnCCCDSDT.setBackground(new java.awt.Color(255, 255, 255));
        
        txtCanCuoc.setEnabled(false);
        txtCanCuoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCanCuoc.setText("Căn cước");
        txtCanCuoc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtCanCuoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCanCuocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCanCuocFocusLost(evt);
            }
        });

        lblSDT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSDT.setText("SDT");
        lblSDT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        lblCCCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCCCD.setText("CCCD");
        lblCCCD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        
        txtSDT.setEnabled(false);
        txtSDT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSDT.setText("Số điện thoại");
        txtSDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        txtSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSDTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSDTFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnCCCDSDTLayout = new javax.swing.GroupLayout(pnCCCDSDT);
        pnCCCDSDT.setLayout(pnCCCDSDTLayout);
        pnCCCDSDTLayout.setHorizontalGroup(
            pnCCCDSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCCCDSDTLayout.createSequentialGroup()
                .addComponent(lblCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCanCuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnCCCDSDTLayout.setVerticalGroup(
            pnCCCDSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCCCDSDTLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(pnCCCDSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtSDT)))
            .addComponent(lblCCCD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtCanCuoc, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pnChonNgay.setBackground(new java.awt.Color(255, 255, 255));

        lblNgaySinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgaySinh.setText("Ngày Sinh");
        lblNgaySinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        lblNgaySinh.setFocusable(false);
        lblNgaySinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblNgayVaoLam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgayVaoLam.setText("Ngày vào làm");
        lblNgayVaoLam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        javax.swing.GroupLayout pnChonNgayLayout = new javax.swing.GroupLayout(pnChonNgay);
        pnChonNgay.setLayout(pnChonNgayLayout);
        pnChonNgayLayout.setHorizontalGroup(
            pnChonNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChonNgayLayout.createSequentialGroup()
                .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcsNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcsNgayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnChonNgayLayout.setVerticalGroup(
            pnChonNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dcsNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
            .addComponent(lblNgayVaoLam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dcsNgayVaoLam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
        dcsNgaySinh.setEnabled(false);
        dcsNgayVaoLam.setEnabled(false);

        pnEmailBaoHiem.setBackground(new java.awt.Color(255, 255, 255));

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email");
        lblEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        
        txtEmail.setEnabled(false);
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setText("Nhập Email");
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        lblBaoHiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBaoHiem.setText("Bảo Hiểm");

        chkBHYT.setText("BHYT");
        chkBHXH.setEnabled(false);
        chkBHXH.setText("BHXH");
        chkBHYT.setEnabled(false);
        
        javax.swing.GroupLayout pnEmailBaoHiemLayout = new javax.swing.GroupLayout(pnEmailBaoHiem);
        pnEmailBaoHiem.setLayout(pnEmailBaoHiemLayout);
        pnEmailBaoHiemLayout.setHorizontalGroup(
            pnEmailBaoHiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEmailBaoHiemLayout.createSequentialGroup()
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBHYT, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBHXH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnEmailBaoHiemLayout.setVerticalGroup(
            pnEmailBaoHiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lblBaoHiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnEmailBaoHiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(chkBHYT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkBHXH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnBan_ThamNien_HeSo.setBackground(new java.awt.Color(255, 255, 255));

        lblPhongBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhongBan.setText("Phòng Ban");
        lblPhongBan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        
        cmbPhongBan.setEnabled(false);

        lblThamNien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThamNien.setText("Thâm Niên");
        lblThamNien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        cmbThamNien.setMaximumRowCount(64);
        cmbThamNien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "0.4", "0.8", "1", "1.4", "1.8", "2", " " }));
        cmbThamNien.setEnabled(false);
        cmbThamNien.setBorder(null);

        lblHeSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeSoLuong.setText("Hệ số");
        lblHeSoLuong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        
        cmbHeSo.setEnabled(false);
        cmbHeSo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.64", "6.5", " " }));
        
        
        
        javax.swing.GroupLayout pnBan_ThamNien_HeSoLayout = new javax.swing.GroupLayout(pnBan_ThamNien_HeSo);
        pnBan_ThamNien_HeSo.setLayout(pnBan_ThamNien_HeSoLayout);
        pnBan_ThamNien_HeSoLayout.setHorizontalGroup(
            pnBan_ThamNien_HeSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBan_ThamNien_HeSoLayout.createSequentialGroup()
                .addComponent(lblPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 86, 120)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, 60, 70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbHeSo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, 70)
                .addGap(2, 2, 2))
        );
        pnBan_ThamNien_HeSoLayout.setVerticalGroup(
            pnBan_ThamNien_HeSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBan_ThamNien_HeSoLayout.createSequentialGroup()
                .addGroup(pnBan_ThamNien_HeSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhongBan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbPhongBan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThamNien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbThamNien)
                    .addGroup(pnBan_ThamNien_HeSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbHeSo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout pnDienThongTinLayout = new javax.swing.GroupLayout(pnDienThongTin);
        pnDienThongTin.setLayout(pnDienThongTinLayout);
        pnDienThongTinLayout.setHorizontalGroup(
            pnDienThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDienThongTinLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(pnDienThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnCCCDSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnChonNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnEmailBaoHiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnBan_ThamNien_HeSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );
        pnDienThongTinLayout.setVerticalGroup(
            pnDienThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDienThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pnBan_ThamNien_HeSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnCCCDSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnChonNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnEmailBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnGiioiTinh.setBackground(new java.awt.Color(255, 255, 255));
        pnGiioiTinh.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Tiêu chí tìm kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        chkMa.setText("Mã Nhân Viên");
        chkMa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkMaStateChanged(evt);
            }
        });

        chkHo.setText("Họ Ten ");

        chkSoDienThoai.setText("Số điện thoại");

        chkCCCD.setText("CCCD");

        chkPhongBan.setText("Phòng Ban");

        chkDiaChi.setText("Địa chỉ");

        chkGioiTinh.setText("Giới Tính");

        chkNgaySInh.setText("Ngày sinh");

        chckNgayVaoLam.setText("Ngày vào làm");

        chkChucVu.setText("Chức vụ");

        chkHeSoLuong.setText("Hệ số lương");

        chkThamNien.setText("Thâm niên");

        chkEmail.setText("Email");

        chkBH.setText("Bảo Hiểm");

        javax.swing.GroupLayout chkGioiTinhLayout = new javax.swing.GroupLayout(pnGiioiTinh);
        pnGiioiTinh.setLayout(chkGioiTinhLayout);
        chkGioiTinhLayout.setHorizontalGroup(
            chkGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chkGioiTinhLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(chkGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkPhongBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkNgaySInh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chckNgayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(chkGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkHeSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(chkThamNien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkBH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        chkGioiTinhLayout.setVerticalGroup(
            chkGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chkGioiTinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chkGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMa)
                    .addComponent(chkChucVu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chkGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHo)
                    .addComponent(chkHeSoLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chkGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkGioiTinh)
                    .addComponent(chkThamNien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chkGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSoDienThoai)
                    .addComponent(chkEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chkGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCCCD)
                    .addComponent(chkBH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPhongBan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDiaChi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkNgaySInh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckNgayVaoLam)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        chkMa.setSelected(false);

        btnTimKiem.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Documents\\NetBeansProjects\\JavaApplication8\\img\\icons\\magnifying-glass.png")); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBodyLayout = new javax.swing.GroupLayout(pnBody);
        pnBody.setLayout(pnBodyLayout);
        pnBodyLayout.setHorizontalGroup(
            pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrCongNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 1248, Short.MAX_VALUE)
            .addGroup(pnBodyLayout.createSequentialGroup()
                .addGroup(pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBodyLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(pnDienThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(pnGiioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnBodyLayout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBodyLayout.setVerticalGroup(
            pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBodyLayout.createSequentialGroup()
                .addGroup(pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnGiioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDienThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnBody, java.awt.BorderLayout.CENTER);

        pnHeader.setBackground(new java.awt.Color(255, 255, 255));

        pnTieuDe.setBackground(new java.awt.Color(255, 153, 0));

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTieuDe.setText("Tìm Kiếm Nhân Viên");
        lblTieuDe.setToolTipText("");
        lblTieuDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnTieuDeLayout = new javax.swing.GroupLayout(pnTieuDe);
        pnTieuDe.setLayout(pnTieuDeLayout);
        pnTieuDeLayout.setHorizontalGroup(
            pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTieuDeLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        pnTieuDeLayout.setVerticalGroup(
            pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTieuDe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );
        
        btnHDSD = new JButton("?");
        btnHDSD.setFont(new Font("Tahoma", Font.BOLD, 10));
        
        lblHDSD = new JLabel("Hướng dẫn sử dụng");

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeaderLayout.setHorizontalGroup(
        	pnHeaderLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnHeaderLayout.createSequentialGroup()
        			.addGroup(pnHeaderLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(pnHeaderLayout.createSequentialGroup()
        					.addGap(354)
        					.addComponent(pnTieuDe, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 17, Short.MAX_VALUE))
        				.addGroup(pnHeaderLayout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblHDSD, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)))
        			.addComponent(btnHDSD)
        			.addContainerGap())
        );
        pnHeaderLayout.setVerticalGroup(
        	pnHeaderLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(pnHeaderLayout.createSequentialGroup()
        			.addGap(22)
        			.addComponent(pnTieuDe, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(27, Short.MAX_VALUE))
        		.addGroup(pnHeaderLayout.createSequentialGroup()
        			.addContainerGap(97, Short.MAX_VALUE)
        			.addGroup(pnHeaderLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnHDSD)
        				.addComponent(lblHDSD))
        			.addContainerGap())
        );
        pnHeader.setLayout(pnHeaderLayout);

        add(pnHeader, java.awt.BorderLayout.NORTH);
        //Lấy sự kiện vào cmb
        //PhongBan
        ComboBoxModel<PhongBan> modalPhongBan = new DefaultComboBoxModel<PhongBan>(danhSachPhongBan());
        cmbPhongBan.setModel(modalPhongBan);
        //ChucVu
        ComboBoxModel<ChucVu> modalChucVu = new DefaultComboBoxModel<ChucVu>(danhSachChucVu());
        cmbChucVu.setModel(modalChucVu);

        
        chkMa.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				checkBoxSuLySuKien(chkMa, e, txtMa, "");
			}
		});
   
        chkHo.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				checkBoxSuLySuKien(chkHo, e, txtHo, txtTen, "Nhập Họ", "Nhập Tên");
			}
		});
        
        chkGioiTinh.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				checkBoxSuLySuKien(chkGioiTinh, e, cmbGioiTinh, "");
			}
		});
        
        chkSoDienThoai.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				checkBoxSuLySuKien(chkSoDienThoai, e, txtSDT, "Số Điện Thoại");
			}
		});
        
        chkCCCD.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				checkBoxSuLySuKien(chkCCCD, e, txtCanCuoc, "Căn cước");
			}
		});
        
        chkPhongBan.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				checkBoxSuLySuKien(chkPhongBan, e, cmbPhongBan, "");
			}
		});
        
        chkDiaChi.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				checkBoxSuLySuKien(chkDiaChi, e, cmbThanhPho, cmbQuanHuyen, cmbXa);
			}
		});
        
        chkNgaySInh.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				checkBoxSuLySuKien(chkDiaChi, e, dcsNgaySinh, "");
			}
		});
        
        chckNgayVaoLam.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				checkBoxSuLySuKien(chckNgayVaoLam, e, dcsNgayVaoLam, "");
			}
		});
        
        chkChucVu.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				checkBoxSuLySuKien(chkChucVu, e, cmbChucVu, "");
			}
		});
        
        chkHeSoLuong.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				checkBoxSuLySuKien(chkChucVu, e, cmbHeSo, "");
			}
		});
        
        chkThamNien.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				checkBoxSuLySuKien(chkChucVu, e, cmbThamNien, "");
			}
		});
        
        chkEmail.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				checkBoxSuLySuKien(chkChucVu, e, txtEmail, "Nhập Email");
			}
		});
        
        chkBH.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				checkBoxSuLySuKien(chkChucVu, e, chkBHXH,chkBHYT, "", "");
			}
		});
        
        cmbThanhPho.addActionListener(new ActionListener() {
			
        	@Override
            public void actionPerformed(ActionEvent e) {
                capNhatDuLIeuQuanHuyen();
        	}
        });
        
        cmbQuanHuyen.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				capNhatDuLieuThiXa();
			}
		});
        
        tblCongNhan.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tblCongNhan.rowAtPoint(e.getPoint());
                if (e.getButton() == MouseEvent.BUTTON1 && row >= 0) {
                    String ma = (String) tblCongNhan.getValueAt(row, 1);
                    NhanVien nv = qlNhanVien.timNhanVienTheoMa(ma);
                    ThongTinNhanVienDialog nhanVienDialog = new ThongTinNhanVienDialog(new Frame() , true); 
                    nhanVienDialog.caiDuLieuVaoForm(nv.getAnh(), nv.getMaNhanSu(), nv.getHo()+" "+ nv.getTen(),
                    								nv.getChucVu().getTenChucVu(), nv.getBan().getTenPhongBan(),
                    								nv.getNgaySinh().toString(), nv.getNgayVaoLam().toString(),
                    								nv.getCCCD(), nv.getSoDienThoai(), nv.getChucVu().getHeSoLuong()+"",
                    								nv.getHeSoLuong()+"", nv.getDiaChi().toString(), nv.getEmail());
                    nhanVienDialog.setLocationRelativeTo(null);
                    nhanVienDialog.setVisible(true);
                }
            }
        });
        
        bangDuLieuNhanVien();
        
    }// </editor-fold>//GEN-END:initComponents

    

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
    	try {
    		String ma = "";
        	String ten = "";
        	String ho = "";
        	String cccd = "";
        	String sdt = "";
        	String thamNien ="0";
        	String heSo ="0";
        	ChucVu chucVu = null;
        	GioiTinh gioiTinh = null;
        	PhongBan ban = null;
        	String tinhThanh = "";
        	String quanHuyen = "";
        	String thiXa = "";
        	Date ngaySinh = null;
        	Date ngayVaoLam = null;
        	String email = "";
        	int lc=0;
        	if(chkBH.isSelected()) {
        		lc=1;
        	}
        	boolean thamGiaBaoHiemYTe = false;
        	boolean thamGiaBaoHiemXaHoi = false;
        	ma = (String) layDuLieuTimKiem(txtMa);
        	ho = (String) layDuLieuTimKiem(txtHo);
        	ten = (String) layDuLieuTimKiem(txtTen);
        	cccd = (String) layDuLieuTimKiem(txtCanCuoc);
        	sdt = (String) layDuLieuTimKiem(txtSDT);
        	chucVu = (ChucVu) layDuLieuTimKiem(cmbChucVu);
        	gioiTinh = (GioiTinh) layDuLieuTimKiem(cmbGioiTinh);
        	ban = (PhongBan) layDuLieuTimKiem(cmbPhongBan);
        	thamNien =  (String) layDuLieuTimKiem(cmbThamNien);
        	heSo =  (String) layDuLieuTimKiem(cmbHeSo);
        	tinhThanh = (String) layDuLieuTimKiem(cmbThanhPho);
        	quanHuyen = (String) layDuLieuTimKiem(cmbQuanHuyen);
        	thiXa =(String) layDuLieuTimKiem(cmbXa);
        	ngaySinh = (Date) layDuLieuTimKiem(dcsNgaySinh);
        	ngayVaoLam = (Date) layDuLieuTimKiem(dcsNgayVaoLam);
        	email = (String) layDuLieuTimKiem(txtEmail);
        	thamGiaBaoHiemYTe = (boolean) layDuLieuTimKiem(chkBHYT);
        	thamGiaBaoHiemXaHoi = (boolean) layDuLieuTimKiem(chkBHXH);
        	if(thamNien == null) {
        		thamNien = "0";
        	}
        	if(heSo == null) {
        		heSo = "0";
        	}
        	NhanVien mangNhanVien[] = new NhanVien_Dao().tieuChiTimKiemNhanVien(ma, ten, ho, cccd, sdt, Float.parseFloat(thamNien), Float.parseFloat(heSo), chucVu, gioiTinh, ban, tinhThanh, quanHuyen, thiXa, ngaySinh, ngayVaoLam, email, thamGiaBaoHiemYTe, thamGiaBaoHiemXaHoi, lc);
        	loadDuLieuNhanVienRaBang(modal, mangNhanVien);
        	lamMoiDuLieu();
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
    }//GEN-LAST:event_btnTimKiemActionPerformed
    
    
    //DAO
    private DiaChi_Dao qlDiaChi = new DiaChi_Dao();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DefaultTableModel modal;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JCheckBox chckNgayVaoLam;
    private javax.swing.JCheckBox chkBH;
    private javax.swing.JCheckBox chkBHXH;
    private javax.swing.JCheckBox chkBHYT;
    private javax.swing.JCheckBox chkCCCD;
    private javax.swing.JCheckBox chkChucVu;
    private javax.swing.JCheckBox chkDiaChi;
    private javax.swing.JCheckBox chkEmail;
    private javax.swing.JPanel pnGiioiTinh;
    private javax.swing.JCheckBox chkHeSoLuong;
    private javax.swing.JCheckBox chkHo;
    private javax.swing.JCheckBox chkMa;
    private javax.swing.JCheckBox chkNgaySInh;
    private javax.swing.JCheckBox chkPhongBan;
    private javax.swing.JCheckBox chkSoDienThoai;
    private javax.swing.JCheckBox chkThamNien;
    private javax.swing.JComboBox<ChucVu> cmbChucVu;
    private javax.swing.JComboBox<GioiTinh> cmbGioiTinh;
    private javax.swing.JComboBox<String> cmbHeSo;
    private javax.swing.JComboBox<PhongBan> cmbPhongBan;
    private javax.swing.JComboBox<String> cmbQuanHuyen;
    private javax.swing.JComboBox<String> cmbThamNien;
    private JComboBox<String> cmbThanhPho;
    private javax.swing.JComboBox<String> cmbXa;
    private com.toedter.calendar.JDateChooser dcsNgaySinh;
    private com.toedter.calendar.JDateChooser dcsNgayVaoLam;
    private javax.swing.JCheckBox chkGioiTinh;
    private javax.swing.JLabel lblBaoHiem;
    private javax.swing.JLabel lblCCCD;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHeSoLuong;
    private javax.swing.JLabel lblHo;
    private javax.swing.JLabel lblHuyenXa;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblPhongBan;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblThamNien;
    private javax.swing.JLabel lblThanhPho_Tinh;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblXa;
    private javax.swing.JPanel pnBan_ThamNien_HeSo;
    private javax.swing.JPanel pnBody;
    private javax.swing.JPanel pnCCCDSDT;
    private javax.swing.JPanel pnChonNgay;
    private javax.swing.JPanel pnDiaChi;
    private javax.swing.JPanel pnDienThongTin;
    private javax.swing.JPanel pnEmailBaoHiem;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnHoTen;
    private javax.swing.JPanel pnMa;
    private javax.swing.JPanel pnTieuDe;
    private javax.swing.JScrollPane scrCongNhan;
    private javax.swing.JTable tblCongNhan;
    private javax.swing.JTextField txtCanCuoc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private PhongBan_Dao qlPhongBan = new PhongBan_Dao();
    private ChucVu_Dao qlChucVu = new ChucVu_Dao();
    private NhanVien_Dao qlNhanVien = new NhanVien_Dao();
    private JButton btnHDSD;
    private JLabel lblHDSD;
    // End of variables declaration//GEN-END:variables
//    private  static void kiemTraDuocLuaChonHayKhong(Container container, ArrayList<Component> mangPhanTu) {
//        Component[] components = container.getComponents();
//        for (Component component : components) {
//            if ((component instanceof JTextField || component instanceof JComboBox || component instanceof JDateChooser) && component.isEnabled()) {
//            	mangPhanTu.add(component);
//            } else if (component instanceof Container) {
//                // Recursively check components inside this container
//                kiemTraDuocLuaChonHayKhong((Container) component, mangPhanTu);
//            }
//        }
//    }
    
    private void bangDuLieuNhanVien(){
        String column[]= {"STT", "Mã Nhân Viên", "Họ", "Tên", "CCCD", "SDT", "Giới Tính", "Phòng Ban", "Chức Vụ", "Địa Chỉ"};
        modal = new javax.swing.table.DefaultTableModel(column, 0) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        loadDuLieuNhanVienRaBang(modal, qlNhanVien.getDs().toArray(new NhanVien[0]));
        tblCongNhan.setModel(modal); 
    }
    
    private Object layDuLieuTimKiem(Component com) {
    	if(com.isEnabled()) {
    		if(com instanceof JTextField) {
    			return (String)((JTextField) com).getText().trim();
    		}else if(com instanceof JComboBox) {
    			return ((JComboBox<?>) com).getSelectedItem();
    		}else if(com instanceof JDateChooser) {
    			return ((JDateChooser) com).getDate();
    		}else if(com instanceof JCheckBox) {
    			return ((JCheckBox) com).isSelected();
    		}
    	}else {
    		if(com instanceof JCheckBox)
    			return false;
    		return null;
    	}
		return null;
    }
    
    private boolean kiemTraEnable(Component e) {
    	if(e.isEnabled()) {
    		return true;
    	}else {
    		return false;
    	}
    }

    
    private static void xuLySuKienTimKiem(Component component) {
		if(component instanceof JTextField) {
			
		}
	}

	private void checkBoxSuLySuKien(JCheckBox chk,ItemEvent e, JComponent txt, String moTa){
        if (e.getStateChange() == ItemEvent.SELECTED) {
                    txt.setEnabled(true);
        } else {
            if(txt instanceof JTextField) {
            	((JTextField) txt).setText(moTa);
                txt.setEnabled(false);
            }else if(txt instanceof JComboBox) {
            	txt.setEnabled(false);
            }else {
            	txt.setEnabled(false);
            }
        }
    }

    private void checkBoxSuLySuKien(JCheckBox chk,ItemEvent e, JComponent txt1, JComponent txt2, String moTa1, String moTa2){
        if (e.getStateChange() == ItemEvent.SELECTED) {
                    txt1.setEnabled(true);
                    txt2.setEnabled(true);
        } else if(txt1 instanceof JTextField && txt2 instanceof JTextField) {
            ((JTextField)txt1).setText(moTa1);
            ((JTextField)txt2).setText(moTa2);
            txt1.setEnabled(false);
            txt2.setEnabled(false);
        }else {
        	((JCheckBox) txt1).setSelected(false);
        	((JCheckBox) txt2).setSelected(false);
        	txt1.setEnabled(false);
            txt2.setEnabled(false);
        }
    }
    
    private void checkBoxSuLySuKien(JCheckBox chk,ItemEvent e, JComboBox<String> txt1, JComboBox<String> txt2, JComboBox<String> txt3){
        if (e.getStateChange() == ItemEvent.SELECTED) {
                    txt1.setEnabled(true);
                    txt2.setEnabled(true);
                    txt3.setEnabled(true);
        } else {
            txt1.setEnabled(false);
            txt2.setEnabled(false);
            txt3.setEnabled(false);
        }
    }
    
    private PhongBan[] danhSachPhongBan(){
        ArrayList<PhongBan> dsPhongBan = qlPhongBan.getDs();
        PhongBan[] mang = new PhongBan[dsPhongBan.size()];
        mang = dsPhongBan.toArray(mang);
        return mang;
    }
    
    private ChucVu[] danhSachChucVu(){
        ArrayList<ChucVu> dsChucVu = qlChucVu.getDs();
        ChucVu[] mang = new ChucVu[dsChucVu.size()];
        mang = dsChucVu.toArray(mang);
        return mang;
    }
    
    private void txtCanCuocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCanCuocFocusGained
        String duLieu = txtCanCuoc.getText().trim();
        if (duLieu.equalsIgnoreCase("Căn cước")) {
            txtCanCuoc.setText("");
            txtCanCuoc.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtCanCuocFocusGained

    private void txtCanCuocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCanCuocFocusLost
        if (txtCanCuoc.getText().isEmpty()) {
            txtCanCuoc.setText("Căn cước");
        }
    }//GEN-LAST:event_txtCanCuocFocusLost

    private void txtSDTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusGained
        String duLieu = txtSDT.getText().trim();
        if (duLieu.equalsIgnoreCase("Số điện thoại")) {
            txtSDT.setText("");
            txtSDT.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtSDTFocusGained

    private void txtSDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusLost
        if (txtSDT.getText().isEmpty()) {
            txtSDT.setText("Số điện thoại");
        }
    }//GEN-LAST:event_txtSDTFocusLost

    private void txtHoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoFocusGained
        String duLieu = txtHo.getText().trim();
        if (duLieu.equalsIgnoreCase("Nhập Họ")) {
            txtHo.setText("");
            txtHo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtHoFocusGained

    private void txtHoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoFocusLost
        if (txtHo.getText().isEmpty()) {
            txtHo.setText("Nhập Họ");
        }
    }//GEN-LAST:event_txtHoFocusLost

    private void txtTenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenFocusGained
        String duLieu = txtTen.getText().trim();
        if (duLieu.equalsIgnoreCase("Nhập Tên")) {
            txtTen.setText("");
            txtTen.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtTenFocusGained

    private void txtTenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenFocusLost
        if (txtTen.getText().isEmpty()) {
            txtTen.setText("Nhập Tên");
        }
    }//GEN-LAST:event_txtTenFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        String duLieu = txtEmail.getText().trim();
        if (duLieu.equalsIgnoreCase("Nhập Email")) {
            txtEmail.setText("");
            txtEmail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (txtEmail.getText().isEmpty()) {
            txtEmail.setText("Nhập Email");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void chkMaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkMaStateChanged
    	
    }//GEN-LAST:event_chkMaStateChanged
    
    protected void capNhatDuLIeuQuanHuyen() {
		String TinhThanhPhpDaChon = (String) cmbThanhPho.getSelectedItem();
		String quanHuyen[] = qlDiaChi.layQuanHuyenDuaTheoTinhThanhPho(TinhThanhPhpDaChon.trim());
		cmbQuanHuyen.removeAllItems();
		for(int i=0;i<quanHuyen.length;i++)
			cmbQuanHuyen.addItem(quanHuyen[i]);
	}
    
    protected void capNhatDuLieuThiXa() {
		try {
			String TinhThanhPhpDaChon = (String) cmbThanhPho.getSelectedItem();
			String quanHuyenDaChon = (String) cmbQuanHuyen.getSelectedItem();
			String thiXa[] = qlDiaChi.layPhuongXaDuaTrenQuanHuyenVaTinhThanhPho(TinhThanhPhpDaChon.trim(), quanHuyenDaChon.trim());
			cmbXa.removeAllItems();
			for(int i=0;i<thiXa.length;i++)
				cmbXa.addItem(thiXa[i]);
		} catch (Exception e) {
			// TODO: handle exception
		}
	}
    
    private void loadDuLieuNhanVienRaBang(DefaultTableModel modal, NhanVien[] mangNhanVien) {
    	int i=1;
    	tblCongNhan.removeAll();
    	modal.setRowCount(0);
        for (NhanVien nv : mangNhanVien) {
        	System.out.println(nv);
        	Vector<String> data = new  Vector<>();
        	data.add(i+"");
        	i++;
        	data.addAll(nv.duLieuFormCapNhat());
        	modal.addRow(data);
            }
	}
    
    private void lamMoiDuLieu() {
    	txtMa.setText("");
    	txtHo.setText("Nhập Họ");
    	txtTen.setText("Nhập Tên");
    	txtCanCuoc.setText("Căn cước");
    	txtSDT.setText("Số điện thoại");
    	txtEmail.setText("Nhập Email");
    	chkBHXH.setSelected(false);
    	chkBHYT.setSelected(false);
    	dcsNgaySinh.setDate(null);
    	dcsNgayVaoLam.setDate(null);
    	cmbChucVu.setSelectedIndex(0);
    	cmbGioiTinh.setSelectedIndex(0);
    	cmbThanhPho.setSelectedIndex(0);
    	cmbQuanHuyen.setSelectedIndex(0);
    	cmbXa.setSelectedIndex(0);
    	cmbThamNien.setSelectedIndex(0);
    	cmbHeSo.setSelectedIndex(0);
    	cmbPhongBan.setSelectedIndex(0);
    }
}
