/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import DAO.ChucVu_Dao;
import DAO.DiaChi_Dao;
import java.io.File;
import java.io.Serializable;
import java.util.Vector;
import Enum.*;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import entity.ChucVu;
import DAO.NhanVien_Dao;
import DAO.PhongBan_Dao;
import Enum.GioiTinh;
import entity.DiaChi;
import entity.NhanVien;
import entity.PhongBan;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.event.ListDataListener;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import java.awt.Font;

/**
 *
 * @author ACER
 */
public class frm_NhanVien_CapNhat extends javax.swing.JPanel implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
        
	/**
     * Creates new form frm_NhanVien_CapNhat_
     */
    public frm_NhanVien_CapNhat() {
        initComponents();
        caiDuLieuDiaChi();
        bangDuLieuNhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCapNhatNhanVien = new javax.swing.JPanel();
        btnChonAnh = new javax.swing.JButton();
        txtNhapMaCanTim = new javax.swing.JTextField();
        cmbTim = new javax.swing.JLabel();
        scrBangThongTinNhanVien = new javax.swing.JScrollPane();
        tblBangNhanVien = new javax.swing.JTable();
        pnThongTinNhanVien = new javax.swing.JPanel();
        lblTen = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        lblGioiTinh = new javax.swing.JLabel();
        pnBaoHiem = new javax.swing.JPanel();
        chkBHYT = new javax.swing.JCheckBox();
        chkBHXH = new javax.swing.JCheckBox();
        lblThamNien = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        PhuCap phuCap[]= {PhuCap.MUC_1, PhuCap.MUC_2, PhuCap.MUC_3, PhuCap.MUC_4};
        cmbThuong = new javax.swing.JComboBox<PhuCap>(phuCap);
        txtMaNhanVien = new javax.swing.JTextField();
        lblThanhPho_Tinh = new javax.swing.JLabel();
        lblHXa = new javax.swing.JLabel();
        lblThuong = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        cmbThanhPho = new javax.swing.JComboBox<String>();
        cmbQuanHuyen = new javax.swing.JComboBox<String>();
        txtEMail = new javax.swing.JTextField();
        lblCCCD = new javax.swing.JLabel();
        lblMaNhanVien = new javax.swing.JLabel();
        lblHeSoLuong = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblHuyenXa = new javax.swing.JLabel();
        cmbChucVu = new javax.swing.JComboBox<ChucVu>(danhSachChucVu());
        txtCanCuoc = new javax.swing.JTextField();
        lblBaoHiem = new javax.swing.JLabel();
        lblPhongBan = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblHo = new javax.swing.JLabel();
        GioiTinh gt[]= {GioiTinh.NAM, GioiTinh.NU, GioiTinh.KHAC};
        cmbGioiTinh = new javax.swing.JComboBox<GioiTinh>(gt);
        lblNgaySinh = new javax.swing.JLabel();
        cmbPhongBan = new javax.swing.JComboBox<>(danhSachPhongBan());
        cmbXa = new javax.swing.JComboBox<String>();
        String heSo[] = {"1.84", 2.17+"", 2.5+"", 2.83+"", 3.16+"", 3.49+"", 3.82+"", "4.15","4.48", "4.81", "5.14", "5.47", "5.8", "6.13", "6.4"};
        cmbHeSoLuong = new javax.swing.JComboBox<String>(heSo) ;
        txtHo = new javax.swing.JTextField();
        lblNgayVaoLam = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        dcsNgaySinh = new com.toedter.calendar.JDateChooser();
        dcsNgayVaoLam = new com.toedter.calendar.JDateChooser();
        txtThamNien = new javax.swing.JTextField();
        tglThem = new javax.swing.JToggleButton();
        tblSua = new javax.swing.JToggleButton();
        btnXoa = new javax.swing.JButton();
        hinhNen = new form.HinhNen(anhGoc);

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(1250, 800));
        setMinimumSize(new java.awt.Dimension(1196, 680));
        setPreferredSize(new java.awt.Dimension(1250, 680));

        pnCapNhatNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        pnCapNhatNhanVien.setMaximumSize(new java.awt.Dimension(1196, 680));
        pnCapNhatNhanVien.setPreferredSize(new java.awt.Dimension(1196, 680));

        btnChonAnh.setText("Chọn");
        btnChonAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChonAnhMouseClicked(evt);
            }
        });


        txtNhapMaCanTim.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNhapMaCanTim.setText("Nhập mã");
        txtNhapMaCanTim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
            	txtNhapMaCanTimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
            	txtNhapMaCanTimFocusLost(evt);
            }
        });

        cmbTim.setText("Tìm kiếm");

        tblBangNhanVien.setPreferredSize(new java.awt.Dimension(200, 500));
        scrBangThongTinNhanVien.setViewportView(tblBangNhanVien);
        pnThongTinNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTinNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true), "Thông Tin Nhân Viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 102, 0))); // NOI18N

        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTen.setText("Tên");
        lblTen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtSoDienThoai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSoDienThoai.setText("SDT");
        txtSoDienThoai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtSoDienThoai.setEnabled(false);
        txtSoDienThoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSoDienThoaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSoDienThoaiFocusLost(evt);
            }
        });

        lblGioiTinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGioiTinh.setText("Giới tính");
        lblGioiTinh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        pnBaoHiem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        chkBHYT.setText("BHYT");
        chkBHYT.setToolTipText("");
        chkBHYT.setEnabled(false);


        chkBHXH.setText("BHXH");
        chkBHXH.setEnabled(false);


        javax.swing.GroupLayout pnBaoHiemLayout = new javax.swing.GroupLayout(pnBaoHiem);
        pnBaoHiem.setLayout(pnBaoHiemLayout);
        pnBaoHiemLayout.setHorizontalGroup(
            pnBaoHiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBaoHiemLayout.createSequentialGroup()
                .addComponent(chkBHYT, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBHXH, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBaoHiemLayout.setVerticalGroup(
            pnBaoHiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBaoHiemLayout.createSequentialGroup()
                .addGroup(pnBaoHiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBHYT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkBHXH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblThamNien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThamNien.setText("Thâm niên");
        lblThamNien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        txtTen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTen.setText("Nhập Tên");
        txtTen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtTen.setEnabled(false);
        txtTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenFocusLost(evt);
            }
        });


        cmbThuong.setEnabled(false);


        txtMaNhanVien.setEditable(false);
        txtMaNhanVien.setBackground(new java.awt.Color(255, 204, 51));
        txtMaNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMaNhanVien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMaNhanVien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));


        lblThanhPho_Tinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThanhPho_Tinh.setText("Thành Phố/Tỉnh");
        lblThanhPho_Tinh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        lblHXa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHXa.setText("Xã");
        lblHXa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        lblThuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThuong.setText("Phụ Cấp");
        lblThuong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        lblChucVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChucVu.setText("Chức vụ");
        lblChucVu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        lblChucVu.setPreferredSize(new java.awt.Dimension(40, 18));

        cmbThanhPho.setEditable(false);
        cmbThanhPho.setMaximumRowCount(64);

        cmbThanhPho.setToolTipText("Danh sách quận huyện và thành phố");
        cmbThanhPho.setBorder(null);
        cmbThanhPho.setEnabled(false);

        cmbQuanHuyen.setMaximumRowCount(100);       
        cmbQuanHuyen.setToolTipText("");
        cmbQuanHuyen.setBorder(null);
        cmbQuanHuyen.setEnabled(false);
        

        txtEMail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEMail.setText("EMail");
        txtEMail.setEnabled(false);
        txtEMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEMailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEMailFocusLost(evt);
            }
        });

        lblCCCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCCCD.setText("CCCD");
        lblCCCD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        lblMaNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaNhanVien.setText("Mã nhân viên");
        lblMaNhanVien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        lblHeSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeSoLuong.setText("Hệ số lương");
        lblHeSoLuong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        lblSDT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSDT.setText("SDT");
        lblSDT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        lblHuyenXa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuyenXa.setText("Huyện/Quận");
        lblHuyenXa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        cmbChucVu.setMaximumRowCount(64);
        cmbChucVu.setToolTipText("");
        cmbChucVu.setBorder(null);
        cmbChucVu.setEnabled(false);
        cmbChucVu.setMaximumSize(new java.awt.Dimension(72, 20));

        txtCanCuoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCanCuoc.setText("Căn cước");
        txtCanCuoc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtCanCuoc.setEnabled(false);
        txtCanCuoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCanCuocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCanCuocFocusLost(evt);
            }
        });


        lblBaoHiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBaoHiem.setText("Bảo Hiểm");
        lblBaoHiem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        lblPhongBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhongBan.setText("Phòng Ban");
        lblPhongBan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email");
        lblEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        lblHo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHo.setText("Họ");
        lblHo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        cmbGioiTinh.setEnabled(false);
        cmbGioiTinh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbGioiTinhFocusGained(evt);
            }
        });

        lblNgaySinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgaySinh.setText("Ngày Sinh");
        lblNgaySinh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        cmbPhongBan.setEnabled(false);
        cmbPhongBan.setPreferredSize(new java.awt.Dimension(100, 22));

        cmbXa.setEnabled(false);


        cmbHeSoLuong.setBorder(null);
        cmbHeSoLuong.setEnabled(false);

        txtHo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHo.setText("Nhập Họ");
        txtHo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtHo.setEnabled(false);
        txtHo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoFocusLost(evt);
            }
        });

        lblNgayVaoLam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgayVaoLam.setText("Ngày Vào Lam");
        lblNgayVaoLam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        lblNgayVaoLam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDiaChi.setText("       Địa Chỉ");
        lblDiaChi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        lblDiaChi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtDiaChi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiaChi.setText("Địa Chỉ");
        txtDiaChi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txtDiaChi.setEnabled(false);
        txtDiaChi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDiaChiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiaChiFocusLost(evt);
            }
        });
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Desktop\\PTUD\\PTUD_APP\\QLyLuongSP\\img\\icons\\refresh-arrow.png")); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.setEnabled(false);
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXacNhan.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Desktop\\PTUD\\PTUD_APP\\QLyLuongSP\\img\\icons\\check-mark.png")); // NOI18N
        btnXacNhan.setText("Xác Nhận");
        btnXacNhan.setEnabled(false);
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Desktop\\PTUD\\PTUD_APP\\QLyLuongSP\\img\\icons\\house.png")); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setEnabled(false);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        dcsNgaySinh.setEnabled(false);

        dcsNgayVaoLam.setEnabled(false);

        txtThamNien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtThamNien.setText("Thâm Niên");
        txtThamNien.setEnabled(false);
        txtThamNien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtThamNienFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtThamNienFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnThongTinNhanVienLayout = new javax.swing.GroupLayout(pnThongTinNhanVien);
        pnThongTinNhanVien.setLayout(pnThongTinNhanVienLayout);
        pnThongTinNhanVienLayout.setHorizontalGroup(
            pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEMail, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                        .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcsNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDiaChi))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHuyenXa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcsNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                                        .addComponent(lblBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pnBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                                        .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(lblThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))))
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                        .addComponent(lblHeSoLuong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbHeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtThamNien))
                .addContainerGap())
            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                            .addComponent(lblMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                            .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblNgaySinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblThanhPho_Tinh, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbThanhPho, 0, 160, Short.MAX_VALUE)
                                .addComponent(txtHo, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 394, Short.MAX_VALUE)
                    .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHXa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSoDienThoai)
                        .addComponent(txtCanCuoc)
                        .addComponent(cmbXa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        pnThongTinNhanVienLayout.setVerticalGroup(
            pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dcsNgayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(dcsNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHuyenXa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbHeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pnBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEMail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addComponent(txtMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                            .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCanCuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(23, 23, 23)
                            .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(25, 25, 25)
                    .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblThanhPho_Tinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbXa, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(lblHXa, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                    .addContainerGap(188, Short.MAX_VALUE)))
        );

        tglThem.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Desktop\\PTUD\\PTUD_APP\\QLyLuongSP\\img\\icons\\plus.png")); // NOI18N
        tglThem.setSelected(false);
        tglThem.setText("Thêm");
        tglThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglThemActionPerformed(evt);
            }
        });

        tblSua.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Desktop\\PTUD\\PTUD_APP\\QLyLuongSP\\img\\icons\\edit.png")); // NOI18N
        tblSua.setText("Sửa");

        btnXoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Desktop\\PTUD\\PTUD_APP\\QLyLuongSP\\img\\icons\\bin.png")); // NOI18N
        btnXoa.setText("Hủy chọn trên Bảng");
        btnXoa.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				btnXoaActionPerformed(e);
			}
		});
        

        javax.swing.GroupLayout hinhNenLayout = new javax.swing.GroupLayout(hinhNen);
        hinhNen.setLayout(hinhNenLayout);
        hinhNenLayout.setHorizontalGroup(
            hinhNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        hinhNenLayout.setVerticalGroup(
            hinhNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        
        lblHDSD = new JLabel("Hướng dẫn sử dụng");
        
        btnHDSD = new JButton("?");
        btnHDSD.setFont(new Font("Tahoma", Font.BOLD, 10));

        javax.swing.GroupLayout pnCapNhatNhanVienLayout = new javax.swing.GroupLayout(pnCapNhatNhanVien);
        pnCapNhatNhanVienLayout.setHorizontalGroup(
        	pnCapNhatNhanVienLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        			.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(scrBangThongTinNhanVien, GroupLayout.PREFERRED_SIZE, 1301, GroupLayout.PREFERRED_SIZE)
        				.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        					.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        							.addGap(40)
        							.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(hinhNen, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        									.addComponent(txtNhapMaCanTim, GroupLayout.PREFERRED_SIZE, 126, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(cmbTim, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE))))
        						.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        							.addGap(127)
        							.addComponent(btnChonAnh, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)))
        					.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(tglThem)
        							.addGap(54)
        							.addComponent(tblSua)
        							.addGap(49)
        							.addComponent(btnXoa)
        							.addGap(185))
        						.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        							.addGap(34)
        							.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.TRAILING)
        								.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        									.addComponent(lblHDSD, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.UNRELATED)
        									.addComponent(btnHDSD))
        								.addComponent(pnThongTinNhanVien, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCapNhatNhanVienLayout.setVerticalGroup(
        	pnCapNhatNhanVienLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnHDSD, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblHDSD))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(pnThongTinNhanVien, GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
        				.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        					.addGap(54)
        					.addComponent(hinhNen, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(btnChonAnh)
        					.addGap(0, 153, Short.MAX_VALUE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(txtNhapMaCanTim, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        					.addComponent(cmbTim, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
        				.addComponent(btnXoa, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        				.addComponent(tblSua, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        				.addComponent(tglThem, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(scrBangThongTinNhanVien, GroupLayout.PREFERRED_SIZE, 235, GroupLayout.PREFERRED_SIZE))
        );
        pnCapNhatNhanVien.setLayout(pnCapNhatNhanVienLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCapNhatNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 1307, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCapNhatNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );
        
        cmbThanhPho.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == ItemEvent.SELECTED) {
		            // Xử lý sự kiện khi mục được chọn
		            capNhatDuLieuQuanHuyen();
		        }
			}
		});

        
        cmbQuanHuyen.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				capNhatDuLieuThiXa();
			}
		});
        
        
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String maCanTim = txtNhapMaCanTim.getText().trim();
                if(maCanTim.isEmpty()) {
                	return;
                }else {
                	timNhanVienTheoMaNhapVao(maCanTim);
                }
            }
        });

        // Thêm DocumentListener để theo dõi sự kiện khi dữ liệu thay đổi trong JTextField
        txtNhapMaCanTim.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                timer.restart(); // Khởi động lại bộ đếm thời gian khi có ký tự được nhập
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                timer.restart(); // Khởi động lại bộ đếm thời gian khi có ký tự bị xóa
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                timer.restart(); // Khởi động lại bộ đếm thời gian khi dữ liệu thay đổi
            }
        });
        
        tblSua.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					hanhDongSua();
				} catch (Exception e1) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null, e1.getMessage());
				}
			}
		});
        
        tblBangNhanVien.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				int dongLuaChon = tblBangNhanVien.getSelectedRow();
				if(dongLuaChon == -1) {
					return;
				}else {
					datDuLieuNhanVienVaoForm(dongLuaChon);
				}
			}
		});
    }// </editor-fold>//GEN-END:initComponents




    protected void btnXoaActionPerformed(ActionEvent e) {
		tblBangNhanVien.clearSelection();
		thietLapLaiForm();
		txtMaNhanVien.setText("");
	}




	//
    private static final String anhGoc = "C:\\Users\\ACER\\Downloads\\user.png";
    private String anhNguoiDung = "";
    private DefaultTableModel modal;
    //DAO
    private ChucVu_Dao qlChucVu = new ChucVu_Dao();
    private DiaChi_Dao qlDiaChi = new DiaChi_Dao();
    private PhongBan_Dao qlPhongBan = new PhongBan_Dao();
    private NhanVien_Dao qlNhanVien = new NhanVien_Dao();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoa;
    private javax.swing.JCheckBox chkBHXH;
    private javax.swing.JCheckBox chkBHYT;
    private javax.swing.JComboBox<ChucVu> cmbChucVu;
    private javax.swing.JComboBox<GioiTinh> cmbGioiTinh;
    private javax.swing.JComboBox<String> cmbHeSoLuong;
    private javax.swing.JComboBox<PhongBan> cmbPhongBan;
    private javax.swing.JComboBox<String> cmbQuanHuyen;
    private javax.swing.JComboBox<String> cmbThanhPho;
    private javax.swing.JComboBox<PhuCap> cmbThuong;
    private javax.swing.JComboBox<String> cmbXa;
    private com.toedter.calendar.JDateChooser dcsNgaySinh;
    private com.toedter.calendar.JDateChooser dcsNgayVaoLam;
    private form.HinhNen hinhNen;
    private javax.swing.JLabel lblBaoHiem;
    private javax.swing.JLabel lblCCCD;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHXa;
    private javax.swing.JLabel lblHeSoLuong;
    private javax.swing.JLabel lblHo;
    private javax.swing.JLabel lblHuyenXa;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblPhongBan;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblThamNien;
    private javax.swing.JLabel lblThanhPho_Tinh;
    private javax.swing.JLabel lblThuong;
    private javax.swing.JLabel cmbTim;
    private javax.swing.JPanel pnBaoHiem;
    private javax.swing.JPanel pnCapNhatNhanVien;
    private javax.swing.JPanel pnThongTinNhanVien;
    private javax.swing.JScrollPane scrBangThongTinNhanVien;
    private javax.swing.JTable tblBangNhanVien;
    private javax.swing.JToggleButton tblSua;
    private javax.swing.JToggleButton tglThem;
    private javax.swing.JTextField txtCanCuoc;
    private javax.swing.JTextField txtDiaChi;
    private static javax.swing.JTextField txtEMail;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtNhapMaCanTim;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtThamNien;
    private JLabel lblHDSD;
    private JButton btnHDSD;
    // End of variables declaration//GEN-END:variables

    private void thietLapLaiForm() {
        cmbGioiTinh.setSelectedIndex(0);
        cmbPhongBan.setSelectedIndex(0);
        txtHo.setText("Nhập Họ");
        txtTen.setText("Nhập Tên");
        txtCanCuoc.setText("Căn cước");
        dcsNgaySinh.setDate(new Date());
        dcsNgayVaoLam.setDate(new Date());
        txtSoDienThoai.setText("SDT");
        txtDiaChi.setText("Địa Chỉ");
        cmbChucVu.setSelectedIndex(0);
        
        cmbThuong.setSelectedIndex(0);
        cmbHeSoLuong.setSelectedIndex(0);
        txtEMail.setText("EMail");
        chkBHXH.setSelected(false);
        chkBHYT.setSelected(false);
        txtThamNien.setText("Thâm Niên");
        hinhNen.setNewBackground(anhGoc);
    }

    private void chonAnh() {
        JFileChooser fchChonAnh = new JFileChooser();
        fchChonAnh.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File file) {
                if (file.isDirectory()) {
                    return true;
                }
                String fileName = file.getName().toLowerCase();
                return fileName.endsWith(".jpg") || fileName.endsWith(".png") || fileName.endsWith(".gif");
            }

            @Override
            public String getDescription() {
                return "Image Files (.jpg, .png, .gif)";
            }
        });
        int result = fchChonAnh.showOpenDialog(null);

        if(result == JFileChooser.APPROVE_OPTION){
            anhNguoiDung = fchChonAnh.getSelectedFile().getAbsolutePath();
            hinhNen.setNewBackground(anhNguoiDung);

        }else{
            return;
        }       
    }

    private void layMaNhanVien() {
        String maNhanVien = NhanVien_Dao.layMaNhanVienTiepTheo();
        txtMaNhanVien.setText(maNhanVien);
    }
    
    private void bangDuLieuNhanVien(){
        String column[]= {"STT", "Mã Nhân Viên", "Họ", "Tên", "CCCD", "SDT", "Giới Tính", "Phòng Ban", "Chức Vụ", "Địa Chỉ"};
        modal = new javax.swing.table.DefaultTableModel(column, 50) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        loadDuLieuNhanVienRaBang(modal);
        tblBangNhanVien.setModel(modal);      
    }

    private void kiemTraDuLieu() throws Exception {
        String ho = txtHo.getText().trim();
        if(ho.equalsIgnoreCase("Nhập Họ") || ho.isEmpty()){
        	throw new Exception("Họ không được rỗng");
        }else if(!ho.matches("^[\\p{L}\\p{Mn}\\p{Mc}\\s]+$")) {
        	throw new Exception("Họ không hợp lệ");
        }
        
        String ten = txtTen.getText();
        if(ten.equalsIgnoreCase("Nhập Tên") || ten.isEmpty() ){
            throw new Exception("Tên không được rỗng");
        }else if(!ten.matches("^[\\p{L}\\p{Mn}\\p{Mc}\\s]+$")) {
        	throw new Exception("Tên không hợp lệ");
        }
        
        String cccd = txtCanCuoc.getText().trim();
        if(cccd.isEmpty()){
            throw new Exception("Căn cước công dân không được rỗng");
        }else if(cccd.length()<11|| !cccd.matches("[0-9]{11}")) {
            throw new Exception("Căn cước công dân không hợp lệ");     	
        }
        
        //nam hien tai
        LocalDate currentDate = LocalDate.now();
        int namHienTai = currentDate.getYear();
        //nam ngay Sinh
        Date ngaySinh = dcsNgaySinh.getDate();
        if(ngaySinh == null) {
        	throw new Exception("Ngày sinh không được rỗng");
        }
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(ngaySinh);
        int namNgaySinh = calendar.get(Calendar.YEAR);
        if(namHienTai - namNgaySinh <18){
            throw new Exception("Tuỏi nhân viên phải từ 18 tới 60");
        }
        
        Date ngayVaoLam = dcsNgayVaoLam.getDate();
        if(ngayVaoLam == null) {
        	throw new Exception("Ngày vào làm không được rỗng");
        }
        
        String tinhThanhPho = (String) cmbThanhPho.getSelectedItem();
        if(tinhThanhPho== null) {
        	throw new Exception("Chưa chọn tỉnh thành phố");
        }
        
        String quanHuyen = (String) cmbQuanHuyen.getSelectedItem();
        if(quanHuyen.trim().isEmpty() || quanHuyen== null) {
        	throw new Exception("Chưa chọn quan Huyen");
        }
        
        String xa = (String) cmbXa.getSelectedItem();
        if(xa.trim().isEmpty() || xa== null) {
        	throw new Exception("Chưa chọn Thị Xã");
        }
        
        String soDienThoai = txtSoDienThoai.getText();
        if(soDienThoai.isEmpty()){
            throw new Exception("Số điện thoại không được rỗng");
        }else if(soDienThoai.length()<10) {
        	throw new Exception("Số điện thoại phải dài 11 kí tự");
        }else if(!soDienThoai.matches("[0-9]+")) {
        	throw new Exception("Số điện thoại không hợp lệ");
        }
        
        String diaChiCuThe = txtDiaChi.getText();
        if(diaChiCuThe.trim().isEmpty() ){
            throw new Exception("Dia chi không được rỗng");
        }else if(!diaChiCuThe.matches("^[\\p{L}\\p{Mn}\\p{Mc}\\s\\d]+$")) {
        	throw new Exception("Dia chi không hợp lệ");
        }
        
        String thamNien = txtThamNien.getText().trim();
        if(thamNien.equalsIgnoreCase("Thâm Niên")||thamNien.isEmpty() ) {
        	throw new Exception("Thâm niên không hợp lệ");
        }else if(!thamNien.matches("[0-9.]+")) {
        	throw new Exception("Thâm niên phải là số");
        }
        
        String email = txtEMail.getText().trim();
        if(email.equalsIgnoreCase("EMail") || email.isEmpty()) {
        	throw new Exception("Email không được rỗng");
        }else if(!email.matches("^[a-zA-Z0-9._%+-]+@(email|yahoo|outlook|gmail).[a-zA-Z]{2,}$")) {
        	throw new Exception("Email không hợp lệ");
        }
        
        if(anhNguoiDung == "") {
        	throw new Exception("Chưa chọn ảnh người dùng");
        }
    }


	protected void capNhatDuLieuThiXa() {
		String TinhThanhPhpDaChon = (String) cmbThanhPho.getSelectedItem();
		String quanHuyenDaChon = (String) cmbQuanHuyen.getSelectedItem();
		String thiXa[] = qlDiaChi.layPhuongXaDuaTrenQuanHuyenVaTinhThanhPho(TinhThanhPhpDaChon.trim(), quanHuyenDaChon.trim());
		cmbXa.removeAllItems();
		for(int i=0;i<thiXa.length;i++)
			cmbXa.addItem(thiXa[i]);
	}

	protected void capNhatDuLieuQuanHuyen() {
			String TinhThanhPhpDaChon = (String) cmbThanhPho.getSelectedItem();
			String quanHuyen[] = qlDiaChi.layQuanHuyenDuaTheoTinhThanhPho(TinhThanhPhpDaChon.trim());
			cmbQuanHuyen.removeAllItems();
			for(int i=0;i<quanHuyen.length;i++)
				cmbQuanHuyen.addItem(quanHuyen[i]);
		
	}
	
	protected boolean kiemTraTacVu() {
		if(tglThem.isSelected()) {
			if(tblSua.isSelected()) {
				return false;
			}
		}
		return true;
	}
	protected void hanhDongSua() throws Exception {
		int dongDuocChon = tblBangNhanVien.getSelectedRow();
		if(dongDuocChon==-1) {
			tblSua.setSelected(false);
			throw new Exception("Chưa chọn nhân viên cần sửa");
		}else {
			if(tblSua.isSelected()) {
				moFormNhapDuLieu();
				tglThem.setEnabled(false);
				btnXoa.setEnabled(false);
				datDuLieuNhanVienVaoForm(dongDuocChon);
				
			}else {
				int lc = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát khỏi chế độ sửa không?", "Chú ý", JOptionPane.YES_NO_OPTION);
				if(lc == JOptionPane.YES_OPTION) {
					tblSua.setSelected(false);
					dongFormNhapDuLieu();
					thietLapLaiForm();
					tglThem.setEnabled(true);
					btnXoa.setEnabled(true);
				}
			}
		}		
	}

	private void datDuLieuNhanVienVaoForm(int dongDuocChon) {
		NhanVien nv = layDuLieuNhanVienTheoMaTuCot(dongDuocChon);
		txtMaNhanVien.setText(nv.getMaNhanSu());
		txtHo.setText(nv.getHo());
		txtTen.setText(nv.getTen());
		//Phong ban
		PhongBan pb = nv.getBan();
		for(int i = 0; i<cmbPhongBan.getItemCount();i++) {
			System.out.println(cmbPhongBan.getItemAt(i));
			if(cmbPhongBan.getItemAt(i).getMaPhongBan().equalsIgnoreCase(pb.getMaPhongBan())) {
				cmbPhongBan.setSelectedIndex(i);
				break;
			}
		}
		//Gioi tính
		GioiTinh gt = nv.getGioiTinh();
		if(gt == GioiTinh.NAM) {
			cmbGioiTinh.setSelectedIndex(0);
		}else if(gt == GioiTinh.NU) {
			cmbGioiTinh.setSelectedIndex(1);
		}else
			cmbGioiTinh.setSelectedIndex(2);
			
		txtSoDienThoai.setText(nv.getSoDienThoai());
		txtCanCuoc.setText(nv.getCCCD());
		dcsNgaySinh.setDate(nv.getNgaySinh());
		dcsNgayVaoLam.setDate(nv.getNgayVaoLam());
		txtDiaChi.setText(nv.getDiaChi().getSoNha());
		//he so luong
		float heSoLuong = nv.getHeSoLuong();
		
		for(int i=0;i<cmbHeSoLuong.getItemCount();i++) {
			if(Float.parseFloat(cmbHeSoLuong.getItemAt(i))== heSoLuong) {
				cmbHeSoLuong.setSelectedIndex(i);
				break;
			}
		}
		
		System.out.println(nv.getDiaChi().getTenTinhThanh().trim());
		//Thành Phố tỉnh
		cmbThanhPho.setSelectedItem(nv.getDiaChi().getTenTinhThanh().trim());
		cmbThanhPho.setSelectedItem(nv.getDiaChi().getTenTinhThanh().trim());
		//
		
		txtEMail.setText(nv.getEmail());
		//bhyt
		if (nv.isBHXH()) {
		    chkBHXH.setSelected(true);
		} else {
		    chkBHXH.setSelected(false);
		}
		//bhxh
		if (nv.isBHYT()) {
		    chkBHYT.setSelected(true);
		} else {
		    chkBHYT.setSelected(false);
		}
		
		txtThamNien.setText(nv.getThamNiem()+"");
		hinhNen.setNewBackground(nv.getAnh());
		anhNguoiDung = nv.getAnh();
		
	}

	private NhanVien layDuLieuNhanVienTheoMaTuCot(int dongDuocChon) {
		String maNhanVien = (String) tblBangNhanVien.getValueAt(dongDuocChon, 1);
		return qlNhanVien.timNhanVienTheoMa(maNhanVien);
	}

	protected void timNhanVienTheoMaNhapVao(String maCanTim) {
		
	}

	protected void txtNhapMaCanTimFocusLost(FocusEvent evt) {
		if (txtNhapMaCanTim.getText().isEmpty()) {
			txtNhapMaCanTim.setText("Nhập mã");
        }
	}

	protected void txtNhapMaCanTimFocusGained(FocusEvent evt) {
		String duLieu = txtNhapMaCanTim.getText().trim();
        if (duLieu.equalsIgnoreCase("Nhập mã")) {
        	txtNhapMaCanTim.setText("");
        	txtNhapMaCanTim.setForeground(Color.BLACK);
        }
	}

	private void btnChonAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChonAnhMouseClicked
        // TODO add your handling code here:
        chonAnh();
    }//GEN-LAST:event_btnChonAnhMouseClicked

    private void tglThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglThemActionPerformed
        if (tglThem.isSelected()) {
        	if(!kiemTraTacVu()) {
        		JOptionPane.showMessageDialog(null, "Không thể đồng thời thực hiện thêm và xóa");
        		tglThem.setSelected(false);
        		return;
        	}
        	thietLapLaiForm();
        	tblBangNhanVien.clearSelection();
        	btnXoa.setEnabled(false);
        	tblBangNhanVien.setEnabled(false);
        	tblSua.setEnabled(false);
            moFormNhapDuLieu();
            layMaNhanVien();
        } else {
        	btnXoa.setEnabled(true);
        	tblBangNhanVien.setEnabled(true);
        	tblSua.setEnabled(true);
            dongFormNhapDuLieu();
        }
    }

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int lc = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn thoát không?", "Lưu Ý", JOptionPane.YES_NO_OPTION);
        if(lc == JOptionPane.YES_OPTION){
            tglThem.setSelected(false);
            tblSua.setSelected(false);
            tglThem.setEnabled(true);
            tblSua.setEnabled(true);
            btnXoa.setEnabled(true);
            tblBangNhanVien.setEnabled(true);
            dongFormNhapDuLieu();
            thietLapLaiForm();      
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
    	if(tblSua.isSelected()) {
    		datDuLieuNhanVienVaoForm(tblBangNhanVien.getSelectedRow());
    	}else {
            thietLapLaiForm();
    	}
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void cmbGioiTinhFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbGioiTinhFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGioiTinhFocusGained

    private void txtHoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoFocusGained
        // TODO add your handling code here:
        String duLieu = txtHo.getText().trim();
        if (duLieu.equals("Nhập Họ")) {
            txtHo.setText("");
            txtHo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtHoFocusGained

    private void txtHoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoFocusLost
        // TODO add your handling code here:
        if (txtHo.getText().isEmpty()) {
            txtHo.setText("Nhập Họ");
        }
    }//GEN-LAST:event_txtHoFocusLost

    private void txtTenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenFocusGained
        // TODO add your handling code here:
        String duLieu = txtTen.getText().trim();
        if (duLieu.equals("Nhập Tên")) {
            txtTen.setText("");
            txtTen.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtTenFocusGained

    private void txtTenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenFocusLost
        // TODO add your handling code here:
        if (txtTen.getText().isEmpty()) {
            txtTen.setText("Nhập Tên");
        }
    }//GEN-LAST:event_txtTenFocusLost

    private void txtCanCuocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCanCuocFocusGained
        // TODO add your handling code here:
        String duLieu = txtCanCuoc.getText().trim();
        if (duLieu.equals("Căn cước")) {
            txtCanCuoc.setText("");
            txtCanCuoc.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtCanCuocFocusGained

    private void txtCanCuocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCanCuocFocusLost
        // TODO add your handling code here:
        if (txtCanCuoc.getText().isEmpty()) {
            txtCanCuoc.setText("Căn cước");
        }
    }//GEN-LAST:event_txtCanCuocFocusLost

    private void txtSoDienThoaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoDienThoaiFocusGained
        // TODO add your handling code here:
        String duLieu = txtSoDienThoai.getText().trim();
        if (duLieu.equals("SDT")) {
            txtSoDienThoai.setText("");
            txtSoDienThoai.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtSoDienThoaiFocusGained

    private void txtSoDienThoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoDienThoaiFocusLost
        // TODO add your handling code here:
        if (txtSoDienThoai.getText().isEmpty()) {
            txtSoDienThoai.setText("SDT");
        }
    }//GEN-LAST:event_txtSoDienThoaiFocusLost

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtDiaChiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaChiFocusGained
        // TODO add your handling code here:
        String duLieu = txtDiaChi.getText().trim();
        if (duLieu.equalsIgnoreCase("Địa Chỉ")) {
            txtDiaChi.setText("");
            txtDiaChi.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtDiaChiFocusGained

    private void txtDiaChiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaChiFocusLost
        // TODO add your handling code here:
        if (txtDiaChi.getText().isEmpty()) {
            txtDiaChi.setText("Địa chỉ");
        }
    }//GEN-LAST:event_txtDiaChiFocusLost

    private void txtEMailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEMailFocusGained
        // TODO add your handling code here:
        String duLieu = txtEMail.getText().trim();
        if (duLieu.equals("EMail")) {
            txtEMail.setText("");
            txtEMail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtEMailFocusGained

    private void txtEMailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEMailFocusLost
        // TODO add your handling code here:
        if (txtEMail.getText().isEmpty()) {
            txtEMail.setText("EMail");
        }
    }//GEN-LAST:event_txtEMailFocusLost

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        try {
			if(tglThem.isSelected()) {
				kiemTraDuLieu();
		        NhanVien nv = taoNhanVien();
		        qlNhanVien.themNhanVien(nv);
		        Vector<String> dataNv = new Vector<>();
		        dataNv.add(tblBangNhanVien.getRowCount()+1+"");
		        dataNv.addAll(nv.duLieuFormCapNhat());
		        modal.addRow(dataNv);
		        thietLapLaiForm();
		        dongFormNhapDuLieu();
		        
		        btnXoa.setEnabled(true);
	        	tblBangNhanVien.setEnabled(true);
	        	tblSua.setEnabled(true);
	            dongFormNhapDuLieu();
		        
		        tglThem.setSelected(false);
			}else if(tblSua.isSelected()) {
				kiemTraDuLieu();
				NhanVien nv = taoNhanVien();
				qlNhanVien.suaNhanVien(nv);
				loadDuLieuNhanVienRaBang(modal);
				thietLapLaiForm();
		        dongFormNhapDuLieu();
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, e.getMessage());
		}
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void txtThamNienFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtThamNienFocusGained
        // TODO add your handling code here:
        String duLieu = txtThamNien.getText().trim();
        if (duLieu.equalsIgnoreCase("Thâm Niên")) {
            txtThamNien.setText("");
            txtThamNien.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtThamNienFocusGained

    private void txtThamNienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtThamNienFocusLost
        // TODO add your handling code here:
        if (txtThamNien.getText().isEmpty()) {
            txtThamNien.setText("Thâm Niên");
        }
    }//GEN-LAST:event_txtThamNienFocusLost

    private void moFormNhapDuLieu() {
        txtMaNhanVien.setText("");
        cmbGioiTinh.setEnabled(true);
            txtHo.setEnabled(true);
            txtTen.setEnabled(true);
            cmbPhongBan.setEnabled(true);
            txtCanCuoc.setEnabled(true);
            dcsNgaySinh.setEnabled(true);
            dcsNgayVaoLam.setEnabled(true);
            txtSoDienThoai.setEnabled(true);
            cmbThanhPho.setEnabled(true);
            //
            cmbQuanHuyen.setEnabled(true);
            cmbXa.setEnabled(true);
            txtDiaChi.setEnabled(true);
            cmbChucVu.setEnabled(true);
            cmbThuong.setEnabled(true);
            cmbHeSoLuong.setEnabled(true);
            txtEMail.setEnabled(true);
            chkBHYT.setEnabled(true);
            chkBHXH.setEnabled(true);
            txtThamNien.setEnabled(true);
            
            btnXacNhan.setEnabled(true);
            btnLamMoi.setEnabled(true);
            btnThoat.setEnabled(true);
    }

    private void dongFormNhapDuLieu() {
        txtMaNhanVien.setText("");
        cmbGioiTinh.setEnabled(false);
        txtHo.setEnabled(false);
        txtTen.setEnabled(false);
        cmbPhongBan.setEnabled(false);
        txtCanCuoc.setEnabled(false);
        dcsNgaySinh.setEnabled(false);
        dcsNgayVaoLam.setEnabled(false);
        txtSoDienThoai.setEnabled(false);
        cmbThanhPho.setEnabled(false);
        //
        cmbQuanHuyen.setEnabled(false);
        cmbXa.setEnabled(false);
        txtDiaChi.setEnabled(false);
        cmbChucVu.setEnabled(false);
        cmbThuong.setEnabled(false);
        cmbHeSoLuong.setEnabled(false);
        txtEMail.setEnabled(false);
        chkBHYT.setEnabled(false);
        chkBHXH.setEnabled(false);
        txtThamNien.setEnabled(false);

        btnXacNhan.setEnabled(false);
        btnLamMoi.setEnabled(false);
        btnThoat.setEnabled(false);

    }
    
    private void loadDuLieuNhanVienRaBang(DefaultTableModel modal) {
    	int i=1;
    	tblBangNhanVien.removeAll();
    	modal.setRowCount(0);
        for (NhanVien nv : qlNhanVien.getDs()) {
        	System.out.println(nv);
        	Vector<String> data = new  Vector<>();
        	data.add(i+"");
        	i++;
        	data.addAll(nv.duLieuFormCapNhat());
        	modal.addRow(data);
            }
	}
      
    private PhongBan[] danhSachPhongBan(){
        ArrayList<PhongBan> dsPhongBan = qlPhongBan.getDs();
        PhongBan[] mang = new PhongBan[dsPhongBan.size()];
        mang = dsPhongBan.toArray(mang);
        return mang;
    }
    
    private ChucVu[] danhSachChucVu(){
        ArrayList<ChucVu> dsChucVu = qlChucVu.layDanhSachChucVu();
        ChucVu[] mang = new ChucVu[dsChucVu.size()];
        mang = dsChucVu.toArray(mang);
        return mang;
    }
    
    private NhanVien taoNhanVien() {
    	String ma = txtMaNhanVien.getText().trim();
        String ho = txtHo.getText().trim();
        String ten = txtTen.getText().trim();
        GioiTinh gioiTinh = (GioiTinh) cmbGioiTinh.getSelectedItem();
        PhongBan phongBan = (PhongBan) cmbPhongBan.getSelectedItem();
        String cccd = txtCanCuoc.getText().trim();
        Date ngaySinh = dcsNgaySinh.getDate();
        Date ngayVaoLam = dcsNgayVaoLam.getDate();
        String sdt = txtSoDienThoai.getText().trim();
        String thanhPho_Tinh = (String) cmbThanhPho.getSelectedItem();
        String quanHuyen = (String) cmbQuanHuyen.getSelectedItem();
        String thiXa = (String) cmbXa.getSelectedItem();
        String diaChiCuThe = txtDiaChi.getText().trim();
        DiaChi diaChi = qlDiaChi.taoDiaChiVaTraDiaChi(diaChiCuThe, thanhPho_Tinh, quanHuyen, thiXa);
        ChucVu chucVu = (ChucVu) cmbChucVu.getSelectedItem();
        
        PhuCap phuCap = (PhuCap) cmbThuong.getSelectedItem();
        float heSoLuong = Float.parseFloat((String) cmbHeSoLuong.getSelectedItem());
        String email = txtEMail.getText();
        boolean bhyt = false;
        if(chkBHYT.isSelected()){
            bhyt = true;
        }
        boolean bhxh = false;
        if(chkBHYT.isSelected()){
            bhxh = true;
        }
        float thamNien = Float.parseFloat(txtThamNien.getText());
        NhanVien nv = new NhanVien(ma, thanhPho_Tinh, ten, sdt, ngaySinh, ngayVaoLam, cccd, diaChi, phuCap, gioiTinh, quanHuyen, chucVu, bhyt, bhxh, phongBan, email, heSoLuong, thamNien);
        return nv;
    }
    
    private void caiDuLieuDiaChi() {
    	String thanhPho[] = qlDiaChi.layDanhSachTinhThanhPho();
    	cmbThanhPho.removeAllItems();
    	cmbThanhPho.setModel(new DefaultComboBoxModel<String>(thanhPho));
    	
    }
    
}
