/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.time.LocalDate;
import java.time.Year;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import DAO.BangLuongNhanVien_Dao;
import DAO.NhanVien_Dao;
import entity.BangLuongNhanVien;
import utils.ExportToExcel;
import utils.MailSenderAll;
import utils.MailSenderWorker;

/**
 *
 * @author ACER
 */
public class frm_NhanVien_TinhLuong extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * Creates new form frm_NhanVien_CapNhat_
     */
    public frm_NhanVien_TinhLuong() {
        initComponents();
        caiThangVaNamHienTai();
    }
    
    public static String[] getRecentYears(int count) {
        int currentYear = Year.now().getValue();
        String[] recentYears = new String[count];
        for (int i = 0; i < count; i++) {
            recentYears[i] = currentYear - i + "";
        }

        return recentYears;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "serial" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	modal = new DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Mã Bảng Lương", "Mã Nhân Viên", "Tên", "Chức Vụ","Phòng Ban", "Lương cứng", "Hệ số", "Thuế", "Lương Nhận"
                }
            ) {
                @SuppressWarnings("rawtypes")
				Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class,java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false, false
                };

                @SuppressWarnings("rawtypes")
				public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            };
    	qlBangLuong = new BangLuongNhanVien_Dao();
        lblHXa = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        pnDienThongTin = new javax.swing.JPanel();
        pnMa_Ten_HeSo = new javax.swing.JPanel();
        lblMa = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        lblTen = new javax.swing.JLabel();
        lblHeSo = new javax.swing.JLabel();
        txtHeSo = new javax.swing.JTextField();
        pnNgayCong_Vang = new javax.swing.JPanel();
        lblCong = new javax.swing.JLabel();
        txtCong = new javax.swing.JTextField();
        lblCoPhep = new javax.swing.JLabel();
        txtCoPhep = new javax.swing.JTextField();
        lblKhongPhep = new javax.swing.JLabel();
        txtKhongPhep = new javax.swing.JTextField();
        pnNgayCong_Vang1 = new javax.swing.JPanel();
        lblCong1 = new javax.swing.JLabel();
        txtCong1 = new javax.swing.JTextField();
        lblCoPhep1 = new javax.swing.JLabel();
        txtCoPhep1 = new javax.swing.JTextField();
        lblKhongPhep1 = new javax.swing.JLabel();
        txtKhongPhep1 = new javax.swing.JTextField();
        pnTangCa_BaoHiem = new javax.swing.JPanel();
        lblTangCa = new javax.swing.JLabel();
        txtTangCa = new javax.swing.JTextField();
        lblBHYT = new javax.swing.JLabel();
        txtBHYT = new javax.swing.JTextField();
        lblBHXH = new javax.swing.JLabel();
        txtBHXH = new javax.swing.JTextField();
        pnTangCa_BaoHiem1 = new javax.swing.JPanel();
        lblTangCa1 = new javax.swing.JLabel();
        txtTangCa1 = new javax.swing.JTextField();
        lblBHYT1 = new javax.swing.JLabel();
        txtBHYT1 = new javax.swing.JTextField();
        lblBHXH1 = new javax.swing.JLabel();
        txtBHXH1 = new javax.swing.JTextField();
        pnThang_PhuCap_Luong = new javax.swing.JPanel();
        cmbThang = new javax.swing.JComboBox<>();
        txtLuong = new javax.swing.JTextField();
        lblLuong = new javax.swing.JLabel();
        txtPhuCap = new javax.swing.JTextField();
        lblPhuCap = new javax.swing.JLabel();
        lblThang = new javax.swing.JLabel();
        pnBody = new javax.swing.JPanel();
        scrCongNhan = new javax.swing.JScrollPane();
        tblCongNhan = new javax.swing.JTable();
        pnThongTinNhanVien = new javax.swing.JPanel();
        lblChonThang = new javax.swing.JLabel();
        cmnChonThang = new javax.swing.JComboBox<>();
        lblChonNam = new javax.swing.JLabel();
        cmbChonNam = new javax.swing.JComboBox<>(getRecentYears(4));
        btnTinhLuongToanBo = new javax.swing.JButton();
        btnGuiThongBaoDenNguoiDung = new javax.swing.JButton();
        btnXuatBangLuongExel = new javax.swing.JButton();
        txtNhapMa = new javax.swing.JTextField();
        lblNhapMa = new javax.swing.JLabel();
        btnBangThue = new javax.swing.JButton();
        pnHeader = new javax.swing.JPanel();
        pnTieuDe = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();

        lblHXa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHXa.setText("Xã");
        lblHXa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn--", "Item 1", "Item 2", "Item 3", "Item 4" }));

        pnDienThongTin.setBackground(new java.awt.Color(255, 255, 255));
        pnDienThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Thông Tin Nhân Viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pnDienThongTin.setMaximumSize(new java.awt.Dimension(500, 250));
        pnDienThongTin.setMinimumSize(new java.awt.Dimension(200, 200));

        pnMa_Ten_HeSo.setBackground(new java.awt.Color(255, 255, 255));

        lblMa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMa.setText("Mã Nhân Viên");
        lblMa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtMa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });

        txtTen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTen.setText("Tên");
        lblTen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        lblHeSo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeSo.setText("Hệ Số");
        lblHeSo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        txtHeSo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        javax.swing.GroupLayout pnMa_Ten_HeSoLayout = new javax.swing.GroupLayout(pnMa_Ten_HeSo);
        pnMa_Ten_HeSo.setLayout(pnMa_Ten_HeSoLayout);
        pnMa_Ten_HeSoLayout.setHorizontalGroup(
            pnMa_Ten_HeSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMa_Ten_HeSoLayout.createSequentialGroup()
                .addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHeSo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHeSo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMa_Ten_HeSoLayout.setVerticalGroup(
            pnMa_Ten_HeSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMa_Ten_HeSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblHeSo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtHeSo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnNgayCong_Vang.setBackground(new java.awt.Color(255, 255, 255));

        lblCong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCong.setText("Số Ngày Công");
        lblCong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtCong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCongActionPerformed(evt);
            }
        });

        lblCoPhep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCoPhep.setText("Cả ngày");
        lblCoPhep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        txtCoPhep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        lblKhongPhep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhongPhep.setText("Nữa ngày");
        lblKhongPhep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        txtKhongPhep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        pnNgayCong_Vang1.setBackground(new java.awt.Color(255, 255, 255));

        lblCong1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCong1.setText("Có phép");
        lblCong1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtCong1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCong1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCong1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtCong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCong1ActionPerformed(evt);
            }
        });

        lblCoPhep1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCoPhep1.setText("Không phép");
        lblCoPhep1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        txtCoPhep1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        lblKhongPhep1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhongPhep1.setText("Trễ");
        lblKhongPhep1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        txtKhongPhep1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        pnTangCa_BaoHiem.setBackground(new java.awt.Color(255, 255, 255));

        lblTangCa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTangCa.setText("Tăng ca");
        lblTangCa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtTangCa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTangCa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTangCa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtTangCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTangCaActionPerformed(evt);
            }
        });

        lblBHYT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBHYT.setText("Bảo hiểm");
        lblBHYT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        txtBHYT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        lblBHXH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBHXH.setText("Phụ Cấp");
        lblBHXH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        txtBHXH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        javax.swing.GroupLayout pnTangCa_BaoHiemLayout = new javax.swing.GroupLayout(pnTangCa_BaoHiem);
        pnTangCa_BaoHiem.setLayout(pnTangCa_BaoHiemLayout);
        pnTangCa_BaoHiemLayout.setHorizontalGroup(
            pnTangCa_BaoHiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTangCa_BaoHiemLayout.createSequentialGroup()
                .addComponent(lblTangCa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTangCa, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBHYT, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBHYT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBHXH, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBHXH, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnTangCa_BaoHiemLayout.setVerticalGroup(
            pnTangCa_BaoHiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTangCa_BaoHiemLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(pnTangCa_BaoHiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTangCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTangCa)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnTangCa_BaoHiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBHYT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBHYT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBHXH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBHXH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnTangCa_BaoHiem1.setBackground(new java.awt.Color(255, 255, 255));

        lblTangCa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTangCa1.setText("Lương trước thuế");
        lblTangCa1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtTangCa1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTangCa1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTangCa1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtTangCa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTangCa1ActionPerformed(evt);
            }
        });

        lblBHYT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBHYT1.setText("Thuế");
        lblBHYT1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        txtBHYT1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        lblBHXH1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBHXH1.setText("Lương sau thuế");
        lblBHXH1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        txtBHXH1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        javax.swing.GroupLayout pnTangCa_BaoHiem1Layout = new javax.swing.GroupLayout(pnTangCa_BaoHiem1);
        pnTangCa_BaoHiem1.setLayout(pnTangCa_BaoHiem1Layout);
        pnTangCa_BaoHiem1Layout.setHorizontalGroup(
            pnTangCa_BaoHiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTangCa_BaoHiem1Layout.createSequentialGroup()
                .addComponent(lblTangCa1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTangCa1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBHYT1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBHYT1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBHXH1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBHXH1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        pnTangCa_BaoHiem1Layout.setVerticalGroup(
            pnTangCa_BaoHiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTangCa_BaoHiem1Layout.createSequentialGroup()
                .addGroup(pnTangCa_BaoHiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTangCa1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnTangCa_BaoHiem1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnTangCa_BaoHiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBHYT1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBHYT1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBHXH1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBHXH1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtTangCa1))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnNgayCong_Vang1Layout = new javax.swing.GroupLayout(pnNgayCong_Vang1);
        pnNgayCong_Vang1.setLayout(pnNgayCong_Vang1Layout);
        pnNgayCong_Vang1Layout.setHorizontalGroup(
            pnNgayCong_Vang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNgayCong_Vang1Layout.createSequentialGroup()
                .addGroup(pnNgayCong_Vang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNgayCong_Vang1Layout.createSequentialGroup()
                        .addComponent(lblCong1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCong1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCoPhep1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCoPhep1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKhongPhep1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKhongPhep1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnTangCa_BaoHiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTangCa_BaoHiem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnNgayCong_Vang1Layout.setVerticalGroup(
            pnNgayCong_Vang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNgayCong_Vang1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNgayCong_Vang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnNgayCong_Vang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCoPhep1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCoPhep1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblKhongPhep1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtKhongPhep1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCong1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCong1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTangCa_BaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTangCa_BaoHiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnNgayCong_VangLayout = new javax.swing.GroupLayout(pnNgayCong_Vang);
        pnNgayCong_Vang.setLayout(pnNgayCong_VangLayout);
        pnNgayCong_VangLayout.setHorizontalGroup(
            pnNgayCong_VangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNgayCong_VangLayout.createSequentialGroup()
                .addGroup(pnNgayCong_VangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNgayCong_VangLayout.createSequentialGroup()
                        .addComponent(lblCong, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCong, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCoPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCoPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKhongPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKhongPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnNgayCong_Vang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnNgayCong_VangLayout.setVerticalGroup(
            pnNgayCong_VangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNgayCong_VangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNgayCong_VangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnNgayCong_VangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCoPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCoPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblKhongPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtKhongPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnNgayCong_Vang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnThang_PhuCap_Luong.setBackground(new java.awt.Color(255, 255, 255));

        cmbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbChonNam.setModel(new javax.swing.DefaultComboBoxModel<>(getRecentYears(4)));
        txtLuong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        lblLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLuong.setText("Lương CB");
        lblLuong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        txtPhuCap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        lblPhuCap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhuCap.setText("Thâm niên");
        lblPhuCap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        lblThang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThang.setText("Tháng");
        lblThang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        javax.swing.GroupLayout pnThang_PhuCap_LuongLayout = new javax.swing.GroupLayout(pnThang_PhuCap_Luong);
        pnThang_PhuCap_Luong.setLayout(pnThang_PhuCap_LuongLayout);
        pnThang_PhuCap_LuongLayout.setHorizontalGroup(
            pnThang_PhuCap_LuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThang_PhuCap_LuongLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(lblPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnThang_PhuCap_LuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThang_PhuCap_LuongLayout.createSequentialGroup()
                    .addComponent(lblThang, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cmbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(370, Short.MAX_VALUE)))
        );
        pnThang_PhuCap_LuongLayout.setVerticalGroup(
            pnThang_PhuCap_LuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThang_PhuCap_LuongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThang_PhuCap_LuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnThang_PhuCap_LuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThang_PhuCap_LuongLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnThang_PhuCap_LuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblThang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnDienThongTinLayout = new javax.swing.GroupLayout(pnDienThongTin);
        pnDienThongTin.setLayout(pnDienThongTinLayout);
        pnDienThongTinLayout.setHorizontalGroup(
            pnDienThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDienThongTinLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(pnDienThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnThang_PhuCap_Luong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnMa_Ten_HeSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnNgayCong_Vang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );
        pnDienThongTinLayout.setVerticalGroup(
            pnDienThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDienThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMa_Ten_HeSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnThang_PhuCap_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(pnNgayCong_Vang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(1250, 800));
        setMinimumSize(new java.awt.Dimension(1196, 680));
        setPreferredSize(new java.awt.Dimension(1250, 680));
        setLayout(new java.awt.BorderLayout());

        pnBody.setBackground(new java.awt.Color(255, 255, 255));

        scrCongNhan.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrCongNhan.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        
        tblCongNhan.setColumnSelectionAllowed(true);
        tblCongNhan.setPreferredSize(new java.awt.Dimension(200, 400));
        scrCongNhan.setViewportView(tblCongNhan);
        tblCongNhan.setModel(modal);
        tblCongNhan.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCongNhan.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				int row = tblCongNhan.rowAtPoint(e.getPoint());
                if (e.getButton() == MouseEvent.BUTTON1 && row >= 0) {
                    String ma = (String) tblCongNhan.getValueAt(row, 0);
                    BangLuongNhanVien bangLuongNhanVien = qlBangLuong.layBangLuongTheoMa(ma);
                    Dialog_BangLuongNhanVien bangLuongDialog = new Dialog_BangLuongNhanVien(new Frame(), true);
                    bangLuongDialog.dayDuLieuVaoBang(bangLuongNhanVien);
                    bangLuongDialog.setLocationRelativeTo(null);
                    bangLuongDialog.setVisible(true);
                }
			}
		});

        pnThongTinNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTinNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Thời Gian", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        lblChonThang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChonThang.setText("Tháng");
        lblChonThang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        cmnChonThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        lblChonNam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChonNam.setText("Năm");
        lblChonNam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));


        javax.swing.GroupLayout pnThongTinNhanVienLayout = new javax.swing.GroupLayout(pnThongTinNhanVien);
        pnThongTinNhanVien.setLayout(pnThongTinNhanVienLayout);
        pnThongTinNhanVienLayout.setHorizontalGroup(
            pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinNhanVienLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblChonThang, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(lblChonNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmnChonThang, 0, 132, Short.MAX_VALUE)
                    .addComponent(cmbChonNam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        pnThongTinNhanVienLayout.setVerticalGroup(
            pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinNhanVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChonThang, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmnChonThang, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChonNam, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbChonNam, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );

        btnTinhLuongToanBo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive - Industrial University of HoChiMinh City\\Documents\\NetBeansProjects\\JavaApplication8\\img\\icons\\all (1).png")); // NOI18N
        btnTinhLuongToanBo.setText("Tính Lương Toàn Bộ Nhân Viên");
        btnTinhLuongToanBo.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					btnTinhLuongActionPerform(e);
				} catch (Exception e1) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null, e1.getMessage());
				}
			}
		});
        btnGuiThongBaoDenNguoiDung.setText("Gửi thông báo lương");
        btnGuiThongBaoDenNguoiDung.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				btnGuiThongBaoDenNguoiDungPdf(e);
			}
		});
        
        btnXuatBangLuongExel.setText("Xuất bảng lương");
        btnXuatBangLuongExel.setPreferredSize(new java.awt.Dimension(118, 31));
        btnXuatBangLuongExel.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				btnXuatBangLuongExel(e);
			}
		});
        txtNhapMa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNhapMa.setMargin(null);
        txtNhapMa.setMinimumSize(new java.awt.Dimension(64, 23));
        txtNhapMa.setPreferredSize(new java.awt.Dimension(71, 23));

        lblNhapMa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhapMa.setText("Nhập mã");

        btnBangThue.setText("Bảng Thuế");
        btnBangThue.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				btnBangThueActionPerformed(e);
			}
		});

        javax.swing.GroupLayout pnBodyLayout = new javax.swing.GroupLayout(pnBody);
        pnBody.setLayout(pnBodyLayout);
        pnBodyLayout.setHorizontalGroup(
            pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrCongNhan)
            .addGroup(pnBodyLayout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(pnThongTinNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnBodyLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txtNhapMa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNhapMa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(btnGuiThongBaoDenNguoiDung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTinhLuongToanBo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBangThue, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(btnXuatBangLuongExel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        pnBodyLayout.setVerticalGroup(
            pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBodyLayout.createSequentialGroup()
                .addComponent(pnThongTinNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBodyLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnXuatBangLuongExel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(scrCongNhan, 300, 310, Short.MAX_VALUE))
                    .addGroup(pnBodyLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNhapMa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNhapMa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTinhLuongToanBo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuiThongBaoDenNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBangThue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        add(pnBody, java.awt.BorderLayout.CENTER);

        pnHeader.setBackground(new java.awt.Color(255, 255, 255));

        pnTieuDe.setBackground(new java.awt.Color(255, 153, 0));

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTieuDe.setText("Lương Nhân Viên");
        lblTieuDe.setToolTipText("");
        lblTieuDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnTieuDeLayout = new javax.swing.GroupLayout(pnTieuDe);
        pnTieuDe.setLayout(pnTieuDeLayout);
        pnTieuDeLayout.setHorizontalGroup(
            pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTieuDeLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(lblTieuDe)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        pnTieuDeLayout.setVerticalGroup(
            pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTieuDe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(pnTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pnTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(pnHeader, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    protected void btnBangThueActionPerformed(ActionEvent e) {
		Dialog_BangThue bangThue = new Dialog_BangThue(null, true);
		bangThue.setLocationRelativeTo(null);
		bangThue.setVisible(true);
	}

	protected void btnGuiThongBaoDenNguoiDungPdf(ActionEvent e) {
		int soNhanVienDaTinhLuong = tblCongNhan.getRowCount();
		String maBangLuong[] = new String[soNhanVienDaTinhLuong];
		for(int i = 0; i < soNhanVienDaTinhLuong; i++) {
			maBangLuong[i] = (String) tblCongNhan.getValueAt(i, 0);
			System.out.println(maBangLuong[i]);
		}
		guiEmailChoToanBoNguoiNhanLuongTrongNen(maBangLuong);
	}

	protected void btnXuatBangLuongExel(ActionEvent e) {
		ExportToExcel.exportToExcel(tblCongNhan);
	}

	protected void btnTinhLuongActionPerform(ActionEvent evt) throws Exception {
    	String thang = (String) cmnChonThang.getSelectedItem();
    	String nam = (String) cmbChonNam.getSelectedItem();
    	if(thang.equalsIgnoreCase("Bất kì") || nam.equalsIgnoreCase("Bất kì")) {
    		throw new Exception("Vui Lòng Chọn Tháng Và Năm Cần Tính Lương");
    	}
		ArrayList<BangLuongNhanVien> dsBangLuong = qlBangLuong.layDanhSachThongTinTuBangChamCongVaThemBangLuong(Integer.parseInt(thang), Integer.parseInt(nam));
		for (BangLuongNhanVien bangLuongNhanVien : dsBangLuong) {
			modal.addRow(bangLuongNhanVien.hienThiDanhSachBangLuong());
		}
	}

	private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    private void txtCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCongActionPerformed

    private void txtTangCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTangCaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTangCaActionPerformed

    private void txtCong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCong1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCong1ActionPerformed

    private void txtTangCa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTangCa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTangCa1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DefaultTableModel modal;
    private javax.swing.JButton btnGuiThongBaoDenNguoiDung;
    private javax.swing.JButton btnTinhLuongToanBo;
    private javax.swing.JButton btnXuatBangLuongExel;
    private javax.swing.JComboBox<String> cmbThang;
    private javax.swing.JComboBox<String> cmnChonThang;
    private javax.swing.JButton btnBangThue;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> cmbChonNam;
    private javax.swing.JLabel lblBHXH;
    private javax.swing.JLabel lblBHXH1;
    private javax.swing.JLabel lblBHYT;
    private javax.swing.JLabel lblBHYT1;
    private javax.swing.JLabel lblChonNam;
    private javax.swing.JLabel lblChonThang;
    private javax.swing.JLabel lblCoPhep;
    private javax.swing.JLabel lblCoPhep1;
    private javax.swing.JLabel lblCong;
    private javax.swing.JLabel lblCong1;
    private javax.swing.JLabel lblHXa;
    private javax.swing.JLabel lblHeSo;
    private javax.swing.JLabel lblKhongPhep;
    private javax.swing.JLabel lblKhongPhep1;
    private javax.swing.JLabel lblLuong;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblNhapMa;
    private javax.swing.JLabel lblPhuCap;
    private javax.swing.JLabel lblTangCa;
    private javax.swing.JLabel lblTangCa1;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblThang;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnBody;
    private javax.swing.JPanel pnDienThongTin;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnMa_Ten_HeSo;
    private javax.swing.JPanel pnNgayCong_Vang;
    private javax.swing.JPanel pnNgayCong_Vang1;
    private javax.swing.JPanel pnTangCa_BaoHiem;
    private javax.swing.JPanel pnTangCa_BaoHiem1;
    private javax.swing.JPanel pnThang_PhuCap_Luong;
    private javax.swing.JPanel pnThongTinNhanVien;
    private javax.swing.JPanel pnTieuDe;
    private javax.swing.JScrollPane scrCongNhan;
    private javax.swing.JTable tblCongNhan;
    private javax.swing.JTextField txtBHXH;
    private javax.swing.JTextField txtBHXH1;
    private javax.swing.JTextField txtBHYT;
    private javax.swing.JTextField txtBHYT1;
    private javax.swing.JTextField txtCoPhep;
    private javax.swing.JTextField txtCoPhep1;
    private javax.swing.JTextField txtCong;
    private javax.swing.JTextField txtCong1;
    private javax.swing.JTextField txtHeSo;
    private javax.swing.JTextField txtKhongPhep;
    private javax.swing.JTextField txtKhongPhep1;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNhapMa;
    private javax.swing.JTextField txtPhuCap;
    private javax.swing.JTextField txtTangCa;
    private javax.swing.JTextField txtTangCa1;
    private javax.swing.JTextField txtTen;
    private BangLuongNhanVien_Dao qlBangLuong;
    // End of variables declaration//GEN-END:variables
	private BangLuongNhanVien bangLuongNhanVien;
    
    private void caiThangVaNamHienTai() {
    	LocalDate currentDate = LocalDate.now();
    	int currentYear = currentDate.getYear();
    	int month = currentDate.getMonthValue();
    	cmnChonThang.setSelectedItem(month+"");;
        cmbChonNam.setSelectedItem(currentYear+"");
    }
     	
    private void guiEmailChoToanBoNguoiNhanLuongTrongNen(String[] maBangLuong) {
    	MailSenderAll all = new MailSenderAll(maBangLuong);
    	all.execute();
    }
}
