/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import DAO.DAO_SanPham;
import Enum.LoaiGo;
import entity.SanPham;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JLabel;

/**
 *
 * @author ADMINS
 */
public class frm_SanPham_CapNhat extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5328082483073631392L;
	/**
     * Creates new form frm_SanPham_CapNhat
     */
    public frm_SanPham_CapNhat() {
        initComponents();
        hienThiDanhSachSanPham();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "serial" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	qlSanPham = new DAO_SanPham();
        pnCapNhatNhanVien = new javax.swing.JPanel();
        btnChonAnh = new javax.swing.JButton();
        txtNhapMa = new javax.swing.JTextField();
        lblTimKiem = new javax.swing.JLabel();
        scrSanPham = new javax.swing.JScrollPane();
        tblBangSanPham = new javax.swing.JTable();
        pnHinhNen = new form.HinhNen();
        pnThongTinSanPham = new javax.swing.JPanel();
        lblMaSP = new javax.swing.JLabel();
        txtMaSanPham = new javax.swing.JTextField();
        lblTenSP = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        lblSoLuong = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        lblLoaiGo = new javax.swing.JLabel();
        cmbLoaiGo = new javax.swing.JComboBox<>();
        lblKhoiLuong = new javax.swing.JLabel();
        txtKhoiLuong = new javax.swing.JTextField();
        lblKichThuoc = new javax.swing.JLabel();
        txtKichThuoc = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        lblGia = new javax.swing.JLabel();
        lblThoiGianSXDuKien = new javax.swing.JLabel();
        dchThoiHanSXDuKien = new com.toedter.calendar.JDateChooser();
        btnXacNhan = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        tglThem = new javax.swing.JToggleButton();
        tglSua = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(1250, 680));

        pnCapNhatNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        pnCapNhatNhanVien.setMaximumSize(new java.awt.Dimension(1196, 680));
        pnCapNhatNhanVien.setPreferredSize(new java.awt.Dimension(1196, 680));

        btnChonAnh.setText("Chọn");
        btnChonAnh.setEnabled(false);
        btnChonAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChonAnhMouseClicked(evt);
            }
        });


        txtNhapMa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNhapMa.setText("Nhập mã");


        lblTimKiem.setText("Tìm kiếm");
        
        modal = new DefaultTableModel(
                new String [][] {
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null}
                },
                new String [] {
                    "STT", "Mã sản phẩm",  "Tên sản phẩm","Giá thành", "Thời gian sản xuất", "Loại gỗ", "Khối Lượng"
                }
            ) {
                @SuppressWarnings("rawtypes")
				Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false, false, false
                };

                @SuppressWarnings("rawtypes")
				public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            };
        tblBangSanPham.setModel(modal);
        tblBangSanPham.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblBangSanPham.setDropMode(javax.swing.DropMode.ON);
        tblBangSanPham.setPreferredSize(new java.awt.Dimension(200, 400));
        tblBangSanPham.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				int dongDaChon = tblBangSanPham.getSelectedRow();
				if(dongDaChon!=-1) {
					String maSanPham = (String) tblBangSanPham.getValueAt(dongDaChon, 1);
					SanPham sanPham = qlSanPham.timSanPhamTheoMa(maSanPham);
					dienDuLieuSanPhamVaoBangThongTin(sanPham);
				}
			}
		});
        scrSanPham.setViewportView(tblBangSanPham);

        javax.swing.GroupLayout pnHinhNenLayout = new javax.swing.GroupLayout(pnHinhNen);
        pnHinhNen.setLayout(pnHinhNenLayout);
        pnHinhNenLayout.setHorizontalGroup(
            pnHinhNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );
        pnHinhNenLayout.setVerticalGroup(
            pnHinhNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        pnThongTinSanPham.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTinSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)), "Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        lblMaSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaSP.setText("Mã sản phẩm");
        lblMaSP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtMaSanPham.setEditable(false);
        txtMaSanPham.setBackground(new java.awt.Color(255, 204, 51));
        txtMaSanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMaSanPham.setHorizontalAlignment(javax.swing.JTextField.CENTER);
//        txtMaSanPham.setText("MSP0001");
        txtMaSanPham.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));


        lblTenSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenSP.setText("Tên sản phẩm");
        lblTenSP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtTenSP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTenSP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtTenSP.setEnabled(false);


        lblSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoLuong.setText("Số lượng");
        lblSoLuong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtSoLuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSoLuong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtSoLuong.setEnabled(false);


        lblLoaiGo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoaiGo.setText("Loại gỗ");
        lblLoaiGo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        cmbLoaiGo.setMaximumRowCount(64);
        cmbLoaiGo.setModel(new javax.swing.DefaultComboBoxModel<>(new LoaiGo[] {LoaiGo.GOTHUONG, LoaiGo.GOTRUNG, LoaiGo.GOTOT}));
        cmbLoaiGo.setToolTipText("");
        cmbLoaiGo.setBorder(null);
        cmbLoaiGo.setEnabled(false);


        lblKhoiLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhoiLuong.setText("Khối lượng(kg)");
        lblKhoiLuong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtKhoiLuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKhoiLuong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtKhoiLuong.setEnabled(false);

        lblKichThuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKichThuoc.setText("Kích thước");
        lblKichThuoc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        txtKichThuoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKichThuoc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtKichThuoc.setEnabled(false);


        txtGia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtGia.setEnabled(false);

        lblGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGia.setText("Giá (VNĐ):");
        lblGia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        lblThoiGianSXDuKien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThoiGianSXDuKien.setText("Thời hạn sản xuất dự kiến");
        lblThoiGianSXDuKien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        dchThoiHanSXDuKien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        dchThoiHanSXDuKien.setEnabled(false);

        btnXacNhan.setIcon(new javax.swing.ImageIcon("D:\\PTUDV2\\QuanLySanPham\\QLyLuongSP\\img\\icons\\check-mark.png")); // NOI18N
        btnXacNhan.setText("Xác Nhận");
        btnXacNhan.setEnabled(false);
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon("D:\\PTUDV2\\QuanLySanPham\\QLyLuongSP\\img\\icons\\refresh-arrow.png")); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.setEnabled(false);
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon("D:\\PTUDV2\\QuanLySanPham\\QLyLuongSP\\img\\button.png")); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setEnabled(false);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThongTinSanPhamLayout = new javax.swing.GroupLayout(pnThongTinSanPham);
        pnThongTinSanPham.setLayout(pnThongTinSanPhamLayout);
        pnThongTinSanPhamLayout.setHorizontalGroup(
            pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinSanPhamLayout.createSequentialGroup()
                .addGroup(pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinSanPhamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnThongTinSanPhamLayout.createSequentialGroup()
                                    .addComponent(lblThoiGianSXDuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dchThoiHanSXDuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnThongTinSanPhamLayout.createSequentialGroup()
                                    .addGroup(pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                    .addGap(6, 6, 6)
                                    .addGroup(pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTenSP)
                                        .addComponent(txtSoLuong))))
                            .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinSanPhamLayout.createSequentialGroup()
                                .addComponent(lblLoaiGo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbLoaiGo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnThongTinSanPhamLayout.createSequentialGroup()
                                .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinSanPhamLayout.createSequentialGroup()
                                .addComponent(lblKhoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKhoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnThongTinSanPhamLayout.createSequentialGroup()
                                .addComponent(lblKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnThongTinSanPhamLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(btnLamMoi)
                        .addGap(89, 89, 89)
                        .addComponent(btnXacNhan)
                        .addGap(89, 89, 89)
                        .addComponent(btnThoat)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThongTinSanPhamLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(870, Short.MAX_VALUE)))
        );
        pnThongTinSanPhamLayout.setVerticalGroup(
            pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoaiGo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLoaiGo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKhoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKhoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThoiGianSXDuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dchThoiHanSXDuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
            .addGroup(pnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThongTinSanPhamLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(293, Short.MAX_VALUE)))
        );

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setText("Xóa bảng");
        btnXoa.setMaximumSize(new java.awt.Dimension(556, 514));
        btnXoa.setMinimumSize(new java.awt.Dimension(556, 514));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tglThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tglThem.setText("Thêm");
        tglThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglThemActionPerformed(evt);
            }
        });

        tglSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tglSua.setText("Sửa");
        tglSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                	tglSuaActionPerformed(evt);
				} catch (Exception e) {
					// TODO: handle exception
					JOptionPane.showMessageDialog(null, e.getMessage());
				}
            }
        });
        
        btnHDSD = new JButton("?");
        btnHDSD.setFont(new Font("Tahoma", Font.BOLD, 10));
        btnHDSD.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					btnHuongDanActionPerformed(e);
				} catch (Exception e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
        JLabel lblHDSD = new JLabel("Hướng dẫn sử dụng");

        javax.swing.GroupLayout pnCapNhatNhanVienLayout = new javax.swing.GroupLayout(pnCapNhatNhanVien);
        pnCapNhatNhanVienLayout.setHorizontalGroup(
        	pnCapNhatNhanVienLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        			.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        					.addGap(54)
        					.addComponent(pnHinhNen, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(pnThongTinSanPham, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(scrSanPham, GroupLayout.PREFERRED_SIZE, 1301, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        		.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        			.addGap(40)
        			.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(btnChonAnh)
        				.addComponent(txtNhapMa, GroupLayout.PREFERRED_SIZE, 126, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblTimKiem, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 643, Short.MAX_VALUE)
        			.addComponent(tglThem, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
        			.addGap(55)
        			.addComponent(tglSua, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        			.addGap(47)
        			.addComponent(btnXoa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(75))
        		.addGroup(Alignment.TRAILING, pnCapNhatNhanVienLayout.createSequentialGroup()
        			.addContainerGap(1061, Short.MAX_VALUE)
        			.addComponent(lblHDSD, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnHDSD)
        			.addGap(105))
        );
        pnCapNhatNhanVienLayout.setVerticalGroup(
        	pnCapNhatNhanVienLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        			.addGap(8)
        			.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnHDSD)
        				.addComponent(lblHDSD))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        					.addComponent(pnHinhNen, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(btnChonAnh))
        				.addComponent(pnThongTinSanPham, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
        			.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(pnCapNhatNhanVienLayout.createSequentialGroup()
        					.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(txtNhapMa, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblTimKiem, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
        					.addGap(0, 2, Short.MAX_VALUE))
        				.addGroup(pnCapNhatNhanVienLayout.createParallelGroup(Alignment.LEADING)
        					.addComponent(tglSua, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        					.addComponent(tglThem, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
        				.addComponent(btnXoa, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(scrSanPham, GroupLayout.PREFERRED_SIZE, 223, GroupLayout.PREFERRED_SIZE))
        );
        pnCapNhatNhanVien.setLayout(pnCapNhatNhanVienLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCapNhatNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 1313, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCapNhatNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(ActionEvent evt) {
		try {
			if(tglThem.isSelected()) {
				kiemTraDuLieu();
				if(qlSanPham.themSanPham(taoDoiTuongSanPham())) {
					JOptionPane.showMessageDialog(null, "Thêm thành công");
					xoaDuLieu();
					dongBangDuLieu();
					tglThem.setSelected(false);
					tglThem.setEnabled(true);
					tglSua.setEnabled(true);
					tblBangSanPham.setEnabled(true);
					hienThiDanhSachSanPham();
				}else {
					JOptionPane.showMessageDialog(null, "Thêm Thất Bại");
				}
			}else {
				kiemTraDuLieuSua();
				if(qlSanPham.capNhatSanPham(taoDoiTuongSanPham())) {
					JOptionPane.showMessageDialog(null, "Sủa thành công");
					xoaDuLieu();
					dongBangDuLieu();
					tglThem.setSelected(false);
					tglThem.setEnabled(true);
					tglSua.setSelected(false);
					tglSua.setEnabled(true);
					tblBangSanPham.setEnabled(true);
					hienThiDanhSachSanPham();
				}else {
					JOptionPane.showMessageDialog(null, "Sửa Thất Bại");
				}
			}
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
	}

	private void kiemTraDuLieu() throws Exception {
		String ten = txtTenSP.getText().trim();
		if(ten.isEmpty() || ten == null){
            throw new Exception("Tên không được rỗng");
        }else if(!ten.matches("^[\\p{L}\\p{Mn}\\p{Mc}\\s]+$")) {
        	throw new Exception("Tên không hợp lệ");
        }
		
		String giaThanh = txtGia.getText().trim();
		if(giaThanh.isEmpty() ) {
        	throw new Exception("Giá thành không được rỗng");
        }else if(!giaThanh.matches("[0-9.]+")) {
        	throw new Exception("Giá thành phải là số");
        }
		
		String anh = pnHinhNen.getHinhNen();
		if( anh == null ||anh.isEmpty()) {
			throw new Exception("Chưa chọn ảnh người dùng");
		}
		
		String kichThuoc = txtKichThuoc.getText().trim();
		if(kichThuoc.isEmpty() ) {
        	throw new Exception("Kích thước không được rỗng");
        }
		
		Date thoiGianSanXuat = dchThoiHanSXDuKien.getDate();
		if(thoiGianSanXuat.before(new Date())) {
			throw new Exception("Thời gian sản xuất phải lớn hơn thời gian hiện tại");
		}
		
		String soLuong = txtSoLuong.getText().trim();
		if(soLuong.isEmpty() ) {
        	throw new Exception("Số Lượng không được rỗng");
        }else if(!soLuong.matches("[0-9.]+")) {
        	throw new Exception("Số lượng phải là số");
        }
		
		String khoiLuong = txtKhoiLuong.getText().trim();
		if(khoiLuong.isEmpty() ) {
        	throw new Exception("Khối Lượng không được rỗng");
        }else if(!khoiLuong.matches("[0-9.]+")) {
        	throw new Exception("Khối lượng phải là số");
        }
		
	}
	
	private void kiemTraDuLieuSua() throws Exception {
		String ten = txtTenSP.getText().trim();
		if(ten.isEmpty() || ten == null){
            throw new Exception("Tên không được rỗng");
        }else if(!ten.matches("^[\\p{L}\\p{Mn}\\p{Mc}\\s]+$")) {
        	throw new Exception("Tên không hợp lệ");
        }
		
		String giaThanh = txtGia.getText().trim();
		if(giaThanh.isEmpty() ) {
        	throw new Exception("Giá thành không được rỗng");
        }else if(!giaThanh.matches("[0-9.]+")) {
        	throw new Exception("Giá thành phải là số");
        }
		
		String anh = pnHinhNen.getHinhNen();
		if( anh == null ||anh.isEmpty()) {
			throw new Exception("Chưa chọn ảnh người dùng");
		}
		
		String kichThuoc = txtKichThuoc.getText().trim();
		if(kichThuoc.isEmpty() ) {
        	throw new Exception("Kích thước không được rỗng");
        }
		
//		Date thoiGianSanXuat = dchThoiHanSXDuKien.getDate();
//		if(thoiGianSanXuat.before(new Date())) {
//			throw new Exception("Thời gian sản xuất phải lớn hơn thời gian hiện tại");
//		}
		
		String soLuong = txtSoLuong.getText().trim();
		if(soLuong.isEmpty() ) {
        	throw new Exception("Số Lượng không được rỗng");
        }else if(!soLuong.matches("[0-9.]+")) {
        	throw new Exception("Số lượng phải là số");
        }
		
		String khoiLuong = txtKhoiLuong.getText().trim();
		if(khoiLuong.isEmpty() ) {
        	throw new Exception("Khối Lượng không được rỗng");
        }else if(!khoiLuong.matches("[0-9.]+")) {
        	throw new Exception("Khối lượng phải là số");
        }
		
	}

	private void dienDuLieuSanPhamVaoBangThongTin(SanPham sanPham) {
    	DecimalFormat decimalFormat = new DecimalFormat("#.##");
		txtMaSanPham.setText(sanPham.getMaSanPham());
		txtTenSP.setText(sanPham.getTenSP());
		cmbLoaiGo.setSelectedItem(sanPham.getChatGo());
		txtKhoiLuong.setText(sanPham.getKhoiLuong()+"");
		txtKichThuoc.setText(sanPham.getKichThuoc());
		dchThoiHanSXDuKien.setDate(Date.from(sanPham.getThoiGianSanXuatDuKien().atStartOfDay(ZoneId.systemDefault()).toInstant()));
		txtSoLuong.setText(sanPham.getSoLuong()+"");
		txtGia.setText(decimalFormat.format(sanPham.getGiaThanh()));
		pnHinhNen.setNewBackground(sanPham.getAnh());
	}

	private void btnChonAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChonAnhMouseClicked
        // TODO add your handling code here:
        JFileChooser fchChonAnh = new JFileChooser();
        fchChonAnh.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File file) {
                if (file.isDirectory()) {
                    return true;
                }
                String fileName = file.getName().toLowerCase();
                return fileName.endsWith(".jpg") || fileName.endsWith(".png") || fileName.endsWith(".gif");
            }

            @Override
            public String getDescription() {
                return "Image Files (.jpg, .png, .gif)";
            }
        });
        int result = fchChonAnh.showOpenDialog(null);

        if(result == JFileChooser.APPROVE_OPTION){
            String path = fchChonAnh.getSelectedFile().getAbsolutePath();
            pnHinhNen.setNewBackground(path);
        }
    }//GEN-LAST:event_btnChonAnhMouseClicked


    private void tglThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglThemActionPerformed
        // TODO add your handling code here:
        if(tglThem.isSelected()){
            tglSua.setEnabled(false);
            tblBangSanPham.setEnabled(false);
            moBangDuLieu();
            tblBangSanPham.clearSelection();
            xoaDuLieu();
            dienMaSanPhamTiepTheoVaoForm();
        }else{
            tglSua.setEnabled(true);
            tblBangSanPham.setEnabled(true);
            dongBangDuLieu();
        }
    }//GEN-LAST:event_tglThemActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int lc = JOptionPane.showConfirmDialog(null, "Bạn Chắn chắn thoát chứ?", "Chú ý", JOptionPane.YES_NO_OPTION);
        if(lc==JOptionPane.YES_OPTION){
            tglSua.setEnabled(true);
            tglThem.setEnabled(true);
            tglThem.setSelected(false);
            tglSua.setSelected(false);
            tblBangSanPham.setEnabled(true);
            dongBangDuLieu();
            xoaDuLieu();
            txtMaSanPham.setText("");
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        tblBangSanPham.clearSelection();
        xoaDuLieu();
        txtMaSanPham.setText("");
        pnHinhNen.setNewBackground("img/profile.png");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tglSuaActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_tglSuaActionPerformed
        // TODO add your handling code here:
        int dongDaChon = tblBangSanPham.getSelectedRow();
        if(dongDaChon==-1){
        	tglSua.setSelected(false);
            throw new Exception("Chưa chọn sản phẩm cần sửa");       	
        }else{
            if(tglSua.isSelected()){
                moBangDuLieu();
                tglSua.setEnabled(false);
                tglThem.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tglSuaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        if(tglThem.isSelected()){
            xoaDuLieu();
        }else if(tglSua.isSelected()){
            layDuLieuTuDongTrenBang();
        }
    }//GEN-LAST:event_btnLamMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<LoaiGo> cmbLoaiGo;
    private com.toedter.calendar.JDateChooser dchThoiHanSXDuKien;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblKhoiLuong;
    private javax.swing.JLabel lblKichThuoc;
    private javax.swing.JLabel lblLoaiGo;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblThoiGianSXDuKien;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JPanel pnCapNhatNhanVien;
    private form.HinhNen pnHinhNen;
    private javax.swing.JPanel pnThongTinSanPham;
    private javax.swing.JScrollPane scrSanPham;
    private javax.swing.JTable tblBangSanPham;
    private javax.swing.JToggleButton tglSua;
    private javax.swing.JToggleButton tglThem;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtKhoiLuong;
    private javax.swing.JTextField txtKichThuoc;
    private javax.swing.JTextField txtMaSanPham;
    private javax.swing.JTextField txtNhapMa;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private DAO_SanPham qlSanPham;
    private DefaultTableModel modal;
    private JButton btnHDSD;
    // End of variables declaration//GEN-END:variables
    private void moBangDuLieu(){
        btnChonAnh.setEnabled(true);
        btnXacNhan.setEnabled(true);
        btnLamMoi.setEnabled(true);
        btnThoat.setEnabled(true);
        txtTenSP.setEnabled(true);
        cmbLoaiGo.setEnabled(true);
        txtKhoiLuong.setEnabled(true);
        txtSoLuong.setEnabled(true);
        txtGia.setEnabled(true);
        txtKichThuoc.setEnabled(true);
        dchThoiHanSXDuKien.setEnabled(true);
//        pnHinhNen.setNewBackground("");
    }
    
    private void dongBangDuLieu(){
    	txtMaSanPham.setText("");
        btnChonAnh.setEnabled(false);
        btnXacNhan.setEnabled(false);
        btnLamMoi.setEnabled(false);
        btnThoat.setEnabled(false);
        txtTenSP.setEnabled(false);
        cmbLoaiGo.setEnabled(false);
        txtKhoiLuong.setEnabled(false);
        txtSoLuong.setEnabled(false);
        txtGia.setEnabled(false);
        txtKichThuoc.setEnabled(false);
        dchThoiHanSXDuKien.setEnabled(false);
        pnHinhNen.setNewBackground("img/profile.png");
    }

    private void xoaDuLieu() {
        txtTenSP.setText("");
        cmbLoaiGo.setSelectedIndex(0);
        txtKhoiLuong.setText("");
        txtSoLuong.setText("");
        txtGia.setText("");
        txtKichThuoc.setText("");
        dchThoiHanSXDuKien.setDate(null);
    }
    
    private void btnHuongDanActionPerformed(ActionEvent evt) throws Exception {
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/huongDan/huongDanThongKeSP.png"));
        
        JPanel imagePanel = new JPanel();
        imagePanel.setLayout(new BoxLayout(imagePanel, BoxLayout.Y_AXIS));
        
        JLabel imageLabel1 = new JLabel(imageIcon);
        imagePanel.add(imageLabel1);
        
        JScrollPane scrollPane = new JScrollPane(imagePanel);
        scrollPane.setPreferredSize(new Dimension(1200, 700));
        
        scrollPane.getVerticalScrollBar().setUnitIncrement(20);
        scrollPane.getVerticalScrollBar().setBlockIncrement(100);
        
        JOptionPane.showMessageDialog(null, scrollPane, "Hướng dẫn thống kê sản phẩm", JOptionPane.PLAIN_MESSAGE);
	}
    
    private void hienThiDanhSachSanPham() {
    	DecimalFormat decimalFormat = new DecimalFormat("#.##");
        ArrayList<SanPham> dsSanPham = qlSanPham.layDanhSachSanPham();

        DefaultTableModel model = (DefaultTableModel) tblBangSanPham.getModel();
        model.setRowCount(0); // Xóa hết các dòng hiện tại trong table

        int stt = 1; // Biến đếm

        for (SanPham sp : dsSanPham) {
            String[] row = {
                stt+"",
                sp.getMaSanPham(),
                sp.getTenSP(),
                decimalFormat.format(sp.getGiaThanh()),               
                sp.getThoiGianSanXuatDuKien().toString(),
                sp.getChatGo().toString(),
                sp.getKhoiLuong()+""
            };
            model.addRow(row);
            stt++; // Tăng giá trị của biến đếm
        }
    }

    private void dienMaSanPhamTiepTheoVaoForm() {
        String ma;
		try {
			ma = DAO_SanPham.layMaSanPhamTiepTheo();
			txtMaSanPham.setText(ma);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
    }

    private void layDuLieuTuDongTrenBang() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private SanPham taoDoiTuongSanPham() {
    	String maSanPham = txtMaSanPham.getText();
        String tenSP = txtTenSP.getText().trim();
        double giaThanh = Double.parseDouble(txtGia.getText());
        LocalDate thoiGianSanXuatDuKien = dchThoiHanSXDuKien.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LoaiGo chatGo = (LoaiGo) cmbLoaiGo.getSelectedItem();
        String anh = pnHinhNen.getHinhNen();
        String kichThuoc = txtKichThuoc.getText().trim();
        int soLuong = Integer.parseInt(txtSoLuong.getText().trim());
        double khoiLuong = Double.parseDouble(txtKhoiLuong.getText().trim());
        return new SanPham(maSanPham, tenSP, giaThanh, thoiGianSanXuatDuKien, chatGo, anh, kichThuoc, soLuong, khoiLuong);
    }
}
