/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package form;

/**
 *
 * @author ACER
 */
public class ThongTinNhanVienDialog extends java.awt.Dialog {

    private static final long serialVersionUID = 1L;
	/**
     * Creates new form ThongTinNhanVienDialog
     */
    public ThongTinNhanVienDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnTieuDe = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        pnThongTin = new javax.swing.JPanel();
        hinhNen = new HinhNen();
        pnThongTinNhanVien = new javax.swing.JPanel();
        pnCV_PB = new javax.swing.JPanel();
        lblChucVu = new javax.swing.JLabel();
        lblDienChucVu = new javax.swing.JLabel();
        lblPhongBan = new javax.swing.JLabel();
        lblDienPhongBan = new javax.swing.JLabel();
        lblMaHoTe = new javax.swing.JPanel();
        lblMa = new javax.swing.JLabel();
        lblDienMa = new javax.swing.JLabel();
        lblHoTen1 = new javax.swing.JLabel();
        lblDienTen = new javax.swing.JLabel();
        pnNgay = new javax.swing.JPanel();
        lblNgaySinh = new javax.swing.JLabel();
        lblDienNgaySinh = new javax.swing.JLabel();
        lblngayVaoLam = new javax.swing.JLabel();
        lblDienNgayVaoLam = new javax.swing.JLabel();
        pnCanCuoc_SDT = new javax.swing.JPanel();
        lblCanCuoc = new javax.swing.JLabel();
        lblDienCangCuoc = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        lblDienSoDienThoai = new javax.swing.JLabel();
        pnLuong_HeSo = new javax.swing.JPanel();
        lblLuong = new javax.swing.JLabel();
        lblDienLuong = new javax.swing.JLabel();
        lblHeSo = new javax.swing.JLabel();
        lblDienHeSo = new javax.swing.JLabel();
        pnDC = new javax.swing.JPanel();
        lblDiaChi = new javax.swing.JLabel();
        dcrDiaChi = new javax.swing.JScrollPane();
        txADiaChi = new javax.swing.JTextArea();
        pnEmail = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        lblDienEmail = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(500, 800));
        setMinimumSize(new java.awt.Dimension(500, 700));
        setPreferredSize(new java.awt.Dimension(500, 700));
        setTitle("Thông Tin Nhân Viên");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
        pnMain.setPreferredSize(new java.awt.Dimension(500, 600));
        pnMain.setLayout(new java.awt.BorderLayout());

        pnTieuDe.setLayout(new java.awt.BorderLayout());

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("Thông tin Nhân Viên");
        lblTieuDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setOpaque(true);
        pnTieuDe.add(lblTieuDe, java.awt.BorderLayout.CENTER);

        pnMain.add(pnTieuDe, java.awt.BorderLayout.NORTH);

        pnThongTin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout hinhNenLayout = new javax.swing.GroupLayout(hinhNen);
        hinhNen.setLayout(hinhNenLayout);
        hinhNenLayout.setHorizontalGroup(
            hinhNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        hinhNenLayout.setVerticalGroup(
            hinhNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        pnThongTinNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTinNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        lblChucVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChucVu.setText("Chức vụ");

        lblDienChucVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblPhongBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhongBan.setText("Phòng ban");

        lblDienPhongBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnCV_PBLayout = new javax.swing.GroupLayout(pnCV_PB);
        pnCV_PB.setLayout(pnCV_PBLayout);
        pnCV_PBLayout.setHorizontalGroup(
            pnCV_PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCV_PBLayout.createSequentialGroup()
                .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienPhongBan, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
        );
        pnCV_PBLayout.setVerticalGroup(
            pnCV_PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
            .addComponent(lblDienChucVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPhongBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDienPhongBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblMa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMa.setText("Mã");

        lblDienMa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblHoTen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoTen1.setText("Họ Tên");

        lblDienTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout lblMaHoTeLayout = new javax.swing.GroupLayout(lblMaHoTe);
        lblMaHoTe.setLayout(lblMaHoTeLayout);
        lblMaHoTeLayout.setHorizontalGroup(
            lblMaHoTeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblMaHoTeLayout.createSequentialGroup()
                .addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienMa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienTen, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lblMaHoTeLayout.setVerticalGroup(
            lblMaHoTeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMa, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
            .addComponent(lblDienMa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblHoTen1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDienTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblNgaySinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgaySinh.setText("Ngày Sinh");

        lblDienNgaySinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblngayVaoLam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblngayVaoLam.setText("Ngày làm");

        lblDienNgayVaoLam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnNgayLayout = new javax.swing.GroupLayout(pnNgay);
        pnNgay.setLayout(pnNgayLayout);
        pnNgayLayout.setHorizontalGroup(
            pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNgayLayout.createSequentialGroup()
                .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblngayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienNgayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
        );
        pnNgayLayout.setVerticalGroup(
            pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
            .addComponent(lblDienNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblngayVaoLam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDienNgayVaoLam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblCanCuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCanCuoc.setText("Căn cước");

        lblDienCangCuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblSoDienThoai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoDienThoai.setText("SDT");

        lblDienSoDienThoai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnCanCuoc_SDTLayout = new javax.swing.GroupLayout(pnCanCuoc_SDT);
        pnCanCuoc_SDT.setLayout(pnCanCuoc_SDTLayout);
        pnCanCuoc_SDTLayout.setHorizontalGroup(
            pnCanCuoc_SDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCanCuoc_SDTLayout.createSequentialGroup()
                .addComponent(lblCanCuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienCangCuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
        );
        pnCanCuoc_SDTLayout.setVerticalGroup(
            pnCanCuoc_SDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCanCuoc, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
            .addComponent(lblDienCangCuoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDienSoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLuong.setText("Lương cb");

        lblDienLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblHeSo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeSo.setText("Hệ số");

        lblDienHeSo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnLuong_HeSoLayout = new javax.swing.GroupLayout(pnLuong_HeSo);
        pnLuong_HeSo.setLayout(pnLuong_HeSoLayout);
        pnLuong_HeSoLayout.setHorizontalGroup(
            pnLuong_HeSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLuong_HeSoLayout.createSequentialGroup()
                .addComponent(lblLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeSo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienHeSo, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
        );
        pnLuong_HeSoLayout.setVerticalGroup(
            pnLuong_HeSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
            .addComponent(lblDienLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblHeSo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDienHeSo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblDiaChi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiaChi.setText("Địa chỉ");

        txADiaChi.setColumns(20);
        txADiaChi.setRows(5);
        txADiaChi.setEnabled(false);
        dcrDiaChi.setViewportView(txADiaChi);

        javax.swing.GroupLayout pnDCLayout = new javax.swing.GroupLayout(pnDC);
        pnDC.setLayout(pnDCLayout);
        pnDCLayout.setHorizontalGroup(
            pnDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDCLayout.createSequentialGroup()
                .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcrDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
        );
        pnDCLayout.setVerticalGroup(
            pnDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDCLayout.createSequentialGroup()
                .addGroup(pnDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(dcrDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email");

        lblDienEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnEmailLayout = new javax.swing.GroupLayout(pnEmail);
        pnEmail.setLayout(pnEmailLayout);
        pnEmailLayout.setHorizontalGroup(
            pnEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEmailLayout.createSequentialGroup()
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDienEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
        );
        pnEmailLayout.setVerticalGroup(
            pnEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
            .addComponent(lblDienEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnThongTinNhanVienLayout = new javax.swing.GroupLayout(pnThongTinNhanVien);
        pnThongTinNhanVien.setLayout(pnThongTinNhanVienLayout);
        pnThongTinNhanVienLayout.setHorizontalGroup(
            pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnLuong_HeSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnCanCuoc_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaHoTe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnCV_PB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        pnThongTinNhanVienLayout.setVerticalGroup(
            pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblMaHoTe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnCV_PB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnCanCuoc_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnLuong_HeSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnThongTinLayout = new javax.swing.GroupLayout(pnThongTin);
        pnThongTin.setLayout(pnThongTinLayout);
        pnThongTinLayout.setHorizontalGroup(
            pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(hinhNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
            .addComponent(pnThongTinNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnThongTinLayout.setVerticalGroup(
            pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(hinhNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnThongTinNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnMain.add(pnThongTin, java.awt.BorderLayout.CENTER);

        add(pnMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThongTinNhanVienDialog dialog = new ThongTinNhanVienDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void chuyenThanhFormCongNhan() {
    	lblTieuDe.setText("Thông Tin Công Nhân");
    	lblChucVu.setText("Chuyên Môn");
    	lblPhongBan.setText("Giới Tính");
    	lblLuong.setText("Trạng Thái");
    	lblHeSo.setText("Phụ Cấp");
    	pnEmail.setVisible(false);
    }
    public void caiDuLieuVaoForm(String path, String ma, String hoVaTen, String tenChucVu,
			String tenPhongBan, String ngaySinh, String ngayVaoLam,
			String canCuoc, String sdt, String luong, String heSoLuong,
			String diaChi, String email) {
		hinhNen.setNewBackground(path);
		lblDienMa.setText(ma);
		lblDienTen.setText(hoVaTen);
		lblDienChucVu.setText(tenChucVu);
		lblDienPhongBan.setText(tenPhongBan);
		lblDienNgaySinh.setText(ngaySinh);
		lblDienNgayVaoLam.setText(ngayVaoLam);
		lblDienCangCuoc.setText(canCuoc);
		lblDienSoDienThoai.setText(sdt);
		lblDienLuong.setText(luong);
		lblDienHeSo.setText(heSoLuong);
		txADiaChi.setText(diaChi);
		lblDienEmail.setText(email);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane dcrDiaChi;
    private HinhNen hinhNen;
    private javax.swing.JLabel lblCanCuoc;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblDienCangCuoc;
    private javax.swing.JLabel lblDienChucVu;
    private javax.swing.JLabel lblDienEmail;
    private javax.swing.JLabel lblDienHeSo;
    private javax.swing.JLabel lblDienLuong;
    private javax.swing.JLabel lblDienMa;
    private javax.swing.JLabel lblDienNgaySinh;
    private javax.swing.JLabel lblDienNgayVaoLam;
    private javax.swing.JLabel lblDienPhongBan;
    private javax.swing.JLabel lblDienSoDienThoai;
    private javax.swing.JLabel lblDienTen;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHeSo;
    private javax.swing.JLabel lblHoTen1;
    private javax.swing.JLabel lblLuong;
    private javax.swing.JLabel lblMa;
    private javax.swing.JPanel lblMaHoTe;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblPhongBan;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblngayVaoLam;
    private javax.swing.JPanel pnCV_PB;
    private javax.swing.JPanel pnCanCuoc_SDT;
    private javax.swing.JPanel pnDC;
    private javax.swing.JPanel pnEmail;
    private javax.swing.JPanel pnLuong_HeSo;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnNgay;
    private javax.swing.JPanel pnThongTin;
    private javax.swing.JPanel pnThongTinNhanVien;
    private javax.swing.JPanel pnTieuDe;
    private javax.swing.JTextArea txADiaChi;
    // End of variables declaration//GEN-END:variables
}
